### ISSUE TITLE
Bashed Patched is placed in Data folder (SE)

### ISSUE THREAD

**Issue by TechAngel85** [ModOrganizer2/modorganizer#208] opened 2018-01-21 01:27 UTC
# The problem

Whenever WB is ran via MO2 and the Bashed Patch is ran for the first time it is placed in the SSE Data folder rather than in the Overwrite folder. 

# Environment

* Mod Organizer Version that exhibits the issue: v2.1.1
* Desktop OS/version used to run Mod Organizer: Windows 7 64-bit.

# Details

Users do not need to complete this process. The issue is a bit deeper. Read the comments below to find out more.

To reproduce this:
1. Download latest WB (SE) from nexus
2. Uninstall WB, if necessary
3. Reinstall WB to the standard directory (SE root) and as the "standalone" version (not the python version)
4. Run WB to ensure it's installed, initialized, and running correctly
5. Delete the "Bashed Patch" from SE Data directory
6. Download latest MO2 from nexus
7. Extract MO2 to: C:\MOTest
8. Download latest USVFS from Discord (Beta5)
9. Extract files to :C:\MOTest
10. Choose "copy and replace" for both conflicts
11. Delete usvfs_proxy.exe
12. Run MO2 from C:\MOTest
13. Click game selection dialog button (13-15 are necessary because I have MO2 installed and set up already)
14. Click Yes
15. Choose Portable
16. Put DLC in correct order in left pane
17. Add WB as an executable
18. Click settings and then Diagnostics tab
19. Change Log Level to Debug
20. Click OK
21. Close MO2
22. Delete logs
23. Run MO2 again
24. Run WB from the drop-down menu
25. Once WB is open, right-click the Bashed Patch
26. Choose Rebuild Patch
27. Click on "Tweak Settings"
28. Change the following:
   - Arrow: Recovery from Actor [50%]
   - Arrow: Speed [x 1.4]
   - Crime: Alarm Distance [Custom] 1200.00
   - Timescale: [Custom] 15.00
29. Click Build Patch
30. Once the prompt is displayed, click OK
31. Click "Yes" to activate Bashed Patch prompt
32. Click the red X to close WB
33. Check MO2 Overwrite folder ...and the only contents I have are an "_INI Tweaks_" and "_Docs_" folder
34. Check the SE _Data_ folder ...and that is where the Batched Patch resides on my end.

# Link to Mod Organizer logs

Here are the full logs: https://mega.nz/#!48sghJ5D!cUw6K2FIC3ty0G1HrcRSFM-pIzhpH2fkNldl3yE7sRo

**Comment by erasmux** [comment] 2018-01-21 05:04
This seems to be a problem when the temp folder and the game folder are on different drives. I will investigate it further and will see if we can workaround it but this may be a serious problem with the way usvfs is currently implemented.

To verify this and also as a possible workaround define an environment variable TMPDIR with the path to a temp directory on the same drive as the game folder (or install the game on the same drive as the default temp directory which should be on same drive you installed windows).
- If you want to do this as a temporary test, I suggest openning a CMD window and entering a command similar to `set TMPDIR=D:\Temp` and then running MO from this CMD window (you can drag the MO executable to the CMD window) and finally run WB from this MO.
- If you want to use this as a more permanent workaround set this as a system variable in the windows system properties / environment variables.

**Comment by TechAngel85** [comment] 2018-01-21 05:37
I can verify the workaround works. Changing your temporarily variables to the same drive as the game folder is location corrects the issue. The Bashed Patch is now being found in the Overwrite folder as it should be.

For the less savvy, here's an easy to follow guide on how to change these variables:
https://www.howtogeek.com/285710/how-to-move-windows-temporary-folders-to-another-drive/

**Comment by Yoosk** [comment] 2018-01-21 10:56
Seems that issue is bound to windows 7 x64, as i got same issue using that OS, while my TMP is on C drive, game and WB on E drive.

**Comment by Silarn** [comment] 2018-02-08 00:17
Not sure if erasmux has looked into a fix for this yet.

**Comment by Silarn** [comment] 2018-04-08 05:36
I'm not aware of any recent reports for this and I don't think any devs can replicate. If it was a problem it's probably fixed in dev builds.

**Comment by Al12rs** [comment] 2018-04-11 06:26
People have reported this problem again on the dev builds so I'm reopening this. Still not able to reproduce myself.

**Comment by Silarn** [comment] 2018-04-11 06:36
It probably only happens if usvfs is failing for another reason, because then nothing gets rerouted.

**Comment by Al12rs** [comment] 2018-12-19 09:07
Have you tried creating an empty `docs` folder in the game Data folder? Make sure to delete the bashed patch

**Comment by Al12rs** [comment] 2019-06-25 22:03
This should have been fixed in 2.2.0, or possibly with recent usvfs patches on disocrd if that is not the case.
Could you please test if the issue is resolved? 
If no response within 20 days we will assume the issue resolved.
If that is not the case we will later re-open the issue.

**Comment by Al12rs** [comment] 2019-10-17 09:33
Closing this assuming resolved, please reopen if not the case.

**Closed by Al12rs** 2019-10-17 09:33 UTC
Labels: Windows 7, Wrye Bash, bug, potential fix, usvfs, waiting on user
