### ISSUE TITLE
failed to receive data from secondary instance: unknown error

### ISSUE THREAD

**Issue by LordFess8937** [ModOrganizer2/modorganizer#542] opened 2018-10-01 21:46 UTC
# The problem
When I try to download mods from Nexus with the new MO2 updated app I receive the error you see in the post title. The error box has an "OK" button but it will not close the error message and MO2 is locked to me. All I can do is reboot the system. MO2 was working fine last night.....

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.5 / Skyrim Special Edition
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Previous to the one above
* Desktop OS/version used to run Mod Organizer: Windows 10 Profesional

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Project579** [comment] 2018-10-09 17:37
next time you can try closing MO2 using the Task Manager no need to reboot.

Try registering the MO2 handler again: run the file called nxmhandler.exe in MO2 folder.

**Comment by Al12rs** [comment] 2019-02-17 11:28
Basically this seems to happen when the seconday Mow instance created to handle the nexus link doesn't recieve a reply from the primary on in time. With this: 
https://github.com/ModOrganizer2/modorganizer/commit/c19ba153376f5d8f4026a46701bb0f7c115c1651 the amount of errors is decreased a lot and it only happens when the first instance is actually overloaded.

**Comment by JiNama** [comment] 2019-06-17 21:33
I know this is closed, but I'm still having this issue. Is there anything I can do?

**Comment by Al12rs** [comment] 2019-06-17 21:34
This exact error message (failed to recieve data from secondary instance: unknown error)? On what version of Mo2 are you on?

**Comment by JiNama** [comment] 2019-06-17 21:36
Yes, the very same. Most recent version, 2.2.0.

**Comment by Al12rs** [comment] 2019-06-18 07:18
Could you specify steps to reproduce and upload the interface log?

**Comment by LostDragonist** [comment] 2019-06-18 07:36
I know one instance of this error can occur when downloading mods too quickly.  Something about the communication between the instances breaks down.  Slowing down on starting new downloads helps prevent the issue.

**Comment by JiNama** [comment] 2019-06-18 10:48
### Steps To Reproduce

1. Download mods relatively quickly from nexusmods.com

GIST of [mo_interface.log](https://gist.github.com/JiNama/d4e5c57120f1e96884827fb0efff3baa)

Also, I am aware of that @LostDragonist; however, other mod managers like Vortex and NMM do not have this issue, and when I'm modding my game, I download a lot of mods at once, so this can get annoying.

**Comment by Al12rs** [comment] 2019-06-18 10:53
I don't really know what can be done to improve this. przester already tried and it seems it's simply the program not keeping up with the request.

**Comment by JiNama** [comment] 2019-06-18 10:56
It's very strange because this wasn't an issue a while ago (maybe six months ago?). Unfortunate, but if there's nothing you can do then it's not a big deal. Thanks for trying anyway Al.

**Comment by Al12rs** [comment] 2019-06-18 11:00
I will leave this open and maybe someone in the future might be able to fix this properly.

**Comment by AndreyRainchik** [comment] 2019-07-24 04:22
The error message is triggered in the SingleInstance::receiveMessage() method of [singleinstance.cpp](https://github.com/ModOrganizer2/modorganizer/blob/Develop/src/singleinstance.cpp), by the `!socket->waitForReadyRead(s_Timeout)` call failing. The `socket` is a QLocalSocket, which [calls](https://code.woboq.org/qt5/qtbase/src/network/socket/qlocalsocket_tcp.cpp.html#436) the waitForReadyRead() method on a tcp socket, which I believe inherits from a QAbstractSocket. The waitForReadyRead() [documentation](https://doc.qt.io/qt-5/qabstractsocket.html#waitForReadyRead) says that "Note: This function may fail randomly on Windows," so I think this is the source of the issue. The documentation says as a fix to "Consider using the event loop and the readyRead() signal if your software will run on Windows."

**Closed** 2019-10-31 13:09 UTC
Labels: bug

**Comment by darksynth0** [comment] 2019-11-15 16:56
Having the same issue and it bugs me for several months. It was fine like ~7-8 months ago. happens to me when I download few optional files for a mod in a rapid succession.

**Comment by isanae** [comment] 2019-11-15 17:23
@darksynth0 This will be released in the next version of MO. We don't have a date for this release yet.

**Comment by darkphoenixff4** [comment] 2019-12-23 03:08
I get this error constantly while downloading mods.

**Comment by darksynth0** [comment] 2019-12-23 19:19
Install latest version

пн, 23 дек. 2019 г., 6:08 Kelly Miller <notifications@github.com>:
