### ISSUE TITLE
When sorting, getting "failed to parse condition" for an esp that is not present

### ISSUE THREAD

**Issue by ChaoticLogic** [ModOrganizer2/modorganizer#950] opened 2019-12-28 16:35 UTC
MO2 v 2.2.1
When using the sort plugins button, it fails with exit code 1.  The log gives these error messages:

10: 29: 28 [D] Updating VFS mappings...
10: 29: 29 [D] VFS mappings updated <linked 84 dirs, 5 files>
10: 29: 30 [D] [loot] Failed to parse condition "not is_master("OCW_Obscure's_CollegeofWinterhold.esp")". Details: An error was encountered while parsing the expression "not is_master(\"OCW_Obscure's_CollegeofWinter...
10: 29: 30 [D] [loot] LOOT failed: yaml-cpp: error at line 12418, column 9: bad conversion: invalid condition syntax: Failed to parse condition "not is_master("OCW_Obscure's_CollegeofWinterhold.esp")". Details: An e...

I am not using College of Winterhold nor do I have any mod that requires it.  Using LOOT from within MO2 (via drop down menu) works fine and sorts properly with no error.

**Comment by LostDragonist** [comment] 2019-12-28 20:19
Can you provide a complete mo_interface.log file for when this happens?

[You can find it here.](https://cdn.discordapp.com/attachments/265929299490635777/598691407657435137/open-folders-menu.png)

**Comment by Al12rs** [comment] 2019-12-28 20:21
Yeah we would need the full log. What I can think of is that either there is a random plugin somewhere that is causing that or the 2.1.1 version of loot is not able to parse the masterlists correctly. In that case testing with the latest Dev builds from discord could let us see if that is the case.

**Comment by ChaoticLogic** [comment] 2019-12-28 21:26
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/4007472/mo_interface.log)
As requested and I think Al12rs might be on the right track as this did not occur before I updated MO2.
If it helps, or is relevant, I'm also using LOOT 0.15.1 build 82c756e1.

**Comment by Al12rs** [comment] 2019-12-28 21:32
I think you have your plugins.txt or loadorder.txt set as readonly, can you check whether that is the case? You can access those files from the profile folder (use the Open Folder menu you used for the logs)

**Comment by ChaoticLogic** [comment] 2019-12-28 21:36
No, neither plugins.txt or loadorder.txt are set to readonly.

**Comment by Al12rs** [comment] 2019-12-28 21:37
Any idea why you get all the missing plugin entries in the logs?

**Comment by ChaoticLogic** [comment] 2019-12-28 21:45
Yes. I'm investigating the cause of a repetitive CTD at Dragon's Bridge. To do so, I copied my main profile over to a testing profile, then disabled all the mods.  I'm gradually re-enabling them, sorting, and coc'ing to the cell to find out which mod is causing the issue.  Ironically, it was my search for the culprit plugin that lead to my discovery of this sorting glitch.

**Comment by Al12rs** [comment] 2019-12-28 21:51
Then I guess you should try the latest dev build to see if it still happens to you.
Here is the link to Discord where you can get it. Just extract the archive version somewhere and start it, it should pick up your existing setup automatically.

**Comment by ChaoticLogic** [comment] 2019-12-28 22:05
Success!  Version 2.2.2 RC5.1 performed the sort successfully.  Also, my compliments on the delivery of LOOT's warnings and error messages afterward. That's a nice touch!

**Comment by Al12rs** [comment] 2019-12-28 22:08
That is good to hear. You should probably read the changelog before using the dev build though: 
https://github.com/ModOrganizer2/modorganizer/wiki/Mod-Organizer-2-Development-Changelog#mod-organizer-v222---alpha-build-2

**Comment by Al12rs** [comment] 2019-12-28 22:09
Since the new version works I'm going to assume that the problem was caused by a change in the masterlist format that the old version of loot was unable to correctly parse. We plan to release 2.2.2 soon(TM) so I'm going to close this in the meantime

**Closed by Al12rs** 2019-12-28 22:09 UTC

**Comment by isanae** [comment] 2019-12-29 13:13
Note that this only happens if you run LOOT 0.15 externally and _then_ try to sort within MO. If you only use the Sort button, 2.2.1 still works fine. As a workaround, you can delete the folder `C:\Users\username\AppData\Local\LOOT`, restart MO and sort again, but the problem will reappear the next time you run LOOT 0.15 externally.
