### ISSUE TITLE
MO does not run from game directory

### ISSUE THREAD

**Issue by cfs3rd** [ModOrganizer2/modorganizer#146] opened 2017-12-13 19:32 UTC
When MO is installed within the game directory there are all kinds of vfs issues. Just did another test to pull fresh logs and only LOOT appears to have issues. Last night when testing there were all kinds of issues and most tools would not run. 
MO installed to: C:\Steam\steamapps\common\Skyrim Special Edition\MO2

Erasmus 12/12 build
Windows 10 Pro 1709 16299.64 UAC off

LOOT 0.12.1 Open with blank screen then the browser open with special/ in the address bar
uvfs log: https://www.dropbox.com/s/3yxn722r69r51zy/usvfs-2017-12-13_19-19-35.log?dl=0
interface log: https://www.dropbox.com/s/nt4bzffnzaig3y7/mo_interface.log?dl=0

Thanks, cfs111

**Comment by Silarn** [comment] 2017-12-13 21:12
If there are any reliable steps to replicate this, they would be welcome. As usual, the developers are having difficulty getting this to happen.

**Comment by cfs3rd** [comment] 2017-12-14 02:55
With newest 12/13 build the issue is no longer present. I can no longer reproduce it. But all that was necessary before was to run any application. WB ran with messed up load order and some mods disabled. Bodyslide errored out. Last night no issues with any application except LOOT. Tonight on newest build, no issues. Not running the experimental from erasmux.

**Comment by cfs3rd** [comment] 2017-12-16 05:53
Issues are back with latest 12/15 build. LOOT presenting the same issue. FNIS does not read all animations, and output is goes into overwrite. Bodyslide fails with; Failed to load setup.xrc file. Wrye opens with no mods. Let me know which logs you want.

**Comment by Silarn** [comment] 2017-12-27 08:48
Is this still an issue on recent builds?

**Comment by cfs3rd** [comment] 2017-12-28 00:55
12/26 build from discord.
WB - the patch goes to overwrite, but a docs folder goes into data
LOOT - Does not begin to parse files and opens browser to blank page special/
XEdit - runs fine
FNIS produces the following warning ">>Warning: Bad installation. Generator not run from <Skyrim_Data>\Tools\GenerateFNIS_for_Users.<<
Skyrim SE 64bit: ??.??.?? - C:\Steam\steamapps\common\Skyrim Special Edition\ (Steam)
Expected generator path: C:\Steam\steamapps\common\Skyrim Special Edition\data\tools\GenerateFNIS_for_Users" and does the output does not go to overwrite. It just seems to disappear. 
Not even going to try Bodyslide since it appears some stuff is being written into data folder.

If you ask something from me here and I do not respond in a day or so feel free to pm or @ me on discord.
Thanks, cfs111

**Comment by Al12rs** [comment] 2018-02-09 11:50
For future reference this seems to be fixed with usvfs 0.31 beta5 available on discord but has not been testet extensively enough to be sure and the original cause of the problem is still unknown.

**Comment by Al12rs** [comment] 2018-02-12 14:22
People have reported that the problem persist with usvfs 0.31 beta 5.

**Comment by Al12rs** [comment] 2019-01-19 22:01
Merging into #169 for organization

**Closed by Al12rs** 2019-01-19 22:01 UTC
Labels: bug, needinfo, needs investigation
