### ISSUE TITLE
When opening the 'Information' dialogue upon first starting MO2 Qt errors occur

### ISSUE THREAD

**Issue by GrantSP** [Modorganizer2/modorganizer#182] opened 2017-12-29 23:39 UTC
# The problem

Whe I first start MO2 and then open the 'Information' Dialogue, either by double-clicking or the context menu, I am greeted by a series of Qt related error messages

# Environment

* Mod Organizer Version that exhibits the issue: **2.1.1 installer version**
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10 v1709 build 16299,125

# Details
NA

# Link to Mod Organizer logs

usvfs log
## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

The vfs log is very small:

> 10:32:46.229 [D] remove from process 11248
> 10:32:46.229 [I] create config in 11248
> 10:32:46.229 [I] 0 processes - 0
> 10:32:46.229 [I] mod_organizer_instance_1 created in process 11248
> 10:32:46.229 [I] attached to mod_organizer_instance_1 with 1 nodes, size 65536
> 10:32:46.229 [I] inv_mod_organizer_instance_1 created in process 11248
> 10:32:46.229 [I] attached to inv_mod_organizer_instance_1 with 1 nodes, size 65536
> 10:32:46.229 [D] context current shm: mod_organizer_instance (now 2 connections)

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!
[interface log](https://pastebin.com/ExHUizQt)

## Screenshots
![1](https://user-images.githubusercontent.com/3291695/34449569-accd4ad0-ed4d-11e7-9c81-e4bbd37efbf3.png)
![2](https://user-images.githubusercontent.com/3291695/34449570-ad04f598-ed4d-11e7-90e7-7955bba7afe0.png)
![3](https://user-images.githubusercontent.com/3291695/34449571-ad3ce408-ed4d-11e7-9783-648493699d9c.png)
![4](https://user-images.githubusercontent.com/3291695/34449572-ad741f54-ed4d-11e7-9ec4-7e7388dc01c7.png)
![5](https://user-images.githubusercontent.com/3291695/34449573-adaada94-ed4d-11e7-9753-88e3f67827a0.png)
![6](https://user-images.githubusercontent.com/3291695/34449574-ade11b90-ed4d-11e7-9acc-c9c171e1017f.png)
![7](https://user-images.githubusercontent.com/3291695/34449576-ae18920a-ed4d-11e7-989a-bf2aa9b85284.png)
![8](https://user-images.githubusercontent.com/3291695/34449577-ae4ff6e6-ed4d-11e7-8d60-7573a423fb7e.png)

**Comment by Silarn** [comment] 2018-01-02 03:12
This looks like another QT DLLs-in-path type issue. This could be caused during compilation if the compiler links to the wrong Qt DLLs - but the installer releases haven't exhibited this issue for others.

For some reason MO must be using another version of the QtWebEngine.exe that is a mismatch to the included dlls.

**Comment by GrantSP** [comment] 2018-01-02 03:53
The screenshots are from the installer version as I was testing that out but today I grabbed a standalone version for the FO4 tests and that install is also doing it.
I think this may be related to my trying to get my build systemsetup as I don't recall these ever happening before.

**Comment by Silarn** [comment] 2018-01-05 18:11
FYI Windows CMake is known to install a version of Qt on the path. So I'd start looking there.

**Comment by GrantSP** [comment] 2018-01-05 21:14
Nothing in my path that is Qt related.

**Comment by maki-chan** [comment] 2018-01-23 13:19
I had this problem, too, and I found CMake in my PATH variable. After removing the path (in my case it was `E:\Program Files\CMake\bin`) from the PATH environment variable, the errors are gone and MO2 works as intended when opening the mod information dialog.

**Comment by GrantSP** [comment] 2018-01-23 22:03
That is it! It's fixed now.
Now the only question I have is why are all those with the dev setup not seeing that same error?

**Comment by AnyOldName3** [comment] 2018-03-02 23:54
I have this, and it isn't fixed by removing CMake from my PATH

**Comment by AnyOldName3** [comment] 2018-03-03 00:06
If I run it from within PowerShell, the error messages go away, but the embedded Nexus description page in the info dialogue is still absent.

**Comment by AnyOldName3** [comment] 2018-03-03 00:40
Interestingly, this works with CMake on my path as long as APITrace is removed, which also has QT DLLs.

**Comment by SuperSandro2000** [comment] 2018-03-03 07:49
I looked trough all my environment variables and couldn't find anything related to APITrace. Which programm installs that?

**Comment by Silarn** [comment] 2018-03-03 08:22
There is a change discussed on discord that should fix this issue. The application was appending the dll directory to the path when it should have prepended it. We can include this in the next release.

**Comment by AnyOldName3** [comment] 2018-03-03 12:17
@SuperSandro2000 as I mentioned on Discord, APITrace is an OpenGL, Direct3D and Vulkan debugger, so you'd know if you had it. It just has Qt DLLs in its bin directory, so if you put it on the path, the DLLs end up on the path too.

**Comment by SuperSandro2000** [comment] 2018-03-03 12:18
Ohhh know everything makes sense.

**Closed** 2018-04-13 15:49 UTC
Labels: bug, fixed in next release, potential fix
