### ISSUE TITLE
Exclude directory setting for conflict check.

### ISSUE THREAD

**Issue by Xanardi** [ModOrganizer2/modorganizer#1138] opened 2020-06-16 06:13 UTC
**Is your feature request related to a problem? Please describe.**
If you "git init" in each mod directory, the contents under the ".git" directory will be displayed as a conflict.

**Describe the solution you'd like**
I want to be able to manage various mods as git submodules.

**Describe alternatives you've considered**
I want to exclude directory and below from the target of conflict check. (Ex. ".git", ".hg")

**Comment by Al12rs** [comment] 2020-06-16 13:12
duplicate of #760

**Closed by Al12rs** 2020-06-16 13:12 UTC
Labels: Feature Request
