### ISSUE TITLE
Can't Install Mod Organizer

### ISSUE THREAD

**Issue by Kronos6419** [Modorganizer2/modorganizer#368] opened 2018-05-18 08:25 UTC
# The problem

When installing, a transfer error displays when extracting qwindowsvistastyle.dll 

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

Delete file: C:\Games\ModOrganizer.exe
Delete file: C:\Games\helper.exe
Delete file: C:\Games\usvfs_x64.dll
Delete file: C:\Games\usvfs_x86.dll
Delete file: C:\Games\usvfs_proxy_x86.exe
Delete file: C:\Games\usvfs_proxy_x64.exe
Delete file: C:\Games\nxmhandler.exe
Delete file: C:\Games\uibase.dll
Delete file: C:\Games\ssleay32.dll
Delete file: C:\Games\QtWebEngineProcess.exe
Delete file: C:\Games\libeay32.dll
Delete file: C:\Games\boost_python27-vc141-mt-x64-1_67.dll
Delete file: C:\Games\loot\lootcli.exe
Delete file: C:\Games\loot\loot_api.dll
Delete file: C:\Games\platforms\qwindows.dll
Delete file: C:\Games\styles\qwindowsvistastyle.dll
Delete file: C:\Games\QtQuick.2\plugins.qmltypes
Delete file: C:\Games\QtQuick.2\qmldir
Delete file: C:\Games\QtQuick.2\qtquick2plugin.dll
Delete file: C:\Games\plugins\bsa_extractor.dll
Delete file: C:\Games\plugins\installer_bundle.dll
Delete file: C:\Games\plugins\diagnose_basic.dll
Delete file: C:\Games\plugins\inibakery.dll
Output folder: C:\Games
Extract: ModOrganizer.exe
Extract: helper.exe
Extract: usvfs_x64.dll
Extract: usvfs_x86.dll
Extract: usvfs_proxy_x86.exe
Extract: usvfs_proxy_x64.exe
Extract: nxmhandler.exe
Extract: uibase.dll
Extract: QtWebEngineProcess.exe
Extract: libeay32.dll
Extract: ssleay32.dll
Extract: boost_python27-vc141-mt-x64-1_67.dll
Output folder: C:\Games\loot
Extract: lootcli.exe
Extract: loot_api.dll
Output folder: C:\Games\plugins
Extract: installer_bundle.dll
Extract: diagnose_basic.dll
Extract: bsa_extractor.dll
Extract: inibakery.dll
Create folder: C:\Games\logs
Output folder: C:\Games\licenses
Extract: 7zip.txt
Extract: AntlrBuildTask.txt
Extract: Castle.txt
Extract: DXTex.txt
Extract: GNU-LGPL-v2.1.txt
Extract: GPL-v2.0.txt
Extract: GPL-v3.0.txt
Extract: LGPL-v3.0.txt
Extract: boost.txt
Extract: cpptoml.txt
Extract: fmt.txt
Extract: openssl.txt
Extract: python.txt
Extract: sip.txt
Extract: spdlog.txt
Extract: udis86.txt
Output folder: C:\Games\platforms
Extract: qwindows.dll
Output folder: C:\Games\QtQuick.2
Extract: qtquick2plugin.dll
Extract: qmldir
Extract: plugins.qmltypes
Output folder: C:\Games\DLLs
Extract: 7z.dll
Extract: archive.dll
Extract: libeay32.dll
Extract: ssleay32.dll
Extract: liblz4.dll
Output folder: C:\Games\resources
Extract: icudtl.dat
Extract: qtwebengine_devtools_resources.pak
Extract: qtwebengine_resources.pak
Extract: qtwebengine_resources_100p.pak
Extract: qtwebengine_resources_200p.pak
Output folder: C:\Games\styles
Extract: qwindowsvistastyle.dll
download failed: Transfer Error

**Comment by Al12rs** [comment] 2018-05-18 08:38
Does this issue happen every time you try at the same point?

**Comment by trrm** [comment] 2018-05-18 08:54
I have almost the same problem but instead of transfer error I get "SendRequest Error". Same thing happens with an old installer (2.1.1) that worked with no problem. I assume this is a temporary network (GitHub?) issue.

**Comment by Al12rs** [comment] 2018-05-18 08:56
@trrm are you on win 7 by any chance? If yes your problem could be caused by the win 7 certificate issues.

**Comment by Kronos6419** [comment] 2018-05-18 08:56
Wherever i set the directory, error occurs at the same download stage, nevertheless I managed to successfully install it Via the Standalone version instead.

**Comment by Kronos6419** [comment] 2018-05-18 08:56
Wherever i set the directory, error occurs at the same download stage, nevertheless I managed to successfully install it Via the Standalone version instead.

**Comment by trrm** [comment] 2018-05-18 08:58
@Al12rs I'm using Win10.

**Comment by Al12rs** [comment] 2018-05-18 08:59
Strange stuff. I will try using the installer myself in a few minutes

**Comment by Al12rs** [comment] 2018-05-18 09:02
No errors on my side

**Comment by Silarn** [comment] 2018-06-28 17:04
LePresidente is working on a new installer that will hopefully fix these issues. I'm going to close this issue for now.

**Closed by Silarn** 2018-06-28 17:04 UTC
Labels: installer
