### ISSUE TITLE
Explorer++ creates empty directories in places it visits

### ISSUE THREAD

**Issue by AnyOldName3** [ModOrganizer2/modorganizer#1229] opened 2020-09-08 22:35 UTC
## The problem:
Every directory I visit in Explorer++ via *Explore Virtual Folder* gains a subdirectory at `Device\MMCSS` in Overwrite.

## To Reproduce:

1. Open MO2.
1. Click *Explore Virtual Folder*.
1. Visit a directory, e.g. `Meshes\f`.
1. Exit Explorer++.
1. Open the Overwrite mod.
1. Observe that there are new directories, e.g. `Device\MMCSS`, `Meshes\Device\MMCSS` and `Meshes\f\Device\MMCSS`.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.3.2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Not tested.
* Desktop OS/version used to run Mod Organizer: Windows 10 18363.1016

## Details:

![image](https://user-images.githubusercontent.com/8485112/92533869-4b5b1f80-f22b-11ea-9cb0-309251c9a586.png)

The files don't show up in Explorer++ if you visit the folder again without restarting it.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
https://gist.github.com/AnyOldName3/6a6f21b9c75ea1eb0baeaf076ff3a188#file-usvfs-2020-09-08_22-32-11-log

I've not looked at this.

### MO Interface:
https://gist.github.com/AnyOldName3/6a6f21b9c75ea1eb0baeaf076ff3a188#file-mo_interface-log

There's nothing fun in this.

**Comment by Al12rs** [comment] 2020-09-08 23:31
We suspected this was caused by an unhandled Delete On Close flag used when creating those folders. Basically we aren't passing it through and closing doesn't delete the files. 
Alternatively this could be a bug with the fake directory registry not cleaning up correctly.

**Comment by AnyOldName3** [comment] 2020-09-08 23:32
I didn't know this was a known issue. I *did* search first, including closed ones too.

**Comment by Al12rs** [comment] 2020-09-09 09:12
I thought we had something already too but I didn't find anything.

**Comment by renfenghuan** [comment] 2020-11-02 02:11
I had this issue too with 2.3.2. 1.35 or the new 1.40 version of Explorer++ are all having this problem.

**Comment by renfenghuan** [comment] 2020-11-02 02:29
Also, I tested it in win7, but it's fine in win7. 

It only happened in win10.

Also, I've run Dism++ to optimize my win10. I don't know if that's relevent.

**Comment by isanae** [comment] 2020-11-02 03:33
Well, I just hooked a debugger to it, and it has nothing to do with the delete on close flag. Something is trying to create a variety of files, such as `\Device\DeviceApi\Dev\Query`, `\Device\MMCSS\MmThread`, `\Device\DeviceApi\CMNotify`, etc. Some of them seem to part of PnP, others from the "Multimedia Class Scheduler Service".

Regardless, these files end up being rerouted. `RerouteW::create()` calls `absolutePath()` on these, which ends up in `winapi::wide::getFullPathName()`. This calls `::GetFullPathNameW()`, which seems to consider these paths as relative and prepend the current drive and cwd to them. So they become something like `C:\game\Data\Somewhere\Device\MMCSS\MmThread`, which ends up being rerouted to overwrite and created as a fake path `C:\Users\user\AppData\Local\ModOrganizer\instance\overwrite\Somewhere\Device\MMCSS`.

I'm not sure about the fix. These paths are weird, they feel like pipes or something. I'd want to just forward them as-is, but I'd need to figure out how to recognize them.

**Comment by renfenghuan** [comment] 2020-11-16 23:53
Also I found out that even if I create a mod from the overwrite folder which contains the created "Device/MMCSS" folder, Explorer++ will still create such folders in overwrite next time.

**Closed** 2020-12-25 04:06 UTC
Labels: bug, issue report, usvfs
