### ISSUE TITLE
Handle directories under Download tab

### ISSUE THREAD

**Issue by unqltango** [ModOrganizer2/modorganizer#1469] opened 2021-03-19 11:19 UTC
**Is your feature request related to a problem? Please describe.**
I have 900+ mods (Skyrim SE) in the download folder, even though I regularly delete older versions. It would be good if I could organize them in folders, for example Downloads\Outfits,  Downloads\Quest mods,  Downloads\Nexus (mods downloaded by nexus API would arrive here), etc.

**Describe the solution you'd like**
I'd just like that the Download tab would be able to handle folders. I'd be happy with just some absolute basic controls, that is I able to enter a folder and I can exit a folder. Folders are on the top of the list. One level depth is enough.

The creating/renaming/deleting of folders, sorting of mods I can do outside of MO2. 

**Describe alternatives you've considered**
I haven't considered alternatives. It would be difficult to allow the user to sort the mods in that small window, so the barebone solutions would be enough.

**Additional context**

**Comment by isanae** [comment] 2021-03-19 11:31
Duplicate of #993.

**Closed by isanae** 2021-03-19 11:31 UTC
Labels: Feature Request, area: Downloads
