### ISSUE TITLE
using all my memory transfering saves

### ISSUE THREAD

**Issue by dsg32** [Modorganizer2/modorganizer#329] opened 2018-04-28 16:19 UTC
# The problem
 
Hi I'm having an issue with the transfer save function, it keeps using all 16GB of my physical memory when I try to copy my saves to and from my profiles, which locks up my system 

# Environment

I'm using Mod Organizer v2.1.2, I haven't tried an older version of Mod Organizer; I'm on windows 10 pro

# Link to Mod Organizer logs

https://gist.github.com/dsg32/d666c4bada7648424e082849a90892b7

## MO Interface link:

https://gist.github.com/dsg32/07b08f0f9af93737a8336b21f2954494

**Comment by Al12rs** [comment] 2018-04-28 16:40
Could you tell me how many GB of actual saves you are trying to move?
And By physical memory do you mean the RAM or Hard Disk?

**Comment by dsg32** [comment] 2018-04-28 16:44
2.35gb for profile 1 Rada and 11.4mb profile 2 Kresren-Dar. I mean ram

**Comment by Al12rs** [comment] 2018-04-28 17:24
hmm, that is certainly strange. I never looked into the transfer code. Since you are just moving 2gb it does not make any sense to use 16 gb so I think we have some kind of leak.

**Comment by dsg32** [comment] 2018-04-28 17:50
thats what I was thinking having heard about such things, but I have no real clue about coding

**Comment by Al12rs** [comment] 2018-04-30 19:30
Ok I can reproduce the high usage, just opening the save transfer dialog ramps up the memory usage and closing does not free. This could just be caching but in that case as well it does not make much sense that just opening the transfer dialog increases of 700Mb+ the memory usage.

**Comment by Silarn** [comment] 2018-05-02 13:40
I'm pretty certain the main issue has been fixed here but please provide confirmation.

**Comment by dsg32** [comment] 2018-05-05 09:32
sorry I've been busy, I'll try this out. Thanks, you work is really appreciated

**Comment by dsg32** [comment] 2018-05-05 09:52
solved Thanks

**Closed** 2018-05-05 09:53 UTC
Labels: bug, fixed in next release, potential fix
