### ISSUE TITLE
Query Info for all downloads missing meta

### ISSUE THREAD

**Issue by Svish** [ModOrganizer2/modorganizer#1180] opened 2020-08-06 02:23 UTC
**Is your feature request related to a problem? Please describe.**
Trying out Mod Organizer 2 after having used Nexus Mod Manager. I restored Skyrim fully to vanilla, but didn't want to re-download all my mods, so I kept the folder with downloaded files and pointed MO2 to that. None of these files have the `.meta` though, and I can't find a way to download this information other than right-clicking each file individually and selecting `Query Info`. 

**Describe the solution you'd like**
When there are files missing `.meta`, there should be a way to download them all in one go. Or at least a way that only requires one button press for me. For example next to the lonely `Refresh` button, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/142162/89483426-550ce580-d79c-11ea-8966-ba6000e3c6ca.png)

**Describe alternatives you've considered**
Haven't found any. I've tried to look for this functionality, but haven't used MO before, so might be missing something too. And this functionality already exists, this issue could be changed to make it more visible.

**Comment by isanae** [comment] 2020-08-06 12:35
Duplicate of #725.

**Closed by isanae** 2020-08-06 12:35 UTC
Labels: Feature Request, duplicate

**Comment by anon2828226** [comment] 2022-08-29 05:52
I just spent 1 hour and 20 minutes right clocking and clicking on query info for over 500 mods from a corrupted hard drive I was reinstalling. what the fuck.

**Comment by Painless68** [comment] 2022-09-10 19:42
I could have sworn this was a feature recently, surprising that it isn't. Same with being able to select multiple files.
