### ISSUE TITLE
MO Cannot download files if you have exactly 254 existing downloads

### ISSUE THREAD

**Issue by Qazerowl** [ModOrganizer2/modorganizer#827] opened 2019-09-05 23:29 UTC
## The problem:
MO2 Fails to start downloads if there are already 254 downloaded files. However, there seems to be no issue if there are already 255+ downloads. If a .zip is manually downloaded and added to the downloads folder, MO will be able to download files again.

MO gives the "you clicked a premium link" error, but then gives the error: "uncaught exception in handler (object qt_scrollarea_viewport, eventtype 4): state: invalid download index 254"

## To Reproduce:

1. Have a combined total of exactly 254 .zip+.7z+.rar files in the downloads directory.
2. Click "Mod Manager Download" on any file on the nexus website

## Environment:

MO: 2.2.1
OS: Windows 10 (latest)

**Comment by Al12rs** [comment] 2019-09-21 11:33
I cannot reproduce the issue. what I believe happened was that a download got corrupted with that index and that is what is making Mo2 trip up for you.

**Comment by ewillett804** [comment] 2019-10-21 18:40
If this is still occurring please provide a detailed gist with version #'s of all components, and a test-case that can be reproduced.  We should be able to close this within 20 days if no new information.

**Closed** 2019-12-02 19:22 UTC
Labels: issue report
