### ISSUE TITLE
MO2 Skyrim SE not loading moreHUD's .mhud file

### ISSUE THREAD

**Issue by elgin4** [Modorganizer2/modorganizer#323] opened 2018-04-20 05:32 UTC
the mod works if installed and loaded manually without MO2, but i can't figure a way for skyrim to see the file if starting the game through MO2

**Comment by Al12rs** [comment] 2018-04-20 05:37
You need to provide us some more information or we can't really tell what is going on. Specifically your Mo logs that are either in Appdata/local/modorganizer/instanceName or in your Mo2 install directory if you are using portable.

**Comment by SuperSandro2000** [comment] 2018-04-20 08:11
@elgin4 the game shouldn't know that it was started trough mo

**Comment by elgin4** [comment] 2018-04-20 08:36
i can't upload my log file because it's 1.3 GB. i'll delete it, load the game once, and upload it soon.

ideally yes, the game should just think MO doesn't exist, but a few versions of MO ago, .dll files had to be loaded in the actual skyrim data folder for its corresponding mod to work. obviously i tried this with moreHUD, but no dice. also, other users have reported this issue with the mod author, so it's not just me.

**Comment by elgin4** [comment] 2018-04-20 20:16
[usvfs-2018-04-20_20-08-46.log](https://github.com/Modorganizer2/modorganizer/files/1933539/usvfs-2018-04-20_20-08-46.log)

**Comment by Astakos71** [comment] 2018-04-30 20:57
I am having the same issue as well.
moreHUD is partially working when through MO2 (i.e. descriptions of shrines do not work), but it is working perfectly when loading a game manually.
It seems that MO2 cannot "read" the .mhud file that is included in the mod and it seems to be the reason that mod's generated log file is empty when in skse.log the dll shows as been successfully registered.

**Comment by elgin4** [comment] 2018-05-01 14:34
same as EmadJo for me too. it used to work with the last version, but doesn't anymore

**Comment by Astakos71** [comment] 2018-05-01 16:11
Same here. Latest build 2.1.3 Dev 7 and the latest one uploaded to Nexus (2.1.2) suffer this bug.
I know it was working correctly some dev versions before the one at Nexus but unfortunately I cannot remember which one since I only noticed this bug quite recently.

**Comment by elgin4** [comment] 2018-05-01 18:56
MO2 v2.1.3 Dev Build 7 does not load the .mhud file for me

**Comment by Silarn** [comment] 2018-05-01 19:05
This could be related to the issue that Roy reported with the geck plugin. I'll get around to running a procmon with this soon and hopefully that will give me somewhere to look because I was having a hard time tracking down the other one.

**Comment by ahzaab** [comment] 2018-05-12 16:33
Al12rs,  Thanks for helping me this morning!

**Comment by Astakos71** [comment] 2018-05-12 16:35
I can confirm that this issue is completely resolved with latest Nexus version 2.1.3 of MO2 and moreHUD 3.4.8.
Thank you guys! :)

**Comment by Silarn** [comment] 2018-05-12 19:17
So, while this issue was patched in the moreHUD dll, there is a USVFS update now which resolves the core issue. I'm going to close the ticket since it's now fixed in either case.

**Closed by Silarn** 2018-05-12 19:17 UTC
Labels: bug, needs investigation, usvfs
