### ISSUE TITLE
MO2 Crashes with mobile drives

### ISSUE THREAD

**Issue by Delgathar** [ModOrganizer2/modorganizer#1155] opened 2020-07-15 04:38 UTC
## The problem:
MO2 Crashes when attempting to load a portable drive that is not present.
I have my mod archive directory set to a portable drive F.  If I unload MO2 and restart with the drive still unattached, MO2 gives two error popups then crashes.  While the popup is misleading, MO2 shouldn't crash. 

## To Reproduce:

1. Go to Tools/Settings/Paths/Downloads.  Set to a directory on a portable drive.
2. Close MO2.
3. Remove portable drive.
4. Restart MO2.

## Environment:
All Versions of MO.
All Versions of Windows.

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

If I remove the drive AFTER MO2 is loaded there is no problem.  The downloads window turns blank and everything works fine until I reload MO2.  If I need to reattach the drive with MO running, there is also no problem.  I only have to refresh the download window.  This is the behavior I would expect on MO2 load as well.
These are the two errors I get.  
![first error](https://user-images.githubusercontent.com/9401098/87502107-bd99f400-c62e-11ea-857f-9b6fc3571853.jpg)
![second error](https://user-images.githubusercontent.com/9401098/87502111-bffc4e00-c62e-11ea-8957-c9d8e4566f13.jpg)
All the logs are either clean or very short when recreating the crash.

## Link to Mod Organizer logs:
Log is clean because MO fails to load.

### USVFS:
https://gist.github.com/Delgathar/b9cd88702b0fb9a1b26b3e644b625af5

### MO Interface:
https://gist.github.com/Delgathar/53090f3bdeb9d6339bb46dd96e275665

**Comment by isanae** [comment] 2020-07-23 21:19
1) Does MO actually crash or does it just close after these messages?
2) MO doesn't handle very well the case of data or game folders not being accessible on startup. You also can't expect MO to work correctly when your stuff is on a drive that's not plugged in.
3) Your logs are short because you haven't set the level to debug in the settings.

I'm closing this as semi-expected behaviour. It's more of a UI issue.

**Closed by isanae** 2020-07-23 21:19 UTC
Labels: issue report
