### ISSUE TITLE
Allow multiple instances without use of Appdata

### ISSUE THREAD

**Issue by WalrusInAnus** [ModOrganizer2/modorganizer#834] opened 2019-09-16 08:20 UTC
I hate to use %AppData% for programs I have as portables.
There doesn't seem to be a way to force MO NOT to use the system folders for profiles or instances or whatever (I don't really understand the new MO). The "base directory" setting is only half solution, with logs and ModOrganizer.ini still being saved there.

**Comment by LostDragonist** [comment] 2019-09-16 08:24
Are you aware of the portable mode of MO2?  It's at the bottom of the instance selection screen.  It makes MO store all your data in the MO folder.

I think it'd still be nice to have a way to completely customize where MO stores instances but I have no idea what a good solution would be.

**Comment by WalrusInAnus** [comment] 2019-09-16 08:27
Ah, I guess that works fine for a single game. That mostly solves my problem, but as a side effect, the folders that would normally reside in instance folder are lost in MO's own folders.
Like you said, full customization...

**Comment by Al12rs** [comment] 2019-09-16 08:36
The problem is that you need to have a place where Mo2 can store where all the stuff is, and if that place is not a fixed place how can MO2 know where to look for it? So if you wan to use multiple games with one installation you will have to accept that a couple of files stay in appdata (I know, the end of the world). As an alternative can install a portable install of Mo2 for each game, like you would have done with MO1.

**Comment by LostDragonist** [comment] 2019-09-16 08:52
I've also been considering options like putting something in the registry or the MO install folder.  Putting stuff in the registry (or AppData) kind of the defeats the purpose of having a portable application.  Putting something in the MO install folder feels wrong for a non-portable application.

One option, that would be fairly high effort to implement, would be to change portable mode to be able to store multiple instances in the MO folder.  Then I guess the non-portable mode could use the registry.  Though I honestly don't think it'd be worth the effort.

**Comment by KerberX** [comment] 2019-09-16 08:56
For Kortex I have special command line parameter that makes the program to read global config files from provided directory. You can use that method. It doesn't really makes sense for Kortex because its VFS can not be made portable but for MO this would work just fine.

**Comment by WalrusInAnus** [comment] 2019-09-16 09:36
My main problems with both current options:
**non portable:**
If you don't want to have mods (or can't due to disk space) in AppData and change the path, the ini files and some other minor stuff will still be saved there, which is potentially problematic in the case of disk failure or when you want to do a backup. You just don't aways remember to backup from two different locations.
**portable:**
Stuff is saved directly into MO folder. That's a mess. At least have it put under a subfolder.
Actually, in portable mode, would something similar to Firefox way works?
Profiles.ini and next to it profiles folder.
In the ini you could maybe even specify full path.
That way you could have local variant of instances or something.

**Comment by Al12rs** [comment] 2019-09-16 09:45
If you move the base directory the only things that stay in Appdata are the modorganizer.ini file containing the location of the base directory, the logs and crash dumps and maybe some cache files.
Everything concerning the modsetup except the modorganizer.ini is in the base directory.
If Appdata gets deleted Mo2 will be able to pick up the base directory you had if you point it to it in the settings.

**Comment by Al12rs** [comment] 2019-09-16 09:47
For portable mode we can't change it simply because we would break all current intallations

**Comment by WalrusInAnus** [comment] 2019-09-16 09:53
I think modorganizer.ini is important with all the program settings. 

> For portable mode we can't change it simply because we would break all current intallations
Didn't think about that. That's true...

**Comment by Al12rs** [comment] 2019-09-21 10:41
To be honest I don't believe this has enough reason to be implemented in any way. There are already two ways of handling things and neither are as inconvenient to warrant the development effort.

**Comment by DaemonPhenex** [comment] 2019-10-22 13:05
Sorry, I'm not well versed in the code but I can understand, retooling might be quite the headache.

I keep my files in a sub-directory name "Instances":

> G:\\GameFiles\\ModOrganizer\instances\\%**GAME**%\

This way it's much cleaner then dropping all the folders in the first directory layer and allows for separate game instances but keep it somewhat portable.

And as you know, if I make a new basic instances it points to:

> %LOCALAPPDATA%\\ModOrganizer\\%**GAME**%

In this configuration, I'm then allowed to have multiple instances. yay 
Though, for my directory locations I must manually change the base directory to the **(G:\\)** drive from within MO for each game, I haven't tried but was going to change it to.

> .\\Instances\\%**GAME**%

Unfortunately, if the **APPDATA** folder gets deleted, MO kinda just shits the bed and forgets where everything is. the second best option seems like a symbolic link and I feel as if that's not ideal.

---
Either way. sorry to complain, +1 on the request.
Thanks for your time and I hope it see's some improvement in future development. ❤️

**Comment by Silarn** [comment] 2019-10-22 18:57
The thing we seem to be missing is there has to be a default location where MO saves this information. If we were to change this to My Documents, then people would complain if their Documents data got deleted. If it's in the registry, people will complain if they reinstall Windows and the registry is gone. That global config info has to go to some predictable unique location for every user with the application having no initial knowledge of where the file is.

Now, it might be better if that global file basically just contained the info necessary to define and locate the profile data and all other settings could be placed relative to the active profile. I don't have a problem with that implementation, except for the fact that we would need a migration process for the data that's already set in the global config file.

There are two things that I think should be done, because they're problematic right now particularly if reconfiguring MO after losing that global ini.

1) Make changing the active directories painless. Right now it automatically regenerates core settings files, overwriting what might already be in those directories. This can nuke profiles and mod order, so changing the directories needs to only create these files if they don't exist.
2) Provide the option to set the starting instance directories when creating the instance.

**Comment by Al12rs** [comment] 2020-06-09 14:58
Proposed solutions tracked here: #254 #561 
Closing since original suggestion was rejected

**Closed by Al12rs** 2020-06-09 14:58 UTC
Labels: Feature Request

**Comment by pritster5** [comment] 2023-02-07 23:54
Can someone explain to me why `%Appdata%` _has_ to be the folder to use when using a global instance? Why cant the file structure be as simple as `D:/MO2` is the program install, with the global instances being stored in `D:/GameMods/Skyrim` and `D:/GameMods/TheWitcher3` ? 

Is this to avoid installing MO2 for all users of a PC? Given that most (or at the very least, many) PC gamers just have one user (themselves, the admin), I wish you could just install MO2 as an admin and enable cases like the filepathing mentioned above.

**Comment by Al12rs** [comment] 2023-02-08 01:03
We explained this already above. Appdata is the standard location where programs can save global data. It's what the windows guidelines indicate to use. The comments we made already explained the reasosn why this is the current situation. 
You can still change the location of most of the files to wherever you want.

**Comment by pritster5** [comment] 2023-02-08 01:24
"It's what the windows guidelines indicate to use"

I understand, but would allowing users to violate this guideline break current installs of MO2? Is it even possible to add this as an option?

**Comment by Al12rs** [comment] 2023-02-08 10:32
As Silarn explained above, MO2 needs to know where to find the global instances somehow. So the solution that was implemented by Tannin was to put the instances in appdata so that any MO2 install could find them.

If you want to use another, this time custom, location, you still need a central place where you record the path to the new location, such as the windows registry. Using the windows registry kind of defeats the purpose of being portable and not storing things on C drive.

Basically you can't have global instances without some kind of central location such as appdata or the registry.

If you don't care about the instance being discoverable globally, and only want the instance to be linked to a specific installation of MO2, then that could maybe be done the way Kerber suggested, by overwriting the normal behavior through a command line option. Though it would still be akward to use for normal users. The way portable currently works can't be changed as it would break installs for all the current portable users and we can't do that.
