### ISSUE TITLE
Network access is disabled (2.3)

### ISSUE THREAD

**Issue by jejunejm** [ModOrganizer2/modorganizer#1173] opened 2020-07-29 06:41 UTC
## The problem:
Upon launch startup or re-authorization, MO2 fails the network handshake.

## Details:
My desktop environment has a lot of services disabled by default, though this wasn't an issue prior to upgrading to the latest release.

## Environment:

* Mod Organizer Version that exhibits the issue: Latest release, 2.3.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.2.0
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro, build 1909

### USVFS:
https://gist.github.com/jejunejm/236ec550ecc04c24afec4289b9230ece

### MO Interface:
https://gist.github.com/jejunejm/7a62e234947351814cdc953aebd6d346

**Comment by isanae** [comment] 2020-07-29 09:10
Do you have a VPN active?

**Comment by jejunejm** [comment] 2020-07-29 10:05
No VPN, but I do use a DNS Resolver (NextDNS) which I disabled the service to when troubleshooting. No issues before upgrading, though.

**Comment by isanae** [comment] 2020-07-29 10:08
It seems to be a bug in the Qt library we're using, introduced in 5.14, which we shipped with 2.3.0. We had 5.13 with 2.2.2. Some users are reporting that switching servers or turning the VPN off or on while MO is running fixes it temporarily, until MO is restarted.

**Comment by jejunejm** [comment] 2020-07-29 12:14
Okay thanks, guess I'll downgrade until there's a fix.

Tried both switching servers as well as disabling/enabling the DNS Resolver while MO2 was open and restarting--no dice.

If it's any correlation,I can't even manually put in my API key for Nexus as it just returns 'validator attempt: code 0' ; network access is disabled' leading to the "You must authorize MO2 in settings" when downloading from Nexus as well as when logging in. 

The browser redirect is fine though. It says it's has been authorized so something is blocking the network request on MO2s' end and network-wise, I haven't changed anything on my end since upgrading.

**Comment by Al12rs** [comment] 2020-07-29 12:24
Just a warning, the issue isn't likely to get fixed soon. We do releases every 4-8 months and from what I understand the resolution entirely depends on Qt fixing it in the meantime and us upgrading to a new version of qt.

**Comment by jejunejm** [comment] 2020-07-29 12:30
Well the issue clearly isn't solely QT, otherwise _no one who is using the latest release_ would be able to log in; I'm totally willing to modify my setup minorly to accomodate the issue, so long as something can be pinpointed as the culprit.

Completely disabling any DNS resolvers, services, and Win-TAP network adapters doesn't change anything so I believe that can be ruled out.

**Comment by isanae** [comment] 2020-07-29 12:34
We have no idea what the issue is. You're the third person to report it: the first two had VPNs, you have a DNS resolver. So it clearly has something to do with network configuration, but we don't know what it is.

**Comment by isanae** [comment] 2020-07-29 12:45
@jejunejm Do you have a static IP? If so, does switching to DHCP fix it?

**Comment by jejunejm** [comment] 2020-07-29 13:55
No static, using DHCP.

**Comment by jejunejm** [comment] 2020-07-29 14:24
Wanted to mention I'm also recieving this log message after idling for a bit in MO: [2020-07-29 14:22:43.106 D] command line: '"D:\Modding Tools\MO2\ModOrganizer.exe" '

[2020-07-29 14:22:45.148 E] [github.cpp:176] Github: request for https://api.github.com/repos/Modorganizer2/modorganizer/releases failed, Network access is disabled. (QNetworkReply::UnknownNetworkError)

**Comment by isanae** [comment] 2020-07-30 01:08
> is there some OS-level dependency that QT library 5.14.2 now requires because as-of yesterday 2.2.2 was working totally fine with this exact network setup

No, it's clearly a regression. It's a bug that was introduced around 5.6, got fixed in 5.9 and got unfixed in 5.14. I don't know what the bug is, what causes it or if there's a workaround.

**Comment by isanae** [comment] 2020-07-31 16:48
@jejunejm Can you try this? It's a tentative for the network problems, but I'm not sure if it works.

[2.3.0-p1.zip](https://github.com/ModOrganizer2/modorganizer/files/5008076/2.3.0-p1.zip)

**Comment by jejunejm** [comment] 2020-07-31 19:37
So, it logged me in now after a restart of MO2 but the log is updating every second with the error "Failed to subscribe to network connectivity events: "The service cannot be started, either because it is disabled or because it has no enabled devices associated with it."

**Comment by isanae** [comment] 2020-08-01 15:06
2.3.1 won't have a fix for this. The problem looks to be deep within Qt and trying to forcibly change the network accessibility status just breaks something else. The only solution for now is to revert back to 2.2.2.1.

**Comment by jejunejm** [comment] 2020-08-01 16:02
Fair enough, thanks for the workaround, regardless. Potentially foolish question but should I expect any neglible performance impact from the connectivity calls if MO is locked while playing?

**Comment by isanae** [comment] 2020-08-01 16:10
I don't know what Qt is trying to do in the background, so I can't tell. I'd expect it to be negligible.

**Comment by isanae** [comment] 2020-08-03 14:48
@jejunejm Can you check if the Windows Event Viewer is working?

**Comment by jejunejm** [comment] 2020-08-04 05:41
It's working, and I don't see any related events to MO after launching.

**Comment by isanae** [comment] 2020-08-05 20:21
@jejunejm Can you try this version? It's built against Qt 5.15. I've had reports that it fixes the network problems.

https://mega.nz/file/XId1FAqb#G4jNUcRbg1OKVoEFrb3qwXF5LB1t4EZZMCFR6bdbDU8

**Comment by jejunejm** [comment] 2020-08-06 06:35
Sorry, dealing with a power outage from the recent storm here in US--I'll
give it a go as soon as I can.

**Comment by isanae** [comment] 2020-08-08 02:47
@jejunejm Courtesy ping, as I'd really like to get to the bottom of this before I release 2.3.2.

**Comment by jejunejm** [comment] 2020-08-10 06:12
@isanae whatever was changed in this new build I cannot log in to nexus anymore.

**Comment by isanae** [comment] 2020-08-13 20:42
2.3.2 won't have a fix for this either. I was hoping Qt 5.15 would work, but it doesn't look like it, so I'm out of ideas.

**Comment by jejunejm** [comment] 2020-08-14 07:17
@isanae i appreciate all the effort to diagnose this issue for edge-case users like myself but '2.3.0-p1' works fine for me and I haven't noticed any performance problems with the log spam so for the time being I guess you can table the issue. 

Just to clarify in case there was a miscommunication; the original fix you uploaded fixed the problem for me but with continued log errors--the newest build you uploaded completely broke everything again for me--the only difference being I noticed a log-in prompt on launch compared to the public release. Same errors being spit out.

**Comment by NovusA1** [comment] 2020-09-19 12:38
I can verify that on v2.3.2, my NordVPN causes this bug. If I turn off the VPN, bug vanishes.

Strange, it wasn't doing this 6+ months ago.

**Comment by CloggedOuthouse** [comment] 2020-12-09 11:33
I this problem as well with my VPN (Private Internet Access).

**Comment by Hello71** [comment] 2021-01-13 16:44
https://bugreports.qt.io/browse/QTBUG-84907, try qt 5.15.1

**Comment by Al12rs** [comment] 2021-01-13 17:49
We are on qt5.15.2 with the dev builds. If anyone with the issue could verify if it's fixed they can find the dev builds on the discord server.

**Comment by CloggedOuthouse** [comment] 2021-01-14 00:46
I tested it on 2.4.0alpha5b and it seems to be fixed for my VPN problem.

**Comment by Al12rs** [comment] 2021-01-14 00:49
Thanks for testing and reporting!

**Comment by isanae** [comment] 2021-02-21 19:43
Fixed in 2.4.

**Closed by isanae** 2021-02-21 19:43 UTC
Labels: bug, fixed in next release, qt
