### ISSUE TITLE
Stardew Valley categories don't make sense and use Skyrim names.

### ISSUE THREAD

**Issue by dragon3025** [ModOrganizer2/modorganizer#1467] opened 2021-03-16 23:08 UTC
## The problem:
Stardew Valley categories don't make sense and use Skyrim names.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.0
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
Some of the categories use names that would fit for Skyrim like "Armour", "Companions", and "Factions". They don't match either, for example "Automation" is automatically assigned to Shader Preset, but that's a Gameplay Mechanic mod.

**Comment by isanae** [comment] 2021-03-17 00:20
This is to be expected for now, support for non-Bethesda games is preliminary and parts of MO don't make sense with other games. I'm closing this as a duplicate of #327, it's a meta issue for stuff like that. We've also been working on a general overhaul for categories, but I'm not sure what's going with that right now.

**Closed by isanae** 2021-03-17 00:20 UTC
Labels: issue report
