### ISSUE TITLE
Missing Python interfaces for plugins

### ISSUE THREAD

**Issue by mdavis199** [ModOrganizer2/modorganizer#1219] opened 2020-08-26 23:44 UTC
## Problem: Public python interface is missing functionality

I've written an MO2 plugin in python.  The first phase, which is almost complete, automates the plugin/mod selections for profiles created for the purpose of generating a merge. Given a list of plugins to include in a merge, it will automatically enable the plugins and all their required masters, move the plugins in proper priority, and disable unneeded mods. The next phase will include an option that will edit/create zMerge configuration based on the MO2 profile.

However, I think MO2 is missing a couple IPlugin interface methods needed for the python plugin. 
#### 1. Missing Callbacks
Whenever a call is made to: 
    ```organizer.pluginList().onPluginStateChanged(self.onPluginStateChanged)```
or
```organizer.pluginList().onPluginMoved(self.onPluginMoved) ```
MO2 throws an exception like below:
```
AttributeError: 'IPluginList' object has no attribute 'onPluginStateChanged'
```
#### 2. IPluginList missing method to set priority
I need to move the plugins selected for the merge to the bottom of the priority list.  But `IPluginList` does not have a `sendToPriority` method.  It has a method to change the load order, but not the priority. 

#### 3. IModList missing method to setActive a list of mods
Is there a method I can call that will deactivate mods in bulk?  `IModList` has `setActive` for a single mod, but deactivating a mod one-at-a-time is very, very slow because it has to refresh after each call. Is there a method where I can pass a list of Mods to disable?

## Screenshots
<details>
<summary> Here are screenshots of the plugin.  The second page will give you a better idea of why I need these changes.</summary>

![plugin_page1](https://user-images.githubusercontent.com/546489/91366465-4e99e880-e7f3-11ea-8aea-9f6d526315bb.jpg)
![plugin_page2](https://user-images.githubusercontent.com/546489/91367400-cd902080-e7f5-11ea-9e7d-66322d7e887d.jpg)

</details>

**Comment by AnyOldName3** [comment] 2020-08-27 00:15
1. I can see the implementation for `IPluginList::onPluginMoved`, so I'm not sure what issue you're having it precisely with that. `IPluginList::onPluginStateChanged` seems to be missing, though.

1. A `sendToPriority` method is less obvious than a `setLoadOrder` method. If you send a plugin to a specific priority, it's not clear what it's going to do with all the other plugins affected by that change. It's easy enough to manipulate a list to do exactly what you want.

1. There might be several parts of MO2 that expect only  one mod to be activated/deactivated at a time, so it could be difficult to add a method to do multiple in a batch. There are a few cases where things like this have caused MO2 to be slow even without plugins, and some of them have been fixed, so it *might* be safe to add such a method now, but I'm not the person who's been involved with that kind of thing.

**Comment by mdavis199** [comment] 2020-08-27 00:55
Thank you for the detailed response! Much appreciated. I'll just note here functions I think the missing interfaces could match with: 
1. Regarding `sendToPriority`, I was hoping it could be a public interface similar to this function: 
https://github.com/ModOrganizer2/modorganizer/blob/f0e94c26aebae6f86a59ed974e433f96e77faec7/src/pluginlist.cpp#L391
or this one
https://github.com/ModOrganizer2/modorganizer/blob/f0e94c26aebae6f86a59ed974e433f96e77faec7/src/pluginlist.cpp#L1413

2. Currently for a single mod, the call to `setActive` calls into this function: https://github.com/ModOrganizer2/modorganizer/blob/f0e94c26aebae6f86a59ed974e433f96e77faec7/src/profile.cpp#L551
For multiple mods, I'm hoping an interface could be added for a function similar to this one: https://github.com/ModOrganizer2/modorganizer/blob/f0e94c26aebae6f86a59ed974e433f96e77faec7/src/profile.cpp#L570

**Comment by Holt59** [comment] 2020-08-27 07:20
1. As @AnyOldName3 said, the binding for `onPluginStateChanged` are missing and should be added. If `onPluginMoved` does not work, you probably got a different error message that would be more useful to understand the issue.

2. For `sendToPriority`, I think it's mostly a convenience function, but since there is already a very similar function in the actual `PluginList` implementation, why not expose it.

3. Looking at the piece of codes you provide, I don't see any reason not to add a function to enable/disable multiple mods at once.

**Comment by Holt59** [comment] 2020-08-27 16:33
The converter for the callback type was missing for `onPluginMoved` which is probably why it did not work. This should be fixed, together with the missing `onPluginStateChanged` in https://github.com/ModOrganizer2/modorganizer-plugin_python/pull/57

**Comment by Al12rs** [comment] 2020-09-01 12:14
@mdavis199 Holt addressed all the things that you mentioned and we have merged the PRs. I created a Dev build (2.4.0alpha1) with these and some more changes so that you can test it and continue development of your plugin. 
It's available on our development discord, under the #dev-builds channel: https://discord.gg/6GKR9jZ .

Please let us know if everything works.
Also feel free to discuss directly with us on discord for anything regarding your plugin's development.

**Comment by mdavis199** [comment] 2020-09-01 12:49
Terrific! So much quicker than I could have imagined.  I don't have access to discord because I do not have a cell phone (with an active data plan) that I can verify the account with.   But I can build MO2 from source with little trouble. It'll probably be tomorrow or Thursday.  I'll let you know. Thanks.

**Comment by Al12rs** [comment] 2020-09-01 13:59
Access to the Mo2 discord shouldn't require phone validated discord accounts, don't know if that is a new requirement for all accounts. It should just require a validated email.

**Comment by mdavis199** [comment] 2020-09-01 14:42
I emailed discord's technical support in July. Although he was very nice, he said the "system's detection system was triggered" and needed phone verification requirement.   He said it could have been from using a VPN or proxy that may have been shared with bad actors.  Again, he was quite nice and seemed regretful that he couldn't help out.

**Comment by Al12rs** [comment] 2020-09-01 15:13
If you are already building from source without issues awesome. That is usually a pretty hard step. If umbrella gives you issues you can try using our new alternative mob instead: https://github.com/isanae/mob

**Comment by Al12rs** [comment] 2020-09-01 15:15
In any case if you can get discord working I'm sure it will make interacting with us much faster. You will be able to see what we are up to and we can try to help for any issues.

**Comment by mdavis199** [comment] 2020-09-03 01:36
@Al12rs Thanks for the info about the alternative mob. It looks great and I look forward to trying it out soon.  For today, I built MO from "umbrella" since I've already worked out the little quirks it has with my system.   I had to install the new Qt version and build MO, so I haven't been able to exercise the changes much, but here are my notes.

### Disabling Mods in Bulk ###
_The good_:  Fantastic speed! Infinitely faster.  Thank you. Without this, I would have had to throw out the entire plugin.

_The bad_: Every time I disable a mod, MO logs an error similar to: `"Plugin not found: Map Markers complete.esp"`. After one run of the plugin, I could have over 600 such lines in MO's log.  I'm pretty sure my code is not querying MO about the plugin after its mod is disable, because it relies on cached data.

### Setting Priority ###
Much better than using `setLoadOrder`.  I think `setLoadOrder` was letting me move a game's plugins that shouldn't be moved. The new method, I think prevents that.

### Callbacks ###
It might be operator error, but I'm not getting callbacks from `organizer.pluginList().onPluginMoved` or `organizer.pluginList().onPluginStateChanged`. I can now connect the signals without an error, but they just don't seem to be sending anything.   I do get info from `organizer.pluginList().onRefreshed` and from the new `organizer.modList().onModStateChanged`

If you need any more details, let me know.   Thanks so much.

**Comment by Holt59** [comment] 2020-09-03 07:25
> I think setLoadOrder was letting me move a game's plugins that shouldn't be moved. The new method, I think prevents that.

I don't know about `setLoadOrder` but the new method should ensure that the load order is "valid" (from a MO2 point-of-view), i.e. that all master-flagged files are at the beginning of the load order for instance.

> ### Callbacks
> 
> It might be operator error, but I'm not getting callbacks from `organizer.pluginList().onPluginMoved` or `organizer.pluginList().onPluginStateChanged`. I can now connect the signals without an error, but they just don't seem to be sending anything. I do get info from `organizer.pluginList().onRefreshed` and from the new `organizer.modList().onModStateChanged`

Could you show us the code you use for `onPluginMoved()` and `onPluginStateChanged()`?

**Comment by mdavis199** [comment] 2020-09-03 12:41
Here are the initialization of the signal connections:
```
 def __init__(self, organizer: IOrganizer, parent: QObject = None):
        super().__init__(parent)
        self._organizer = organizer
        self._isLoading = False

        organizer.pluginList().onRefreshed(self.onRefreshed)
        organizer.pluginList().onPluginMoved(self.onPluginMoved)
        organizer.pluginList().onPluginStateChanged(self.onPluginStateChanged)
        organizer.modList().onModStateChanged(self.onModStateChanged)
```
Here are the slots. Presently they do nothing but log. For `onPluginStateChanged`, I tried all three pyqtSlot variations
```
    @pyqtSlot()
    def onRefreshed(self):
        self.log.emit("ModOrganizer refreshed the plugin list", LogStatus.Info)

    @pyqtSlot(str, int, int)
    def onPluginMoved(self, name, old, new):
        qInfo("onPluginMoved")
        self.log.emit("Plugin {}: load order moved from {} to {}".format(name, old, new), LogStatus.Info)

    # @pyqtSignal(str, int)
    # @pyqtSlot(str, object)
    @pyqtSlot(str, "PyQt_PyObject")
    def onPluginStateChanged(self, name, state):
        qInfo("onPluginStateChanged")
        self.log.emit("Plugin {}: changed to {}".format(name, state), LogStatus.Info)

    @pyqtSlot(str, object)
    def onModStateChanged(self, name, state):
        ModStateActive = 2
        # active = (state & ModState.Active) == ModState.Active
        active = (state & ModStateActive) == ModStateActive
        activeName = "Active" if active else "Inactive"
        self.log.emit("Mod: {} changed to {} (state: {})".format(name, activeName, state), LogStatus.Info)

**Comment by Holt59** [comment] 2020-09-03 12:44
Thanks, I'll look into it when I have time. For your information, `onModStateChanged(self, name, state)` has been deprecated (you are probably getting a warning for it) in favor of `onModStateChanged(self, mods)` (where `mods` is a dictionary from mod name to state).

**Comment by AnyOldName3** [comment] 2020-09-03 13:15
Why are you making them into signals and slots? They're regular callbacks. It's not impossible that the pyqt decorators are confusing things.

**Comment by mdavis199** [comment] 2020-09-03 14:35
Likely, it was a hold over from just trying to get it to work. I removed the pyqtSlot decorations shown in the code above.   No change in the output.  Still not getting any qInfo() lines from `onPluginStateChanged` or `onPluginMoved`

**Comment by Holt59** [comment] 2020-09-03 14:36
> 
> 
> Likely, it was a hold over from just trying to get it to work. I removed the pyqtSlot decorations shown in the code above. No change in the output. Still not getting any qInfo() lines from `onPluginStateChanged` or `onPluginMoved`

Do you get the log from `self.log`? I'm not sure `qInfo()` works properly in python. You can do a simple `print` and it should go to the MO2 logs.

**Comment by mdavis199** [comment] 2020-09-03 14:43
I made the following change.  No log entries in the two callbacks in MO log or in my log widget.
<details><summary>Revised code</summary><p>

```
    def onRefreshed(self):
        print("OnRefreshed")
        self.log.emit("ModOrganizer refreshed the plugin list", LogStatus.Info)

    def onPluginMoved(self, name, old, new):
        print("OnPluginMoved")
        self.log.emit("Plugin {}: load order moved from {} to {}".format(name, old, new), LogStatus.Info)

    def onPluginStateChanged(self, name, state):
        print("onPluginStateChanged")
        self.log.emit("Plugin {}: changed to {}".format(name, state), LogStatus.Info)

    def onModStateChanged(self, stateDict):
        print("onModStateChanged")
        # active = (state & ModState.Active) == ModState.Active
        ModStateActive = 2
        for name in stateDict:
            active = (stateDict[name] & ModStateActive) == ModStateActive
            self.log.emit(
                "Mod: {} changed (active? {}, state: {})".format(name, active, stateDict[name]), LogStatus.Info
            )
```
</p></details>

**Comment by AnyOldName3** [comment] 2020-09-03 16:18
`qDebug` and `qCritical` both work from Python if they're imported, so I'd expect `qInfo` to work, too.

**Comment by Holt59** [comment] 2020-09-03 17:00
So there are a few issues in MO2 code base regarding `onPluginStateChanged` and `onPluginMoved`:

- `onPluginMoved` is not called when plugins are moved due to a plugin being enabled / disabled.
- `onPluginStateChanged` is only called when you check / uncheck a plugin manually, not when you enable/disable all/selected, or when you call `setState`.

**Comment by mdavis199** [comment] 2020-09-03 17:08
And it doesn't look like `onPluginMoved` is called with the new `IPluginList::setPriority` is called, which is what I'm doing.

**Comment by Holt59** [comment] 2020-09-03 17:13
> 
> 
> And it doesn't look like `onPluginMoved` is called with the new `IPluginList::setPriority` is called, which is what I'm doing.

`onPluginMoved` is definitively called with the new `setPriority`. Maybe you have an issue somewhere else in your code? Did you try setting log to debug?

**Comment by mdavis199** [comment] 2020-09-03 17:20
Sorry, yes. you are correct.  That part is working fine. Thanks.

**Comment by Holt59** [comment] 2020-09-27 13:05
The behavior of `onPluginStateChanged` has been fixed. I am not sure we want to fix `onPluginMoved` for activation / deactivation since what matters most is the relative order of plugins, which does not change when a plugin is activated / deactivated, and you can use `onPluginStateChanged` anyway.

This will go into the next alpha build (2.4.0a2) but is already available if you build from source. Feel free to open new issues if you find specific bug / unexpected behavior in the callbacks.

**Closed** 2020-09-27 17:00 UTC
Labels: Feature Request, area: mo2 plugin interface, area: python proxy
