### ISSUE TITLE
Hardllink mode instead of symlink option, some mods won't work properly otherwise.

### ISSUE THREAD

**Issue by njalooo** [ModOrganizer2/modorganizer#1719] opened 2022-07-03 08:00 UTC
I'm trying to mod Cyberpunk 2077, and for some mods (f.e. simple menu, metro system) it seems like they only work properly when dropped directly into the game files. A mod i unfourtunately couldn't find again, actually has a notice in the description on nexusmods, that one should activate hardlink mode for vortex.

Unfourtunately Mod Organizer 2 currently only seems to support a symlink mode. It would be really great if someone could implement a hardlink mode too.
Or just find another solution that makes the part of Cyberpunk that is unable to access symlinks work.

**Comment by LePresidente** [comment] 2022-07-03 08:49
Try this

https://www.nexusmods.com/skyrimspecialedition/mods/31720/

**Comment by Qudix** [comment] 2022-07-03 09:32
There is no such thing as a hardlink/symlink mode in MO2.

**Comment by AnyOldName3** [comment] 2022-07-03 14:14
MO2's virtual filesystem really is virtual. Unlike Vortex, which still writes symlinks or hardlinks to the real filesystem, MO2 replaces parts of the Windows file API at runtime with its own functions that behave as if the files were really there. This has the advantage that it keeps the game's directory completely clean, but certain files get loaded before the function hooks are set up, and so have to really be there. For the few cases where it's genuinely necessary, there's the root builder plugin linked above, which can copy or link specific files for real so they're accessible as soon as the process is launched.

**Comment by njalooo** [comment] 2022-07-03 19:13
@LePresidente Doesn't seem to work, files not appearing in game folder after manual build, thanks for the suggestion though.

**Comment by 63OR63** [comment] 2022-10-22 18:40
@njalooo @LePresidente I'm in the same boat, but for me Root Builder kinda worked. The problem is that some mods create files in the `overwrite` folder during work, and Root Builder can't help with that, these files aren't seen by the game until you close it and manually move these files to `root` folder (as Root Builder specifies). The workaround is to point `overwrite` folder directly to the game folder, which isn't perfect as it clutters game folder and partially invalidates the meaning of using of MO2. Yet, it works.

Until the better solution is proposed, I'll leave the how-to here for users with the same problem:
1. Install MO2
2. Set `overwrite` folder in MO2 settings to the game folder, e.g. `C:\Program Files (x86)\Steam\steamapps\common\Cyberpunk 2077`
3. Install Root Builder as directed at https://kezyma.github.io/?p=rootbuilder
4. Add exclusions to Root Builder to stop hashing/backuping folders, which MO2 is dealing with just fine. I propose to set exclusions to `archive,BonusContent,mods,r6,tools` as for 1.6 game version.
5. Install any mods as usual, and for mods containing `bin` or `red4ext` folders, or any other folders containing binary files as `.exe` or `.dll`, move these folders to `root` subfolder.

Here's an example. If a mod folder in MO2 has a structure like this:

```
Some Mod
├── archive
│	└── some_folder_1
├── bin
│	└── x64
│		└── some_library.dll
├── engine
│	└── tools
│		└── some_executable.exe
└── r6
	└── some_folder_2
```

...it should become this:

```
Some Mod
├── archive
│	└── some_folder_1
├── r6
│	└── some_folder_2
└── root
	├── bin
	│	└── x64
	│		└── some_library.dll
	└── engine
		└── tools
			└── some_executable.exe
```

6. Run game through MO2 as you would usually do, Root Builder should do it's job and copy folders in root subfolder to the game folder, and remove them after you close the game.

> Note: if you failed to add exclusions to Root Builder, it will backup the entire game folder at first run, which is pointless.

The described procedure works for me on Cyberpunk 2077 v1.6 and both with and without Redmod installed.

> Bonus tip: don't use `--launcher-skip` argument if you want to use Redmod.

**Comment by TomTurbine** [comment] 2023-07-21 01:36
> MO2's virtual filesystem really is virtual. Unlike Vortex, which still writes symlinks or hardlinks to the real filesystem, MO2 replaces parts of the Windows file API at runtime with its own functions that behave as if the files were really there. This has the advantage that it keeps the game's directory completely clean, but certain files get loaded before the function hooks are set up, and so have to really be there. For the few cases where it's genuinely necessary, there's the root builder plugin linked above, which can copy or link specific files for real so they're accessible as soon as the process is launched.

Question if you don't mind. Since the issue is the hooks aren't setup before the game is loaded, couldn't MO2 have a setting where it could delay executing the games until after the virtual system is established?

Like have it delay actually launching the file by 2-5 seconds just to ensure the file hooks are in place? 

I won't lie, being able to setup the Script Extenders, Bug fixes, and ENB files via the mod organizer and leaving the actual game folder 100% untouched at all times would be great. Would make updating and swapping out ENBs and disabling fixes to check stuff massively simpler. Especially if you like to keep your game on 1 drive and your mods on another.

**Comment by tim-elmer** [comment] 2023-07-21 02:32
@TomTurbine I'm going to guess that it's less an issue of time, and more an issue of the order specific things have to load in.

**Comment by Silarn** [comment] 2023-07-21 04:54
Unfortunately it doesn't really have to do with the time it takes to load the file mappings, that's basically done before the application is launched. Essentially those libraries get loaded before usvfs is able to set up the memory hooks on the application.

There is a third party plugin that lets you set up tld files. It even supports using usvfs, but this will probably only work for certain types of files. It can also be configured to use links, which is the default behavior.

**Comment by TomTurbine** [comment] 2023-07-21 13:19
Ah, understood, That sucks but can't be dealt with.

Was just thinking about it because Root Builder sounds good until the first time you have a power outage in the middle of a game and it doesn't get the chance to delete the files.

**Comment by TomTurbine** [comment] 2023-07-21 17:06
Sorry to bug you too much, but another question if you don't mind. Do symlinks have issues with games?

I am asking this because if games could run like that without issue, would it be possible to just have a mod organizer create a duplicate of the game install in it's profiles using symlinks there to both the main game and the mods and then launch it like that? At least for games that supported having their directories moved.

Sorry if I am coming off as massively under informed on this but I kinda am and just thinking this off the top of my head.

**Closed** 2023-10-15 14:02 UTC
Labels: Feature Request
