### ISSUE TITLE
Add support for game [Starfield]

### ISSUE THREAD

**Issue by ActualEllie** [ModOrganizer2/modorganizer#1862] opened 2023-09-03 21:59 UTC
**Please provide the following information for the game (remove the optional lines you do not use):**

- **Name:** Starfield
- **Short name:** starfield
- **Nexus ID [optional]:** [https://www.nexusmods.com/starfield/mods/](url)
- **Executable:** Starfield.exe
- **Data path:** Starfield\Data
- **Documents path:** My Games\Starfield
- **Saves directory [optional]:** My Games\Starfield\Saves
- **Save extension [optional]:** SFS
- **Steam ID [optional]:** 1716740

### **Provide additional details regarding the game that could be required for the plugin.**
**Starfield Script Extender (SFSE)** will most likely be used in mods that significantly change the game: [https://github.com/ianpatt/sfse](url)

**Comment by Qudix** [comment] 2023-09-03 22:57
https://github.com/ModOrganizer2/modorganizer-game_starfield

**Comment by Jff007** [comment] 2023-09-04 05:49
Important note: Texture mods seem to need to go into the "My Games\Starfield\Data"  folder to be recognized in game.

**Comment by GRY4096** [comment] 2023-09-04 09:59
people have found out a way to load textures from the root data folder https://www.reddit.com/r/starfieldmods/comments/169b1jo/i_figured_out_how_to_make_texture_mods_load_from/

**Comment by DoubleYouC** [comment] 2023-09-04 15:29
Problem with that is as soon as they use Photo Mode to take a screenshot, it will break again.

**Comment by DoubleYouC** [comment] 2023-09-05 00:41
Did you actually test Photo mode as I mentioned? I tested again just now, and it instantly put the screenshot in Documents\My Games\Starfield\Data\Textures\Photos, with Message of the Day disabled and no existing Data folder in My Games. Since there now is a Textures directory, no Textures in the game's steamapps\common\Starfield\Data\Textures will load. You would need to never use Photo Mode for that to continue to work. 

Now, if Mod Organizer would hook into this and grab the photos and put it into Overwrite, or perhaps a special Photos mods directory, that would be able to fix the issue, provided that the My Games directory was cleared of the Textures level.

**Comment by Silarn** [comment] 2023-09-05 02:54
As it is mo2 would have to functionally delete the existing data directory when launching for that method to work.

I'm still exploring options.

**Comment by Silarn** [comment] 2023-09-05 02:56
I suppose the directory could be moved before launching and restored when finished, but this might cause problems for people that may have already installed something to that directory. Then again, that could be an issue anyway.

**Comment by Silarn** [comment] 2023-09-05 02:57
This still doesn't really resolve the photo mode as the game is hardcoded to look in the my games directory for those and that necessitates virtualizing that directory.

**Comment by dumpsters** [comment] 2023-09-05 12:27
Keep getting these
![Untitled](https://github.com/ModOrganizer2/modorganizer/assets/12140220/5f844369-6015-492f-9481-ee058e7b2125)

**Comment by Demaar** [comment] 2023-09-07 22:20
> https://github.com/ModOrganizer2/modorganizer-game_starfield
OK, no, what is this and how do I use it?

**Comment by fabio-s-franco** [comment] 2023-09-12 16:22
> https://github.com/ModOrganizer2/modorganizer-game_starfield

It would be nice if you could make a release there, so that people (whoever managed to figure out how to do it), don't need to install Qt, CMake and whatnot just to get a version that supports starfield.

**Comment by hiloyt** [comment] 2023-09-12 16:25
> > https://github.com/ModOrganizer2/modorganizer-game_starfield
> 
> It would be nice if you could make a release there, so tthe hat people (whoever managed to figure out how to do it), don't need to install Qt, CMake and whatnot just to get a version that supports starfield.

There is already build on the MO2 Discord server.

**Comment by Holt59** [comment] 2023-09-14 14:26
> > > > https://github.com/ModOrganizer2/modorganizer-game_starfield
> > > 
> > > 
> > > It would be nice if you could make a release there, so tthe hat people (whoever managed to figure out how to do it), don't need to install Qt, CMake and whatnot just to get a version that supports starfield.
> > 
> > 
> > There is already a build on the MO2 Discord server.
> 
> Let's not make content exclusive to Discord.. I agree the build should be available here.

We do not release alpha/beta versions of MO2 outside of Discord for many reasons, this is not going to change.

**Comment by frozht** [comment] 2023-09-15 09:45
> > > > > https://github.com/ModOrganizer2/modorganizer-game_starfield
> > > > 
> > > > 
> > > > It would be nice if you could make a release there, so tthe hat people (whoever managed to figure out how to do it), don't need to install Qt, CMake and whatnot just to get a version that supports starfield.
> > > 
> > > 
> > > There is already a build on the MO2 Discord server.
> > 
> > 
> > Let's not make content exclusive to Discord.. I agree the build should be available here.
> 
> We do not release alpha/beta versions of MO2 outside of Discord for many reasons, this is not going to change.

The discord invite is invalid, by the way.

**Comment by justjanne** [comment] 2023-09-21 13:18
> > > > > https://github.com/ModOrganizer2/modorganizer-game_starfield
> > > > 
> > > > 
> > > > It would be nice if you could make a release there, so tthe hat people (whoever managed to figure out how to do it), don't need to install Qt, CMake and whatnot just to get a version that supports starfield.
> > > 
> > > 
> > > There is already a build on the MO2 Discord server.
> > 
> > 
> > Let's not make content exclusive to Discord.. I agree the build should be available here.
> 
> We do not release alpha/beta versions of MO2 outside of Discord for many reasons, this is not going to change.

That's an absolute red flag indicative of malware. I've immediately uninstalled mod organizer after reading this, there is no reason not to use GitHub's pre-release feature unless you've got bad intentions.

**Comment by Holt59** [comment] 2023-09-21 13:37
> That's an absolute red flag indicative of malware. I've immediately uninstalled mod organizer after reading this, there is no reason not to use GitHub's pre-release feature unless you've got bad intentions.

Github releases are not better verified than other hosting services, so what you said is just completely wrong.  MO2 is 100% open-source, you can go through every part of MO2 and check for Malware. You can even build MO2 from yourself if you don't trust the internal builds.

MO2 releases and release candidates are always available on Github, we do not release beta version on Github because people do not understand the concept of beta version. When we release a beta versions for testers, we expect feedbacks for testers **on Discord**, because Discord is our main communication channels. 

If you do not feel like coming to Discord to download a beta version MO2, then you will never come to Discord to report bugs and other feedbacks from the beta version, and you will simply yell at us because the software will be bugged (**beta** software, remember? eh?), spam the Github issues, etc., etc.

**Comment by mkaito** [comment] 2023-09-21 14:23
> MO2 is 100% open-source

Except for all the conversations around issues and development that are buried in Discord, where it's incredibly hard to find and follow unless you're a daily active part of your buddy group.

> you will never come to Discord to report bugs and other feedbacks from the beta version

No, of course I wouldn't. Because that's absurd. Issues should be tracked in an adequate issue tracking system. Discord is not.

I don't care if you post builds on Discord. I would build it myself anyway, so that I can more easily debug any issues. But expecting me to be on Discord to document such issues is humbug.

> you will simply yell at us because the software will be bugged

I would search the issues on GitHub, and if I come up empty I would assume the issue is not reported and simply report it myself. On GitHub. Not on Discord.

You shouldn't assume a couple bad actors represent everyone that might use your project. Every open source project on this planet gets bad issues. Noisy, spammy, rude, and sometimes worse. You just close them and move on with your life. You don't cloister yourself in Discord. By doing that you're throwing the baby out with the bathwater.

This "discord or leave" attitude is quite off-putting in general. It's your project, and your prerogative, and I'm not your dad. But you are responsible for setting the tone and attitude of the project in general, and that will in turn determine both the quality and quantity of the community involvement you are likely to get. If that works for you, great. But I'm not inclined to go anywhere near it after reading through this.

**Comment by Holt59** [comment] 2023-09-21 14:56
> > MO2 is 100% open-source
> 
> Except for all the conversations around issues and development that are buried in Discord, where it's incredibly hard to find and follow unless you're a daily active part of your buddy group.

Community is much more active on Discord, if you have a problem with the beta version, someone will probably point you to a solution with a link to a message. Non developers are mostly not active on Github, so you will get way much support on Discord than on Github because there are way more beta users than developers within MO2.

> 
> > you will never come to Discord to report bugs and other feedbacks from the beta version
> 
> No, of course I wouldn't. Because that's absurd. Issues should be tracked in an adequate issue tracking system. Discord is not.

I can agree on that, but beta versions are subject to way too many bug and changes. Having quick back-and-forth with live message with users is much more convenient that communicating through asynchronous Github issues. 

Github issues are fine when you're dealing with developers, dealing with users through Github issues is way more complicated because users are not used to such systems and you often have to talk them through to help you debug the issue.

Also note that creating a MO2 releases (or release candidate) is long process that we basically bypass to create beta builds quickly and easily. Having to a do release for every beta version will greatly reduces the frequency of beta builds. 

> 
> I don't care if you post builds on Discord. I would build it myself anyway, so that I can more easily debug any issues. But expecting me to be on Discord to document such issues is humbug.
> 

You're developer - 100% of what I said above does not apply to you, so I don't really understand why you are even commenting here. As I already said multiple times on this thread, developers are used to use Github, do not expect standard Github to be, which is why we do not rely on Github to have users tests beta versions of MO2.

> > you will simply yell at us because the software will be bugged
> 
> I would search the issues on GitHub, and if I come up empty I would assume the issue is not reported and simply report it myself. On GitHub. Not on Discord.
> 
> You shouldn't assume a couple bad actors represent everyone that might use your project. Every open source project on this planet gets bad issues. Noisy, spammy, rude, and sometimes worse. You just close them and move on with your life. You don't cloister yourself in Discord. By doing that you're throwing the baby out with the bathwater.

Again, you seem to be used to developer communities. Most non-developer users just expect a easily available software to work, and then blame the developers for a non-working beta software. Putting a barrier to accessing the beta software greatly reduces the amount of such users.

> 
> This "discord or leave" attitude is quite off-putting in general. It's your project, and your prerogative, and I'm not your dad. But you are responsible for setting the tone and attitude of the project in general, and that will in turn determine both the quality and quantity of the community involvement you are likely to get. If that works for you, great. But I'm not inclined to go anywhere near it after reading through this.

It's not « Discord or Leave » - We never rejected Github issues or PR, etc., because the author was not on Discord. We are just way more reactive on Discord than on Github because it's easier to directly communicate.

I re-iterate my saying again and again but the « quantity of the community involvement » for MO2 mostly relies on testers and not developers, which are way more used to tools such as Discord than Github.

I will stop commenting on this subject - This is MO2 way of working and this will not change. If you want to discuss further on this matter, contact me directly via email (or via Discord... ) but please restrain from commenting on this issue since this is getting completely off-topic.

**Comment by Silarn** [comment] 2023-09-21 16:26
I also think it's time to close this discussion, but I would like to add that we often generate issues on GitHub directly through communication on Discord. It's not an either-or proposition. To most end users it's far more efficient to work through issues and identify core causes through a dialog on Discord than it is in piecemeal and slow GitHub issue conversation (which often end up abandoned and ignored by the issue creator when there isn't an immediate response).

The beta builds are more like internal development builds where we (a team of disparate volunteer coders spread across the world) can get immediate feedback about changes without publishing every single build to GitHub as if it's actually ready to be seen by the wider public.

And let's be honest here, the only reason this is all coming up is because there's a big new game release and a massive influx of people are clamoring for an update and don't have the patience to wait until it's actually release-ready.

These are beta builds for a reason. In fact, we usually label them as dev or alpha builds on Discord, but I think we are motivated to try to get an actual release out soon and the 'beta' label reflects that.

**Comment by Silarn** [comment] 2023-09-21 16:28
> > > > > > https://github.com/ModOrganizer2/modorganizer-game_starfield
> > > > > 
> > > > > 
> > > > > It would be nice if you could make a release there, so tthe hat people (whoever managed to figure out how to do it), don't need to install Qt, CMake and whatnot just to get a version that supports starfield.
> > > > 
> > > > 
> > > > There is already a build on the MO2 Discord server.
> > > 
> > > 
> > > Let's not make content exclusive to Discord.. I agree the build should be available here.
> > 
> > 
> > We do not release alpha/beta versions of MO2 outside of Discord for many reasons, this is not going to change.
> 
> The discord invite is invalid, by the way.
> 
> Edit: Nevermind, the discord invite in the README is invalid, but the one on the top right in the About section is working :P.

We've been working on updating the links. They're spread out all over the place and I guess that one expired for some reason.

**Comment by Silarn** [comment] 2023-09-21 16:49
In other news, considering the current state of Starfield modding, the actual support plugin (version 1) is largely done. You can either opt-in to the development beta on Discord if you're unable to wait, or you can wait a week or two when we may be ready to publish a release candidate that includes many more changes than just Starfield support.

I guess I'll leave this open for the time being so that people don't just open a new issue, but unless there's actual usable feedback I probably won't respond.

**Comment by AnyOldName3** [comment] 2023-09-21 17:01
> Every open source project on this planet gets bad issues. Noisy, spammy, rude, and sometimes worse. You just close them and move on with your life. You don't cloister yourself in Discord. By doing that you're throwing the baby out with the bathwater.

I think something key here is that you're conflating user support with issue tracking. We have literally hundreds of people coming to Discord to ask for support a day. The vast majority of those are just asking a *how do I do X* question that's got nothing to do with any issue. Most of the rest have just misunderstood how to do something, which only becomes worth considering a UX issue once a decent percentage of users are affected. It's comparatively rare that users asking support have encountered an actual bug that's worth having on the issue tracker, and even when it does happen, it's usually a duplicate of something we're already tracking, so doesn't need adding again.

GitHub issues aren't a good tool for general user support, and aren't intended to be. That's the whole point of GitHub having the discussions feature. If you've got a smaller project, or one that's generally only used by technical people who can solve their own problems and reasonably reliably determine if they've encountered a bug, then it can be feasible to ignore this, as the trickle of inappropriate issues will be manageable. For MO2, there are a huge number of users, and many of them are only technical enough to handle using mods, not to develop software, so there'd be a deluge of inappropriate issues if we didn't have other places for general support to happen, and an even larger one if dev builds only intended for MO2 enthusiasts were easy to stumble upon for regular users.

The simple fact of the matter is that having the experimental builds only on Discord puts a *massive* dent in the number of people using dev builds because they're not able to determine that they should actually be using a regular release, and a massive dent in the number of people experiencing problems without giving us enough information to make an actionable issue report that we have any hope of actually addressing.

**Comment by AnyOldName3** [comment] 2023-09-21 17:02
Oh, it seems I can't minimise my own comment as off-topic.

**Comment by fabio-s-franco** [comment] 2023-09-27 13:40
@Silarn I think a lot of this confusion could have been avoided if references to the alpha/beta starfield supporting version was more clearly communicated and pointed towards.
I for one simply gave up, because, although somewhere I heard that it could be accessed via discord, the link in the website was broken.

I have gotten here in an endless search for conclusive ways to get access to the to a version that adds support for starfield and no articles I read about the modorganizer say anything about actually getting a version that works with starfield.
A comment in this thread points to the repo with the source for the working version. When I got there I saw the source code (which I created an issue for as I was unable to compile). So whoever gets here or there, just reaches a dead-end.

Instead of people going through loops and searches all over the place, which by the way, still does not lead anywhere, why not add a comment in this thread and a README.md on the other repo, stating:

"To download the compiled version of the alpha/whatnot version, join our discord: (include invite link that works)".

It would've saved yours and everyone else's time by adding a very simple pointer, which shouldn't be so hard to find and will be reachable via search engine.

**Comment by Silarn** [comment] 2023-09-27 17:45
Discussion about dev builds is over. Any more comments about it will be deleted. I know of no major project, open source or otherwise, that regularly publishes unfinished and untested builds to their release channels.

If you want Starfield support before 2.5.0 is release ready then your only option is to participate in the development channels we currently use.

**Comment by fabio-s-franco** [comment] 2023-10-28 19:41
Wow, if there was any motivation for me to contribute to this project it is now completely gone. The toxicity is not worth it.

**Comment by Silarn** [comment] 2023-11-10 02:59
RC 1 is available for download.

**Closed by Silarn** 2023-11-10 02:59 UTC
Labels: fixed in next release, additional games support, Feature Request, area: mo2 game plugins
