### ISSUE TITLE
MO2 RC3 SSE - Not finding all updated mods

### ISSUE THREAD

**Issue by mpjbay** [ModOrganizer2/modorganizer#701] opened 2019-05-04 20:26 UTC
When I check for updates, not all updated mods are listed.

I tested by running the updater then going to nexus and checking. It looks like MO only reported about half the updated mods that actually have an update since the time it was downloaded. 

Thanks in advance.

**Comment by Silarn** [comment] 2019-05-04 22:44
There can be several reasons this might happen. We really need to know what specific mods, how they were installed, and what you've done since the update. You can potentially select your entire mod list, right click, and force check updates for everything. This should forcibly collect all latest update info no matter how recently mo2 thinks those mods were checked. Alternatively, if the specific file that was last installed was an add-on file or something similar, it may not be considered part of a standard mod update.

**Comment by mpjbay** [comment] 2019-05-05 03:45
Hi Silarn, Thank you for getting to me. I did a force check which had zero results. Seems strange because when I do a regular update check a few mods return with updates. I install mods from Nexus via MO2. There are loads of mods that need updates that are not showing in MO2 during a check however, "wet and Cold" is one that needed an update that did not now. Any thoughts? When I upgrade I run the installer, should I manually replace the files instead? Are there specific files that I can replace that deal with the update API?

**Comment by Al12rs** [comment] 2020-06-08 22:49
We didn't receive other reports of this happening on latest version, closing for organizational purposes. Please reopen if you can still reproduce.

**Closed by Al12rs** 2020-06-08 22:49 UTC
