### ISSUE TITLE
Crash while installing Interesting NPCs

### ISSUE THREAD

**Issue by bonesbro** [ModOrganizer2/modorganizer#1200] opened 2020-08-20 02:21 UTC
## The problem:
While installing Interesting NPCs (specifically, Interesting NPCs 3DNPC SE - Loose-29194-4-3-6-1582214998.7z from https://www.nexusmods.com/skyrimspecialedition/mods/29194) the app crashes while about 50% finished unzipping.  Nothing in the logs folder is useful and the crashDumps folder is empty.  

## To Reproduce:
Steps to reproduce the behavior: I downloaded the mod and double clicked it.  It crashed while the unzipping/installing progress dialog was zooming by.  It crashed at different points in the three times I tried it: once was at 12%, once was at 51%.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.3.2.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): Unknown.  I installed quite a lot with 2.3.0 or 2.3.1, including other large mods, and that worked fine.  I also installed at least a dozen other mods today with this build and it worked.  I installed several other mods after experiencing the crashes and that worked.
* Desktop OS/version used to run Mod Organizer: Win10 Pro, 10.0.18362 Build 18362

## Details:

Faulting application name: ModOrganizer.exe, version: 2.3.2.0, time stamp: 0x5f3a1c8d
Faulting module name: ntdll.dll, version: 10.0.18362.815, time stamp: 0xb29ecf52
Exception code: 0xc0000374
Fault offset: 0x00000000000f9229
Faulting process id: 0x8260
Faulting application start time: 0x01d67696abae11ff
Faulting application path: D:\games\MO2\ModOrganizer.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: bad9f26c-ebd8-4743-83ce-196ea127ac5a
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 2108064659320498892, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: ModOrganizer.exe
P2: 2.3.2.0
P3: 5f3a1c8d
P4: StackHash_a930
P5: 10.0.18362.815
P6: b29ecf52
P7: c0000374
P8: PCH_5E_FROM_ntdll+0x000000000009CBC4
P9: 
P10: 

and

Fault bucket 1198443114904242773, type 5
Event Name: FaultTolerantHeap
Response: Not available
Cab Id: 0

Problem signature:
P1: ModOrganizer.exe
P2: 2.3.2.0
P3: 5F3A1C8D
P4: ffffbaad

### USVFS:
https://gist.github.com/bonesbro/5c28abd8a2d001ebe23b9630f120cbc3

### MO Interface:
https://gist.github.com/bonesbro/a174ed4a01a4de03ed2d095f32158ece

**Comment by isanae** [comment] 2020-08-20 02:27
Make sure your log level in the settings is set to Debug, restart MO and reupload `mo_interface.log` here.

**Comment by isanae** [comment] 2020-08-20 02:49
I also can't reproduce the crash.

**Comment by bonesbro** [comment] 2020-08-20 11:51
Sorry about that - I'd set the log level to debug but didn't restart.  Here are the updated logs after I attempted a repro again and got another crash: https://gist.github.com/bonesbro/068493cd4505405cf0b2d1e9d0b34ba4

**Comment by Holt59** [comment] 2020-08-28 11:02
Do you have crash dumps in the `crashDumps` folder? If so could you upload the most recent one after reproducing the crash?

Also, you are on official 2.3.2, not RC1 or RC2, right?

**Comment by bonesbro** [comment] 2020-08-28 14:45
I'm afraid not - these crashes never populated anything in the crashDumps folder.  I mentioned that in the initial issue then confirmed it just now.

By the way, https://docs.microsoft.com/en-us/windows/uwp/monetize/get-desktop-application-error-reporting-data has information on how to get information from Microsoft on the crash dumps that people report.

**Comment by InfamousNate** [comment] 2020-11-03 21:19
Same issue, identical logs, no crash dump.  Mod partially installs.  BSA version of main file installs with no issue.  Extracting the BSA within Mo2 after BSA install was successful with no issue.  Loose files version crashes MO2 mid install with only partial files:
![image](https://user-images.githubusercontent.com/16141506/98041577-28468980-1df0-11eb-8d7d-ed2e1468094b.png)
Left is Losse file manual install and the right image is the folder inside mods after crash.

**Comment by Holt59** [comment] 2020-11-03 21:20
Does this always happen? Like if you try re-installing the loose version?

**Comment by InfamousNate** [comment] 2020-11-03 21:20
Sorry, I forgot to add that part.  Happens 100% of the time

**Comment by Al12rs** [comment] 2020-11-03 21:31
Could you either upload the file or show us the details of it, like size or maybe md5 hash? To check if there was an issue during download and the file isn't the same

**Comment by InfamousNate** [comment] 2020-11-03 21:34
Update:  Interesting turn of events..  After my last test of installing the BSA version and unpacking within Mo2 I decided to try and install the loose version one more time.  Watched Mo2 delete the old mod (extracted BSA) and install the loose version. I was expecting a crash around the 50% mark as usual (during the .fuz installation) and to my surprise, Mo2 installed the Loose version with no crash.  The only thing I did differently from the consistent 100% crashes was install the BSA version and unpack it, then install the loose version over top of it. I also had previously attempted to install the Loose version over the BSA (did not unpack) and Mo2 crashed around the 40%-50% (.fuz files) mark.  Seems unpacking the BSA first made a difference somehow.

**Comment by InfamousNate** [comment] 2020-11-03 21:36
Here's this:
![image](https://user-images.githubusercontent.com/16141506/98043149-c0457280-1df2-11eb-966e-95226f245cb7.png)

Where might I find the md5 hash?

**Comment by Al12rs** [comment] 2020-11-03 21:43
You can rename the metafile associated with it in the downlaods folder. Then enable log level debug in MO2 (right click on log window), then restart Mo2. then right click on the file in MO2 and press query info. Check the log for a `Searching SkyrimSE for MD5 of 737f792a5881265511873164fe924ad7`

**Comment by InfamousNate** [comment] 2020-11-03 21:47
Searching SkyrimSE for MD5 of 8a0b6c209e9611dcc29333f811b3a12d

**Comment by Al12rs** [comment] 2020-11-03 21:50
Do you actually get a hit?

**Comment by InfamousNate** [comment] 2020-11-03 21:51
Yeah it got a hit.  Crazy thing is even after removing the mod within Mo2 and re-installing the Loose version fresh, I cannot replicate the issue.

**Comment by Al12rs** [comment] 2020-11-03 21:52
What mod did Mo2 find with that md5 hash? My file had a different hash

**Comment by InfamousNate** [comment] 2020-11-03 21:58
Once the hit is acquired, a mouse over shows the correct file (interesting npc SE (3DNPC) (ID29194) with loose files in the description.  Clicking on "visit on Nexus" does take me to the correct mod page.  Is there another way I can verify?

**Comment by Al12rs** [comment] 2020-11-03 21:58
huh I guess I have a different version somehow

**Comment by Al12rs** [comment] 2020-11-03 21:59
Well you don't know how to reproduce anymore though right?

**Comment by InfamousNate** [comment] 2020-11-03 22:04
Yeah, the loose version installs just fine every time (tried 6 times).  I've been using the same archive the whole time so I'm not sure what the issue could have been.  I had another problem about a month ago and someone on the discord told me the VFS can be weird sometimes.  I've had other crashes in the past during installation of an archive but it was never persistent.

**Comment by Al12rs** [comment] 2020-11-03 22:07
VFS doesn't really come into play until you run a program from Mo2, like the game.

**Comment by InfamousNate** [comment] 2020-11-03 22:24
Makes sense.  Nothing virtual about unpacking an archive into a folder.  I was just thinking that it might have been some other one off oddity similar to what they were referring to.  I'll keep an eye out for any other persistent crashes when installing a mod and report back with the relevant information.  Thanks for looking into this.

**Comment by Holt59** [comment] 2021-01-11 13:37
Fixed by #1336, re-open if it happens again.

**Closed by Holt59** 2021-01-11 13:37 UTC
Labels: area: mod installers, issue report
