### ISSUE TITLE
Please re-introduce INI Tweaks per mod

### ISSUE THREAD

**Issue by tunbridgep** [ModOrganizer2/modorganizer#663] opened 2019-02-21 07:25 UTC
There are some mods such as Darnified UI for New Vegas which always need custom INI tweaks. There is also a mod I made called No Magic Compass which uses them (and sets them in a FOMOD installer) to disable Quest markers.

Would it be possible to re-introduce the INI tweaks capability in MO2? It was very, very useful as it helped to keep mods extremely self-contained. Currently, if I need, for example, Darnified UI's INI tweaks, I have to do them to the game INI itself and remember to change it back afterwards. This is bad from a philosophy standpoint as even being disabled, a mod might "bleed" into the rest of the game, which is bad. I want a mod to be COMPLETELY disabled when I disable it, and this includes disabling it's INI changes

I would simply like to have the original INI Tweaks restored, if at all possible.

Also, I am not sure the "Modify INI" fomod function ever actually worked. If not, it would be great to have it work the same way - it would basically add an auto-generated INI file to the list of ini tweaks for any given mod.

**Comment by Al12rs** [comment] 2019-02-22 20:58
Sadly all the code handling the Ini tweaks was inside the MO1 Virtualization library, basically it was hacking the game to allow a merged ini file to be shown.
MO2 has a completely new Virtual Library which is designed to be a general purpose VFS, with no modding specific code inside. It could be used by other applications which need a virtual file system, without any strange game specific hacks inside.

This means that the entire feature of INITweaks is simply not implemented and actually needs to be implemented from scratch to not require virtualization hacks. It is possible, but the amount of effort and time to implement is very high for the amount of use that the feature actually would see.

Newer games such as Skyrim already natively load INI files with the same name as plugins files (eg: if you have foobar.esp enabled, the game will also try to load foobar.ini if it finds it in the data folder).
So the only game that actually would make use of this is Oblivion, and only a restricted number of mods there.

I'm not excluding the possibility of implementing this, simply stating that there are a lot of other features that will take priority over this and the implementation isn't at all trivial.

If someone with development knowledge shows up wanting implement the feature then we would be happy to help him as we can.

**Comment by gab** [comment] 2019-07-15 04:44
@Al12rs If this feature was to be implemented, how would you envision it from a technical standpoint? Something like modifying the .ini on-the-fly when launching some application from MO2?

I was wondering if perhaps each ini line could be treated in the conflict logic and viewer as pretty much its own file, with the last mod to modify an ini line "winning".

**Comment by Al12rs** [comment] 2019-07-15 15:27
Im actually working on an Ini manager standalone application that will allow handling Ini edits as if they were mods with conflicts, priority with drag and drop etc. I's for a uni project that I have to show mid September but I have other exams to give as wel, so I still have not started on actual code. After the project is done I will see if I can Expose the functionality as a plugin for Mo2 or something

**Comment by AnyOldName3** [comment] 2019-07-15 18:09
I assume you're thinking of having it be an `IPluginFileMapper` with an `onAboutToRun` callback to:
* load an ini file from each mod directory
* combine those with the profile-specific ini or base game ini (depending on what the profile-specific ini setting says)
* put the combined ini into a temp location
and expose that path to the game with the `IPluginFileMapper` functions.

If so, you might have to figure out what happens when two file mapper plugins map the same path, as the ini bakery plugin will also try mapping something to that path. In fact, what does the ini bakery plugin even *do*? Is it just mapping the profile-specific ini if it's enabled and otherwise doing nothing?

**Comment by Al12rs** [comment] 2019-07-15 18:12
I guess I will find out when the time comes. Still have to start writing the damn thing and pass the exam, as well as three other exams...

**Comment by Al12rs** [comment] 2020-06-08 22:33
duplicate of #215

**Comment by AnyOldName3** [comment] 2020-10-22 19:36
This is a description of the original INI Tweaks implementation. There are source code snippets and thoughts on the implications above and below it: https://discordapp.com/channels/265929299490635777/412414009694748693/768522711931682916

Also, I'm not sure why we've got two instances of this issue and only one's got a Duplicate label.

**Closed** 2020-12-28 12:14 UTC
Labels: Feature Request, duplicate, help wanted
