### ISSUE TITLE
MO2 doesn't load mods

### ISSUE THREAD

**Issue by SpaceJoker13** [ModOrganizer2/modorganizer#358] opened 2018-05-13 16:17 UTC
# The problem

It all worked fine until, I think, a Windows update today. I'm not entirely sure since I haven't played Skyrim in like a week, but until then it was ok. Essentially running either Skyrim SE or SKSE from MO2 (top right) won't actually load the mods/plugins into the game. It's exactly like running the .exe from the Steam folder, where there are no mods installed, except that it crashes when i try to start a new game. 

# Environment
 MO2 v2.1.1.

Windows 10 Pro 1803

# Link to Mod Organizer logs

https://gist.github.com/SpaceJoker13/eb2c6163b928b803292085c80fbc55c5

https://gist.github.com/SpaceJoker13/08d489585d2d840529afcd1b6b0039ef

**Comment by Silarn** [comment] 2018-05-13 21:29
I suggest upgrading your install to 2.1.3, but you may need to restart and make sure anything like CCleaner is not wiping your windows logs as this tends to break USVFS.

**Comment by Cooperton** [comment] 2018-05-13 21:30
I'm having the same issue.  MO2 is fully up to date.  MO just doesn't seem to be working at all.  Fallout doesn't "see" any of the mods that are "installed"

Its quite frustrating.

**Comment by SpaceJoker13** [comment] 2018-05-13 21:47
@Silarn Yeah but that doesn't make any sense because this version was working up until last week/today's Win10 update, and I've already reinstalled MO2 by then (I've only kept the mods, overwrite and profiles folders). I might try and see whether the Antivirus or Win Firewall is blocking it.

**Comment by Al12rs** [comment] 2018-05-14 09:12
Why do you have 2.1.1? Please use the latest available version!

**Comment by Al12rs** [comment] 2018-05-14 09:17
Duplicate of #296

**Closed as completed** 2018-05-14 09:19 UTC
