### ISSUE TITLE
Game not launching depending on the game resolution.

### ISSUE THREAD

**Issue by EduX007** [ModOrganizer2/modorganizer#416] opened 2018-06-26 18:31 UTC
# The problem

If game resolution is set to 3840x2160, which for me is supersampling for a 1080p monitor, launching the game from MO2 directly will leave the screen black and the mouse in a loading wheel. Task Manager says Skyrim is not responding. However, if I create a shortcut for the exact same thing, the game is able to launch to the menu, without any changes to any settings. In that case though, the game sometimes seems to launch with the image supersized, as in a quarter of the game screen takes over the whole monitor, though switching windows to the game fixes that last part.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.3
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10

# Details

I unchecked the "Local Game Settings", so that the game would use the same graphic settings as set my GeForce Experience. This was done without any mods installed, only the Skyrim SE game files.

# Link to Mod Organizer logs

## USVFS
https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/5b0d093de4661b524d4363767e3640c2eb72ecf6/Log1.txt
https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/5b0d093de4661b524d4363767e3640c2eb72ecf6/Log2.txt

Log 1 was launching from MO2, Log 2 is launching from a desktop shortcut. If there was any launch using SKSE64, please disregard as I hadn't reinstalled yet the SKSE64 files.
Additionally, I had just reinstalled MO2 using the Archive version (had deleted the AppData and program files, and have tried as well before with the installer version). Also using at the moment Avast Antivirus.

## MO Interface
https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/5b0d093de4661b524d4363767e3640c2eb72ecf6/MOInterface.txt

**Comment by LostDragonist** [comment] 2018-06-27 03:08
I have not been able to reproduce this so far.  Here are the steps I followed:

1. Create a custom resolution of 3840x2160 (native resolution of 2560x1440) in the Nvidia Control Panel.
2. Set the resolution of the game to 3840x2160 in the INI file.
3. Launch the game.
4. Tell Windows to shut up about [blurry apps](https://i.imgur.com/6VjjbS1.png) as it was kicking me back to the desktop.
5. Launch Skyrim SE any which way and everything worked... for the most part.  That's SKSE, no SKSE, MO, no MO, local game settings, global game settings, shortcut, main MO window.

The one issue I did run into is that occasionally the game would launch and minimize itself after a second.  Attempts to restore the game would often minimize it again.  Eventually, restoring the window worked.  This specific issue appears to be due to something about the main MO window.  When using a desktop shortcut, the issue does not occur.  If the main MO window is not on the monitor running the game, the issue does not occur.  

Something about the change in resolution seems to cause the main MO window to steal focus from the game.  Maybe.  

Is it related at all to the original issue... maybe?  @EduX007, do you normally have problems alt-tabbing in and out of Skyrim?

**Comment by EduX007** [comment] 2018-06-27 05:19
Hmm, I didn't create a custom resolution, but rather choose that option from the Skyrim Launcher, which shows me 3840x2160 as an option.
Additionally, usually there is delay when alt-tabbing in and out of games for in general, which takes like a second and sound cuts off for a second, but that might be due to using fullscreen, not sure. Besides that, not really.
Additionally, I do also get the message telling me about blurry apps, which is at the time my screen is all black and the cursor a loading wheel.

**Comment by EduX007** [comment] 2018-06-27 05:30
Hmm, I didn't create a custom resolution, but rather choose that option from the Skyrim Launcher, which shows me 3840x2160 as an option.
Additionally, usually there is delay when alt-tabbing in and out of games for in general, which takes like a second and sound cuts off for a second, but that might be due to using fullscreen, not sure. Besides that, not really.
Additionally, I do also get the message telling me about blurry apps, which is at the time my screen is all black and the cursor a loading wheel.
Also, the shortcut does work whether the main window is open or not.

**Comment by EduX007** [comment] 2018-06-27 15:06
https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/a52560741381ae28f9ed4b8b279b15dd7bace11f/Log3.txt
I tried to changing it to 2715x1527, the other only resolution GeForce Experience was giving me, and I do have a NVIDIA card, 1070 Ti, driver version 398.11. Doing so, game did launch.
https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/b0a926ad6cedcc0f6db1b980365314fbb92af0f2/Log4.txt
Changing back to 3840x2160 caused again the previous problem.

**Comment by EduX007** [comment] 2018-06-27 15:07
https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/a52560741381ae28f9ed4b8b279b15dd7bace11f/Log3.txt
I tried to changing it to 2715x1527, the other only resolution GeForce Experience was giving me, and I do have a NVIDIA card, 1070 Ti, driver version 398.11. Doing so, game did launch.
https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/b0a926ad6cedcc0f6db1b980365314fbb92af0f2/Log4.txt
Changing back to 3840x2160 caused again the previous problem.
I do have experimental features enabled on GeForce Experience, so let me know if you'd like me to try disabling them and try again.

**Comment by Project579** [comment] 2018-06-27 19:06
You can try disabling them but I believe they are only for Audio features.

From the logs it seems that the problem is something from NVIDIA that wants to write on a location but MO2 virtual structure won't allow it, try disabling NVIDIA Share (from GeForce Experience) as well.

**Comment by EduX007** [comment] 2018-06-27 19:33
I disabled the overlay, and it didn't work. Then I disabled and then re-enabled the experimental features and it worked before and after re-enabling them. However, I restarted the computer and didn't work, did the same thing and didn't work again. Then I disabled it, restarted and didn't work again.
There are very few rare cases where it does work, only to then stop working without changing any setting.

**Comment by Project579** [comment] 2018-06-27 19:48
That is very odd, could you post the logs (both Interface and usvfs) when GeForce Experience is uninstalled and try both of the resolutions.

**Comment by EduX007** [comment] 2018-06-27 19:59
Interface: https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/88db8edcc82463232871cda12937560439b1972b/InterfaceUn

3840 (didn't work): https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/88db8edcc82463232871cda12937560439b1972b/LogUn3840

1080 (worked): https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/88db8edcc82463232871cda12937560439b1972b/LogUn1080

2715 (also worked, though didn't start the window as the focus, just switched to it and worked fine): https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/88db8edcc82463232871cda12937560439b1972b/LogUn2715

**Comment by Project579** [comment] 2018-06-27 20:08
In MO2 settings, diagnostic tab make sure Log Level is set to debug if not could you set it like that and redo the tests please.

**Comment by EduX007** [comment] 2018-06-27 20:19
Sorry, forgot I hadn't changed that setting when reinstalling MO2. Same results as before

Interface: https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/fe35843c23029fa6c7320358bb7257d6161dda47/InterfaceD.txt

3840: https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/fe35843c23029fa6c7320358bb7257d6161dda47/LogD3840.txt

2715: https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/fe35843c23029fa6c7320358bb7257d6161dda47/LogD2715.txt

1080: https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/fe35843c23029fa6c7320358bb7257d6161dda47/LogD1080.txt

3840, 2nd try: https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/fe35843c23029fa6c7320358bb7257d6161dda47/LogD3840(2).txt

**Comment by Project579** [comment] 2018-06-27 21:16
Could you try what LostDragonist did:
1. Create a custom resolution of 3840x2160 (native resolution of 2560x1440) in the Nvidia Control Panel.
2. Set the resolution of the game to 3840x2160 in the INI file.
3. Launch the game.

**Comment by EduX007** [comment] 2018-06-27 21:37
Sorry for asking about that, but when going to the NVIDIA Control Panel, do I set the custom resolution to 3840x2160, or 2560x1440. Am I supposed to change the native resolution somehow? (mine is set to 1920x1080)

**Comment by Project579** [comment] 2018-06-27 21:44
yes you need to add a new resolution

**Comment by EduX007** [comment] 2018-06-27 22:03
https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/3c5254a961d987a40829adfc5f30e2ae99a7abd2/LogT
Changed the resolution in SkyrimPrefs.ini, as well as the laucher to 3840x2160.
In the NVIDIA control panel I set the resolution to 2560x1440 at 60 Hz (monitor is 144, but for some reason it wasn't allowing to change the resolution at that level. Didn't work.

https://gist.githubusercontent.com/EduX007/f66e2deda2c2f659e98ff9756bad282b/raw/5cf1242e2f26e1dd3a77c7b86493e5680cdd98e8/LogT2
Changed the NVIDIA resolution to 3840x2160, game was able to launch. Gonna try again to see if it works after restarting.

**Comment by Project579** [comment] 2018-06-27 22:29
So it must be a bug of NVIDIA DSR clashing with MO2. I suggest you play like it is right now.

**Comment by EduX007** [comment] 2018-06-27 23:38
But with 2715x1527, which is also DSR, does work. Strange how only 3840x2160 is the problem.

**Comment by Project579** [comment] 2018-06-28 09:10
It could be just NVIDIA DSR being bugged or your Graphics card not having enough memory for a modded skyrim in 4k.

**Comment by EduX007** [comment] 2018-06-28 22:43
Okay, thanks for all your help with this.
Just to clarify that last part, I was running with no mods besides the official DLC, and the game can launch at 4K without MO2, with Geforce Experience automatically optimizing the game to that resolution.

**Comment by EduX007** [comment] 2018-07-01 18:02
Could be. In any case thank you so much for putting up with me during all this.

**Comment by Al12rs** [comment] 2019-09-18 19:22
I'm closing this for organizational purposes, please reopen if this issue is still happening.

**Closed by Al12rs** 2019-09-18 19:22 UTC
