### ISSUE TITLE
Mod Organizer 2 takes forever to launch F4SE, sometimes doesn't launch at all.

### ISSUE THREAD

**Issue by WolfJarl** [Modorganizer2/modorganizer#407] opened 2018-06-18 14:59 UTC
For a while now, after modding Fallout 4, Mod Organizer 2 refuses to start up F4SE through it. It takes at least five minutes for the game to boot up, while at other times it doesn't run at all. I've tried reinstalling Fallout 4 and its script extender, but it does nothing.

With any other game it has no issue and boots up each specific Script Extender properly.

Currently using Mod Organizer 2.1.4 (pre-Alpha), which is where the problem started, and where I started modding Fallout 4 to begin with.

17:43:57 [D] ssl support: 1
17:43:57 [D] data path: C:/Users/Joonas Sinkkonen/AppData/Local/ModOrganizer/Fallout 4
17:43:57 [D] Working directory: D:\Mod Organizer 2
17:43:57 [D] Loaded settings:
17:43:57 [D]   base_directory=D:/Mod Organizer 2/mods/Fallout 4 mods
17:43:57 [D]   compact_downloads=false
17:43:57 [D]   crash_dumps_max=5
17:43:57 [D]   crash_dumps_type=1
17:43:57 [D]   display_foreign=true
17:43:57 [D]   force_enable_core_files=true
17:43:57 [D]   hide_unchecked_plugins=false
17:43:57 [D]   language=en
17:43:57 [D]   load_mechanism=0
17:43:57 [D]   log_level=1
17:43:57 [D]   meta_downloads=false
17:43:57 [D]   nexus_login=true
17:43:57 [D]   nmm_version=0.65.2
17:43:57 [D]   offline_mode=false
17:43:57 [D]   use_prereleases=false
17:43:57 [D]   use_proxy=false
17:43:57 [D] initializing core
17:43:57 [D] usvfs log messages are written to C:/Users/Joonas Sinkkonen/AppData/Local/ModOrganizer/Fallout 4/logs/usvfs-2018-06-18_14-43-57.log
17:43:57 [D] Initializing VFS <mod_organizer_instance, 1, 1, C:/Users/Joonas Sinkkonen/AppData/Local/ModOrganizer/Fallout 4/crashDumps>
17:43:57 [D] downloads after refresh: 0
17:43:57 [D] initialize plugins
17:43:57 [D] looking for plugins in D:\Mod Organizer 2\plugins
17:43:57 [D] loaded plugin "bsa_extractor.dll"
17:43:57 [D] loaded plugin "check_fnis.dll"
17:43:57 [D] loaded plugin "diagnose_basic.dll"
17:43:57 [D] loaded plugin "game_fallout3.dll"
17:43:57 [D] loaded plugin "game_fallout4.dll"
17:43:57 [D] loaded plugin "game_fallout4vr.dll"
17:43:57 [D] loaded plugin "game_falloutNV.dll"
17:43:57 [D] loaded plugin "game_morrowind.dll"
17:43:57 [D] loaded plugin "game_oblivion.dll"
17:43:57 [D] loaded plugin "game_skyrim.dll"
17:43:57 [D] loaded plugin "game_skyrimse.dll"
17:43:57 [D] loaded plugin "game_skyrimvr.dll"
17:43:57 [D] loaded plugin "game_ttw.dll"
17:43:57 [D] loaded plugin "inibakery.dll"
17:43:57 [D] loaded plugin "inieditor.dll"
17:43:57 [D] loaded plugin "installer_bain.dll"
17:43:58 [D] loaded plugin "installer_bundle.dll"
17:43:58 [D] loaded plugin "installer_fomod.dll"
17:43:58 [D] loaded plugin "installer_manual.dll"
17:43:58 [D] loaded plugin "installer_ncc.dll"
17:43:58 [D] loaded plugin "installer_quick.dll"
17:43:58 [D] loaded plugin "pyCfg.py"
17:43:58 [D] loaded plugin "plugin_python.dll"
17:43:58 [D] loaded plugin "preview_base.dll"
17:43:58 [D] downloads after refresh: 71
17:43:58 [D] managing game at D:\Steam\steamapps\common\Fallout 4
17:43:58 [D] setting up configured executables
17:43:58 [D] configured profile: Default
17:43:58 [D] validating login cookies
17:43:58 [D] initializing tutorials
17:43:58 [D] localization file qt_en not found
17:43:58 [D] localization file qtbase_en not found
17:43:58 [D] localization file organizer_en not found
17:43:58 [D] localization file bsa_extractor_en not found
17:43:58 [D] localization file check_fnis_en not found
17:43:58 [D] localization file diagnose_basic_en not found
17:43:58 [D] localization file game_fallout3_en not found
17:43:58 [D] localization file game_fallout4_en not found
17:43:58 [D] localization file game_fallout4vr_en not found
17:43:58 [D] localization file game_falloutNV_en not found
17:43:58 [D] localization file game_morrowind_en not found
17:43:58 [D] localization file game_oblivion_en not found
17:43:58 [D] localization file game_skyrim_en not found
17:43:58 [D] localization file game_skyrimse_en not found
17:43:58 [D] localization file game_skyrimvr_en not found
17:43:58 [D] localization file game_ttw_en not found
17:43:58 [D] localization file inibakery_en not found
17:43:58 [D] localization file inieditor_en not found
17:43:58 [D] localization file installer_bain_en not found
17:43:58 [D] localization file installer_bundle_en not found
17:43:58 [D] localization file installer_fomod_en not found
17:43:58 [D] localization file installer_manual_en not found
17:43:58 [D] localization file installer_ncc_en not found
17:43:58 [D] localization file installer_quick_en not found
17:43:58 [D] localization file plugin_python_en not found
17:43:58 [D] localization file preview_base_en not found
17:43:58 [D] localization file pyCfg_en not found
17:43:58 [D] loaded language en
17:43:59 [D] interface Ethernet seems to be up (address: fe80::cd86:1a43:a5af:d04c%ethernet_32768)
17:43:59 [D] localization file bsa_extractor_en not found
17:43:59 [D] localization file check_fnis_en not found
17:43:59 [D] localization file diagnose_basic_en not found
17:43:59 [D] localization file game_fallout3_en not found
17:43:59 [D] localization file game_fallout4_en not found
17:43:59 [D] localization file game_fallout4vr_en not found
17:43:59 [D] localization file game_falloutNV_en not found
17:43:59 [D] localization file game_morrowind_en not found
17:43:59 [D] localization file game_oblivion_en not found
17:43:59 [D] localization file game_skyrim_en not found
17:43:59 [D] localization file game_skyrimse_en not found
17:43:59 [D] localization file game_skyrimvr_en not found
17:43:59 [D] localization file game_ttw_en not found
17:43:59 [D] localization file inibakery_en not found
17:43:59 [D] localization file inieditor_en not found
17:43:59 [D] localization file installer_bain_en not found
17:43:59 [D] localization file installer_bundle_en not found
17:43:59 [D] localization file installer_fomod_en not found
17:43:59 [D] localization file installer_manual_en not found
17:43:59 [D] localization file installer_ncc_en not found
17:43:59 [D] localization file installer_quick_en not found
17:43:59 [D] localization file plugin_python_en not found
17:43:59 [D] localization file preview_base_en not found
17:43:59 [D] localization file pyCfg_en not found
17:43:59 [D] reading save games from C:/Users/Joonas Sinkkonen/Documents/My Games/Fallout4/Saves
17:43:59 [D] displaying main window
17:43:59 [D] retrieving credentials
17:44:00 [D] D:\Mod Organizer 2\mods\Fallout 4 mods\profiles\Default\modlist.txt saved
17:44:00 [D] this version is newer than the newest installed one: 2.1.4 pre-alpha -> 2.1.3
17:44:06 [D] D:\Mod Organizer 2\mods\Fallout 4 mods\profiles\Default\initweaks.ini saved
17:44:06 [D] D:\Mod Organizer 2\mods\Fallout 4 mods\profiles\Default\plugins.txt saved
17:44:06 [D] D:\Mod Organizer 2\mods\Fallout 4 mods\profiles\Default\loadorder.txt saved
17:44:06 [D] D:\Mod Organizer 2\mods\Fallout 4 mods\profiles\Default\lockedorder.txt saved
17:44:06 [D] Load Mechanism: Mod Organizer
17:44:06 [D] USVFS DLL Name: usvfs_x64.dll
17:44:06 [D] enable local saves: 0
17:44:06 [D] Updating VFS mappings...
17:44:07 [D] D:\Mod Organizer 2\mods\Fallout 4 mods\profiles\Default\archives.txt saved
17:44:07 [D] VFS mappings updated <linked 55 dirs, 2 files>
17:44:07 [D] Spawning direct process < "D:/Steam/steamapps/common/Fallout 4/f4se_loader.exe" , "" , "D:/Steam/steamapps/common/Fallout 4" >
17:44:07 [D] Waiting for spawned process completion : f4se_loader.exe (2612)
17:50:08 [D] Waiting for usvfs process completion : Fallout4.exe (13056)
17:50:46 [D] Waiting for process completion successfull
17:50:46 [D] D:\Mod Organizer 2\mods\Fallout 4 mods\profiles\Default\lockedorder.txt saved
 [D]

**Comment by Al12rs** [comment] 2018-06-18 15:25
This is probably a really bad idea:
`17:43:57 [D] base_directory=D:/Mod Organizer 2/mods/Fallout 4 mods`
Could you try creating a new empty Instance from the top left button, install only FOSE and try running the game? Don't change paths etc.

**Comment by WolfJarl** [comment] 2018-06-18 16:31
Launched instantly. But I'd really rather not have any additional data on my C drive if I can help it, as it's remarkably smaller compared to my D drive (intended for games).

**Comment by Al12rs** [comment] 2018-06-18 17:04
Then move the new base directory on the D drive, like in D:\Mod Organizer 2 Instances\Fallout4Inst1
and try again to see if there are major reductions in speeds. If there aren't then it's safe to assume that one of the mods in the other instance is the cause of the slowdown and not MO2.

**Comment by WolfJarl** [comment] 2018-06-18 18:03
Did so. It seems to be a mod since the problem persists. Gonna see if turning off all mods fixes the issue.

**Comment by WolfJarl** [comment] 2018-06-18 18:06
Nevermind. Didn't fix it either.

**Comment by Al12rs** [comment] 2018-06-18 19:37
Then maybe a ini setting?

**Comment by Al12rs** [comment] 2018-07-21 09:52
Closing since this is most probably not MO2's fault. If you still have the problem and you still believe it's mo2 fault then I will reopen

**Closed** 2018-07-21 10:07 UTC
