### ISSUE TITLE
Option to let users keep mod directories pristine when executables try to overwrite files

### ISSUE THREAD

**Issue by cagelight** [ModOrganizer2/modorganizer#724] opened 2019-05-20 17:11 UTC
There's an option to have executables run through MO create files in a mod directory instead of Overwrite, atm this only creates files here, but file modifications still overwrite the files in their original mod directory. Would it be possible to have this option also redirect file modifications to new files in this directory so that one could more easily keep original mod files pristine?

**Comment by Al12rs** [comment] 2019-05-23 06:51
Duplicate of #352 ,please check our discussion of this over there.

**Comment by Al12rs** [comment] 2019-05-23 06:52
Closing for better organization

**Closed by Al12rs** 2019-05-23 06:52 UTC
Labels: Feature Request, duplicate, usvfs
