### ISSUE TITLE
WryeBash Windows 7 infinite loop.

### ISSUE THREAD

**Issue by SuwinTzi** [ModOrganizer2/modorganizer#506] opened 2018-08-28 08:28 UTC
When attempting to build bash patched by running Wrye Bash through MO2, Wrye Bash will run into memory leak where bashedpatch.html and Docs will fail to save/generate.  Applies to WB 306 and 307 beta.  Unknown if occurs with older Wrye Bash.  Edit: Current OS Windows 7 Ultimate x64

MO2 Version 2.1.5 and 2.1.4 exhibit this issue.
MO1 Final release does not have this problem.  Current solution is to build bashed patch through MO1 by migrating installed mods and profiles to MO1, then profiles back to MO2.

MO2 and MO1 are installed on C: drive while Skyrim and WB are on D:

MO2 does not generate any error logs, only WB errors are generated.

**Comment by Al12rs** [comment] 2018-08-28 08:32
Operating system?

**Comment by Project579** [comment] 2018-08-29 10:32
Wait how do you know that causes a memory leak?

**Comment by Al12rs** [comment] 2018-08-29 11:13
It isn't a memory leak simply the code gets stuck in a loop like it does for you @Project579 , if that code acquires resources or something then memory goes up. We need to isolate the issue and fix it.
@SuwinTzi for a temporary fix try to create an empty `docs` folder in your data directory.

**Comment by Project579** [comment] 2018-08-29 16:28
We are talking Python here not C++, garbage collection is a thing; everything is "leaked" like in Java.

**Comment by Silarn** [comment] 2018-08-29 19:35
Well right, things get deallocated automatically when they go out of scope. It's more of a recursive loop issue where we never get out of scope and keep allocating new memory.

**Comment by Project579** [comment] 2018-08-29 19:37
Also Wrye Bash just throws a million kernel exceptions anyway, not sure if it does it outside of MO2 as well.

**Comment by SuwinTzi** [comment] 2018-08-31 02:29
Having the docs folder allows WB to complete the patch thanks.

**Comment by Al12rs** [comment] 2019-06-25 22:04
This should have been fixed in 2.2.0, or possibly with recent usvfs patches on disocrd if that is not the case.
Could you please test if the issue is resolved? 
If no response within 20 days we will assume the issue resolved.
If that is not the case we will later re-open the issue.

**Closed** 2019-08-03 13:08 UTC
Labels: Windows 7, Wrye Bash, bug, needs investigation, potential fix, usvfs, waiting on user
