### ISSUE TITLE
Can't switch between profiles

### ISSUE THREAD

**Issue by Fracco** [ModOrganizer2/modorganizer#1495] opened 2021-04-24 10:06 UTC
I can't switch between profiles; the only way I have is to delete all other profiles and restart MO2.

**Comment by LostDragonist** [comment] 2021-04-25 00:03
How are you trying to switch?  The main way of switching profiles is the drop-down above the mod list.  There is also a button called "switch" in the profiles window that is currently broken.

**Comment by isanae** [comment] 2021-04-25 00:07
The "Select" button is broken when the window is opened from the menu and toolbar, but it works from the `<Manage...`> item. So it's just kinda 2/3 broken.

**Comment by isanae** [comment] 2021-04-26 04:37
Duplicate of #1489.

**Closed by isanae** 2021-04-26 04:37 UTC
