### ISSUE TITLE
Tutorial stuck - mod "Information"

### ISSUE THREAD

**Issue by super-aardvark** [ModOrganizer2/modorganizer#1472] opened 2021-03-20 19:46 UTC
## The problem:
Going through the tutorial, after the bit about plugins, I came to a step about the "Information" menu for a mod.  After exiting the Information window, the tutorial is stuck.

## To Reproduce:

1. Follow the tutorial until you can't anymore
2. ???

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.0 r70840210
* Last Mod Organizer Version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
Going through the tutorial, after the bit about plugins, I came to this step: "A single mod may contain zero, one or multiple esps.  Some or all may be optional. If in doubt, please consult the documentation of the individual mod. To do so, right-click the mod and select 'Information'."  I right-clicked a mod and selected "Information...", and got more tutorial bits in that window, mentioning the Nexus Info tab and other things, and culminating in: "We may revisit this screen in later tutorials."  I clicked around a bit, looked at the "Optional ESPs" tab, the Nexus Info tab, and others.  Then I clicked the Close button (I've also reproduced it by clicking nothing but the Close button).  Now the first instruction quoted above is still there on the main screen, with the left-hand pane (mod list) highlighted.  I can't tell what to do to advance the tutorial.

### USVFS:
https://gist.github.com/super-aardvark/0a82289a3b5665ed8fafeabe5f489075#file-usvfs-2021-03-20_13-10-40-log

### MO Interface:
https://gist.github.com/super-aardvark/0a82289a3b5665ed8fafeabe5f489075#file-mo_interface-log

**Comment by isanae** [comment] 2021-03-20 19:48
Duplicate of #1419.

**Closed by isanae** 2021-03-20 19:48 UTC
Labels: issue report
