### ISSUE TITLE
FO4 crashes after a short time when launched through the launcher 

### ISSUE THREAD

**Issue by AstartesFanboy** [ModOrganizer2/modorganizer#1056] opened 2020-04-17 15:40 UTC
## The problem: When I launch FO4 it works for a bit,  but after a short amount of time the game crashes to desktop without any error message or anything. I’ve tried it with mods and without any mods and the same thing happens no matter what.

Briefly describe the issue you are experiencing. Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our [discord channel](https://discord.gg/5tCqt6V)

## To Reproduce:

1. Launch the game 
2. Click on anything just okay it 

## Environment: just the start of the game outside and in the vault 

* Mod Organizer Version that exhibits the issue: 2.2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details: game crashes to desktop after a short amount of time playing without any error messages. Have only gotten to the vault once and that was launching through steam. Quit and relaunched the game through the mod manager and it crashed when I got into the cryopod. It happens whether I have mods activated or not
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Al12rs** [comment] 2020-04-17 16:04
To check whether the issue is related to one of the mods installed or your ini settings, see if it keeps happening in a new empty profile:
https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png
https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png

Also make sure you don't have any mods installed in actual game folder, and test if the issue happens outside of Mo2 if you didn't already.

**Comment by Al12rs** [comment] 2020-06-10 07:40
Closing due to no repsponse and things look like it's not a mo2 issue.

**Closed by Al12rs** 2020-06-10 07:40 UTC
Labels: issue report
