### ISSUE TITLE
Reproducible Exception Dialog When Running App in 2.1.6

### ISSUE THREAD

**Issue by TheRealKraggy** [ModOrganizer2/modorganizer#593] opened 2018-12-23 21:38 UTC
# The problem

Reproducible Exception Dialog When Running App in 2.1.6

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.6
* Last Mod Organizer Version that did not exhibit the issue (if applicable): 2.1.5
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro

# Details

1) Run Tool A via the RUN button: it works
2) Run Tool B as an elevated process: it works
3) Run Tool A: an error dialog appears reporting a usvfs_proxy_x86 error, when dismissed tool A works as before.

This dialog will now appear on every RUN of any tool until MO2 is closed, it will come back whenever an elevated process is RUN

# Link to Mod Organizer logs

Sorry, I'm an end-user not a developer, I have no idea what:
"Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here."
means. 

Please refer to this thread on STEP's site where I reported this (as directed by the STEP MO Guide!):

https://forum.step-project.com/topic/13808-reproduceable-exception-dialog-when-running-app-in-216/?p=230948

**Comment by LostDragonist** [comment] 2018-12-23 21:44
Duplicate of https://github.com/ModOrganizer2/modorganizer/issues/218.  This is a known issue.  Previously, MO2 would have failed silently.  Now it warns they user that they're doing something wrong.

**Closed by LostDragonist** 2018-12-23 21:44 UTC

**Comment by TheRealKraggy** [comment] 2018-12-23 21:54
So WHAT am *II doing wrong by running a tool that needs elevation?

**Comment by LostDragonist** [comment] 2018-12-23 21:58
That was probably a poor choice of words on my part.  "Now it warns the user that they're doing something that is breaking the virtual file system."

You're running a tool that needs elevation.  This breaks the virtual file system for subsequent things that are not run elevated.  We plan to add something that'll let MO2 handle this better at some point.

**Comment by Al12rs** [comment] 2018-12-23 22:02
To avoid the issue set MO2 to run as admin @TheRealKraggy so that it does not need to switch to elevated mode during execution
