### ISSUE TITLE
Corrupting existing mod installs

### ISSUE THREAD

**Issue by TheSeekingArrow** [ModOrganizer2/modorganizer#535] opened 2018-09-26 09:48 UTC
# The problem

Both a CTD and/or a forced close of SkyrimVR results in the corruption of mods and/or mod files. Despite showing mods are installed and .esp files are checked in the load order, skyrim will report .esp files as missing and other mod files simply will fail to load files. For instance, follower .esp files will be missing despite being checked in the load order. Additionally, certain mods that aren't showing as missing during the load of a game like CBBE base files will indeed be missing critical files and fail to function properly in the game.

This makes it very difficult to know if a mod stops working due to a CTD until I finally come across a texture that was working but has now been screwed up.

The issue is always always always fixed by simply right clicking on the mod and reinstalling by selecting 'replace'. I don't have to do anything else except that and it fixes the problem. These are not mod conflicts at all, but are issues that arise directly as a result of forcing skyrimVR to close outside of the normal method of quitting the program.

This has happened enough times now to narrow down the issue, and the issue always arises as a result of the above described cause.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Mod Organizer: Windows 10 Pro 64 bit

# Details

In this latest episode, the following esp was missing despite me not touching the load order: Zwabber_Kaylin.esp

And Caliente's CBBE mod and textures were completely missing from the game. The resulting bodies had two belly buttons and were missing slices of texture from the hips and the shading was pretty smashed up on the bodies.

I was able to create this problem simply by forcing the program closed by right clicking on the task bar and selecting close.

Additional mods are probably corrupted as well, but it would require days of work to determine which are effected. The only thing I can do is reinstall every single mod again after an issue like this.

# Link to Mod Organizer logs

## USVFS
(3 files attached here)
https://gist.github.com/TheSeekingArrow/aff9c92dcd58e179589fa57a2816f06d

## MO Interface
(same, 3 files attached here)
https://gist.github.com/TheSeekingArrow/aff9c92dcd58e179589fa57a2816f06d

**Comment by Project579** [comment] 2018-10-11 11:06
Can you please test this while not using MO2?

**Comment by TheSeekingArrow** [comment] 2018-10-11 14:49
MO2 uses a virtual filesystem. How am I supposed to test this without using MO2?

**Comment by Al12rs** [comment] 2018-10-11 16:28
What Project was asking is whether SkyrimVR kills setups even when installing mods manually and forcing the game to close. None of the Devs have SkyrimVR to test.
To test you would have to install a small number of mods manually and see if the game deletes files etc when it is made to crash. 
As far as we know no one experienced this kind of issue neither on the other games nor on SkyrimVR, but Skyrim VR is not as widely used

**Comment by TheSeekingArrow** [comment] 2018-10-12 12:29
Testing a small subset of mods which are manually installed could potentially provide a false negative test result. Such a test result would then necessitate the test be repeated, but with the full set of mods installed. Considering I have 200 mods installed, this is a debugging path I don't have the time/skill to pursue.

However, all is not lost. Since this issue appears to be a first of it's kind, I would suggest this issue report at least be preserved as a starting/reference point for any future issue reports that align with my experience. If the issue does resurface, it seems it will likely come from the small subset of SkyrimVR users. Thanks.

**Comment by Al12rs** [comment] 2018-10-12 12:47
All right, as it stands the alternative debugging path for us would mean manually searching for an error in the code while not being able to reproduce the error. So until more information is found there is not much to do.

**Comment by Al12rs** [comment] 2019-09-20 07:40
Since there have been no further reports of this happening I'm closing for organization purposes, please reopen if this still happens.

**Closed by Al12rs** 2019-09-20 07:40 UTC
Labels: needs investigation
