### ISSUE TITLE
Save game delete when turning off local savegame

### ISSUE THREAD

**Issue by Wash113** [Modorganizer2/modorganizer#176] opened 2017-12-27 20:33 UTC
# The problem

Save files are deleted if you do not move then back to global before disabling local savegame

# Environment

Mod Organizer v2.1.0.1
Running as admin

# Details

NA not a whole lot else. no prompts or anything. They were just gone. I have been able to repeat this issue

# Link to Mod Organizer logs

Not sure what these are or which one you would need so I sent you all of them that I have

## USVFS
[usvfs-2017-12-27_18-03-26.log](https://github.com/LePresidente/modorganizer/files/1589824/usvfs-2017-12-27_18-03-26.log)
[usvfs-2017-12-27_18-02-20.log](https://github.com/LePresidente/modorganizer/files/1589825/usvfs-2017-12-27_18-02-20.log)
[usvfs-2017-12-27_18-01-24.log](https://github.com/LePresidente/modorganizer/files/1589826/usvfs-2017-12-27_18-01-24.log)
[usvfs-2017-12-27_17-59-59.log](https://github.com/LePresidente/modorganizer/files/1589827/usvfs-2017-12-27_17-59-59.log)
[usvfs-2017-12-27_17-58-47.log](https://github.com/LePresidente/modorganizer/files/1589828/usvfs-2017-12-27_17-58-47.log)
[usvfs-2017-12-27_20-20-58.log](https://github.com/LePresidente/modorganizer/files/1589829/usvfs-2017-12-27_20-20-58.log)

## MO Interface
[mo_interface.log](https://github.com/LePresidente/modorganizer/files/1589818/mo_interface.log)

**Comment by CptMcSplody** [comment] 2017-12-27 20:46
Does it happen when your not running as Admin?

There should be a prompt on unticking local save games.

If you tick it again they should show.

**Comment by Al12rs** [comment] 2017-12-27 22:51
I have tried replicating this too and I always receive the prompt that asks if I want to delete or not.
Could you update to the last build on nexus and try to replicate your issue while monitoring what happens inside your profile and save folder. The initial situation should be with the saves in mygames and no Saves or Saves_ folders inside your profile folder. Then you should enable local saves and transfer your saves (you can choose to copy or cut). At this point there should be a folder named Saves in your profile containing the transfered files. Now, if you deselect the local saves, a dialogue should pop up asking if you want to keep the saves. Please describe the behavior you experience after this point.
![image](https://user-images.githubusercontent.com/26797547/34395483-e232a902-eb60-11e7-91d3-e4fc4e32b014.png)

**Comment by Wash113** [comment] 2017-12-27 22:52
Yeah they don’t come back when I turn local back on. At least for me

**Comment by Wash113** [comment] 2017-12-27 22:53
I will update and try it when I get home tonight and let you know

**Comment by erasmux** [comment] 2017-12-27 23:01
Does that reproduce for you with a clean install? Meaning open the latest build to a new clean directory, select portable install and replicate issue with minimal steps. If you manage to reproduce it like this please detail the minimal steps necessary to reproduce the issue. Thanks.

**Comment by Al12rs** [comment] 2018-04-09 19:06
Closing this since we were not able to reproduce and we received no further feedback

**Closed by Al12rs** 2018-04-09 19:06 UTC
Labels: awaiting feedback, bug
