### ISSUE TITLE
Unable to unpack 7z file

### ISSUE THREAD

**Issue by grc472** [ModOrganizer2/modorganizer#585] opened 2018-12-13 18:38 UTC
# The problem

MO2 crashes whenever I try to install the "SurvivalConfig - Patches.7z" file from https://www.nexusmods.com/skyrimspecialedition/mods/14404.  I can install other 7z files, including the SurvivalConfig.7z main file from that same mod, but the patches file crashes every time.  I created it using 7zip version 18.05 (x64) with default settings.  I tried installing it with Vortex and it worked just fine.  

There is something about that file that MO2 doesn't like, but the logs don't show anything relevant.  The crash is manifested as a popup error dialog that is blank.  The dialog title says "Error", but the client area is completely blank.

Also, if I recreate the patches file and change the archive format from 7z to zip, then MO2 is able to install it with no errors.

# Environment

* Mod Organizer Version that exhibits the issue:  2.1.5
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:  Windows 10

# Details

See above.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by LostDragonist** [comment] 2018-12-13 18:45
I can reproduce this with problem with MO 2.1.5 but not with MO 2.1.6 (soon to be released).  It looks like this should be fixed along with some other similar problems we've fixed.  You can grab the development build on our discord if you want to try it out earl.y

**Comment by Al12rs** [comment] 2018-12-13 18:58
Soon means hopefully within two weeks depending on how many issues the test builds have.

**Comment by LostDragonist** [comment] 2018-12-13 19:03
I might've spoke too soon.  The specific problem of "The dialog title says "Error", but the client area is completely blank" seems to be fixed in 2.1.6.  

There appears to be another problem where running the installer twice breaks things.  It works the first time but some files are left in %TEMP% so that the installer will fail the second time.  This happens for me regardless of if it's a .7z or .zip file.

The specific files being left behind are images\HB.png and images\MD.png.  I'll have to take a closer look.

**Comment by LostDragonist** [comment] 2018-12-13 19:06
Ah, HB.png and MD.png are read-only in the archive.  Getting rid of that lets MO delete the files properly.  

You might give that a shot and see if it fixes your problem in 2.1.5.  You'll probably have to manually delete %TEMP%/fomod to get it to work right.

**Comment by grc472** [comment] 2018-12-13 19:07
Yes, I completely forgot to mention that.  Sorry.  Once it fails you have to manually delete those temp files.  Presumably, if it does not fail in the first place with 2.1.6 then that won't be a problem.  You might need some logic to clean up past failures, though.

**Comment by LostDragonist** [comment] 2018-12-13 19:36
I've made some additional changes to 2.1.6 to prevent issues like this in the future.  

1.  MO2 will change the permissions on the temporary files so it can delete them even if they're read-only.  
2.  The user will be warned if any temporary files can't be deleted.

Everything should work just a little better now.  Thanks for the report, @grc472!

**Comment by LostDragonist** [comment] 2018-12-21 21:04
MO [v2.1.6](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.1.6) has been released and this bug should be fixed.  If anyone runs into this again, please submit a new issue.

**Closed by LostDragonist** 2018-12-21 21:04 UTC
Labels: bug, fixed in next release
