### ISSUE TITLE
Disabling "MO is locked" makes mo2 executable desktop shortcuts not see the mods

### ISSUE THREAD

**Issue by Viscerous** [ModOrganizer2/modorganizer#422] opened 2018-07-02 10:39 UTC
# The problem

This may not even be considered an issue necessarily, but when MO isn't running and you're simply launching a game from a shortcut made by MO, I don't think this dialogue box should come up unless MO is also running.

I remember at some point the previous behaviour of launching a shortcut, was simply to show the splash image of its associated instance, then launch the game. Considering you get to customise these splash images, this looks a lot nicer.

Low priority 'issue' of course.

# Environment

* Mod Organizer 2.1.3
* Old behaviour was all the way back in MO1 I think
* Windows 10 1803

**Comment by Al12rs** [comment] 2018-07-02 11:01
This was done intentionally by erasmux. Mo is running while the program is launched. I think it was done so that it the user wouldn't be able to run another program from another shortcut at the same time.

**Comment by Silarn** [comment] 2018-07-02 20:28
Not really, it's because some small version of MO has to be running to manage the file mappings to USVFS. If it's closed, the VFS will ultimately stop working correctly. (And it will definitely fail to hook any additional apps.)

**Comment by Silarn** [comment] 2018-07-02 20:33
To be more specific there are a couple variables that are instantiated by the MO2 process which are updated by USVFS to tell it when the processes are done running. Without this variable USVFS will not work properly and may just crash.

**Comment by Al12rs** [comment] 2018-07-02 20:54
I think the question is if there is any need for the ui together the Mo2 process.

**Comment by Silarn** [comment] 2018-07-02 22:18
The better question is what benefit does that get you? The vast majority of the application is not loaded, it's just one dialog box. The resource load is minimal and it lets you know if there are any remaining hooked processes on your system.

Yes it could be done as a background process but there's barely anything gained from that and definitely something lost. What happens if there's another application hooked for some reason keeping usvfs and the background mo running? You have no way to identify what it is.

**Comment by Al12rs** [comment] 2018-07-03 09:13
And the above is a very good answer. @Viscerous there you go, if that is satisfactory to you we can close the issue.

**Comment by Viscerous** [comment] 2018-07-03 10:40
>The better question is what benefit does that get you?
Quite honestly, it prevents you from having yet another program running in your task bar solely for hand holding a group of users unlikely to even use MO to begin with.

It's basically as if you were leaving a "Game is running" box open all the time for running a Steam game, as Steamworks also hooks into the process whilst also disallowing you to run other Steam games at the same time. People already know they shouldn't, and it seems like an easy thing to disallow launching another game through MO or leave a message when the user tries, like Steam does. Which is at the same time a lot less vague than having a dialogue box open the entire time.

**Comment by Al12rs** [comment] 2018-07-03 11:57
Sometimes some random programs get hooked by usvfs like chrome and steam so that window tells you that inviting you to close them to stop usvfs. You can technically launch more programs under usvfs at the same time running other shortcuts etc and nothing actually stops you, we discourage it as we can't guarantee that everything will work well. Most important thing is not mess with the virtualized files from outside the VFS, while it is running, which could happen if a program is hooked and there is no indication of it anywhere.

**Comment by Viscerous** [comment] 2018-07-03 12:07
I'm sorry but I've _never_ seen MO hook 'random' programs. And even if it did, the box does not tell you what is hooked, so it would not help in this situation whatsoever.

**Comment by Al12rs** [comment] 2018-07-03 12:32
Well we have, and the box does tell you, after closing the first program, if there is another one there, by listing it's name. It will remain open until all hooked processes have ended. I believe being transparent to what Mo2 is doing is important.

**Comment by Viscerous** [comment] 2018-07-03 12:39
Okay look, if you find it so important to have this box impede and question the user's ability to think for themself, how about at some point in time at least introducing an _option_ for the people who are familiar with MO to simply disable locking altogether. Put a small disclaimer on it if you have to, informing the user that hooking multiple programs at once may not work well. In practice I imagine the main use case for having a shortcut rather than working inside MO would be to actually use or play said program/game, which would cause no issues to begin with.

**Comment by Al12rs** [comment] 2018-07-03 12:51
I don't see what the problem is with having that little box? It does not look good? It serves a very specific purpose which is to let the users know if there is a program using the vfs and which one. It's not a question whether they know how to use Mo or not. I of course know how to use Mo2 but if the hooked process is not shut down correctly (like gui is gone but the process is still running) I want Mo2 to tell me that before I open it and start installing new mods or go mess with the files from the explorer. 
I'm not forbidding an alternative here, simply stating why it would not be a good idea to simply remove the box. 
If you have a good alternative and someone with the time to implement it I would welcome the new options.

**Comment by Al12rs** [comment] 2018-07-03 12:57
If you want to use the shortcut to start the game then what exactly of that box is getting in the way? You won't see it while playing and it will close itself when you finish unless something goes wrong in which case having that box will help.

**Comment by Viscerous** [comment] 2018-07-03 12:59
The problem is that it's unnecessary clutter and it impedes your workflow if you do choose to run two hooked programs concurrently. I doubt experienced users are in favour of having this parental lock put on them which they have to click through each time. I know I don't. It's also not exactly easy for normal users to 'accidentally' start a whole bunch of hooked programs as each needs to be added manually and they would know full well if they were launched hooked or not, as adding said program means you need it to be hooked for it to function the way you want to.

Having the option to disable it for experienced users should hurt no one.

**Comment by LePresidente** [comment] 2018-07-03 13:15
At this point, the general consensus if I read above is its not going to be removed any time soon by us, Though if someone is willing to do the work and as long its not set to enabled by default it shouldn't be an issue to merge though that would be up for debate when the pull request is done.

**Comment by Viscerous** [comment] 2018-07-03 13:29
Fair enough, appended the title in case anyone wants to pitch in. As stated from the start, it's not a big deal.

**Comment by Silarn** [comment] 2018-07-03 14:01
It sounds like what you really want is to be able to run additional programs through the VFS while the first is still running. This has been brought up before and is plausible with usvfs (unlike the old mo1 hooking method). Unless you're running a crack or something Steam will still open when you run a Steam game and tell you what game is running. One dialog is even less intrusive then that.

Ultimately though I think we need to restructure how the usvfs process monitoring is handled to do this properly.

**Comment by LostDragonist** [comment] 2018-12-21 21:16
[MO v2.1.6](https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.1.6) has been released and includes an option to prevent locking the GUI.  This can be found in Settings > Workarounds > Lock GUI when executable is running.  This is considered a very advanced feature and is not supported by the team.

**Comment by Viscerous** [comment] 2018-12-31 15:40
Just got around to testing this, it breaks loading through an MO created shortcut to some degree. Either MO isn't loaded entirely or it uses the default (vanilla) profile I left in. Not sure. Works fine obviously without disabling locking.

Followed up here instead of opening a new issue since it's not supported officially.

**Comment by IanMunster** [comment] 2020-06-04 22:21
(Sorry for the Necro)

Is it however possible to add a "Hide Mo2 is Locked" command?
For the users who know Mo2 is locked and want to hide the GUI?

Example: "X:\Mod Organizer 2\ModOrganizer.exe" "moshortcut://Game:Instance" -NoLockGUI

This way "advanced" user can use the command simply to hide the message-box, because they know Mo2 is needed to run and don't want to change anything within Mo2.

Thanks in advance!

**Comment by jaxseries2** [comment] 2021-01-04 23:29
> 
> Al12rs wrote:
> I don't see what the problem is with having that little box? It does not look good?

For the love of God, add an option to not have this window pop-up or display at all when launching through a executable shortcut such as Script Extender. You ask why a high end modder would want such an option? By our nature modders want to customize the experience and fix things they personally see as problems. THE PROBLEM is that this pop up letting us know MO is locked or running or whatever seriously screws with the way some games open into fullscreen. Literally screwing with my intro/menu mods cause this MO window wants to be on top even with bTopMostAlways in the ini of game.

**Comment by isanae** [comment] 2021-01-04 23:34
@jaxseries2 Just to clarify, MO has an option to disable locking the UI, which also hides the popup when running a shortcut. Are you asking for a separate option for running shortcuts and for launching programs from MO?

**Comment by isanae** [comment] 2021-01-05 01:51
Apparently, running shortcuts with locking disabled is rather broken. My apologies, working on a fix.

**Comment by isanae** [comment] 2021-01-05 12:07
The fix will be available on the discord within a few days in a development build. It will be released with 2.4 eventually, no date yet.

**Closed** 2021-01-05 12:06 UTC
Labels: bug
