### ISSUE TITLE
MO isn't running a certain type of mod. Installed 3 different faster sneak mods and they wont work.

### ISSUE THREAD

**Issue by alostsoul341** [ModOrganizer2/modorganizer#539] opened 2018-09-27 22:01 UTC
# The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Mod Organizer). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our discord channel

# Environment

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs

## USVFS
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

## MO Interface
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by alostsoul341** [comment] 2018-09-27 22:05
I have almost 200 mods running fine with NMM (at the same time) and started running MO to handle bigger mods. It installed Beyond Skyrim: Burma fine and no problems at all. But one little sneak mod wont run.

**Comment by AnyOldName3** [comment] 2018-09-27 22:08
It's completely impossible to even start working out what your issue is here as things are. Please fill in the report template so we have something to work with. I guarantee the issue isn't that MO just doesn't work with sneak mods, so we're going to at least need the names of the mods you couldn't make work.

**Comment by Al12rs** [comment] 2018-10-12 08:55
Closing since there was no asnwer, reopen if you have more info.

**Closed by Al12rs** 2018-10-12 08:55 UTC
