### ISSUE TITLE
Manually typing priority in load order doesn't work

### ISSUE THREAD

**Issue by hype-1** [ModOrganizer2/modorganizer#736] opened 2019-05-27 06:29 UTC
Since some beta version of 2.2.0 manually typing a priority number in the load order doesn't work anymore.
I can type the number, but other actions revert it back to the old value.
For example double clicking a mod in the left pane.

**Comment by Al12rs** [comment] 2019-05-27 09:56
Duplicate of #522 . I would be ideal to fix this before 2.2.1 release.

**Closed** 2019-11-27 19:50 UTC
Labels: bug, duplicate, issue report
