### ISSUE TITLE
usvfs_proxy_x86.exe marked as MALWARE

### ISSUE THREAD

**Issue by JHam215** [ModOrganizer2/modorganizer#532] opened 2018-09-22 21:38 UTC
# The problem

Bitdefended completed an update one 21 SEP 18, and then marked every mete.ini file as "infected with Atc4.Detection and moved to quarantine".   Then marked every other file in the My Mod organizer directory with the same "Atc4.Detection", and finally ended up decided that usvfs_proxy_x86.exe was the culprit. I've sent this same notification to Bitdefender as I believe this is a bunch of false positives. 

# Environment

Windows 10 Home 17134.285
Mod Organizer Verison 2.1.5
Bitdefender Total Security 2019 Build 23.0.10.31

# Details

n/a

## USVFS
currently quarantined. 

## MO Interface
n/a

**Comment by SuperSandro2000** [comment] 2018-09-22 22:16
Known issue. Nothing really we can do except to complain to the av's.
The problem is that what usvfs is doing is a bit hacky.
Then MO1 is not currently being developed. Please go to the mo2 repo for assistant.

**Comment by Project579** [comment] 2018-09-22 22:17
the thing is, usvfs does it in the cleanest way i've ever seen; and AV still complain.

**Comment by SuperSandro2000** [comment] 2018-09-22 22:50
True. If you don't trust us look at the source and compile it yourself or upload it to virustotal.com.
Some AV even complain about libs(.so) packaged in APK files.

**Comment by Al12rs** [comment] 2018-09-30 13:49
closing since we know of this

**Closed by Al12rs** 2018-09-30 13:49 UTC
