### ISSUE TITLE
Script extender log reports incompatible plugins

### ISSUE THREAD

**Issue by TheWanderer0794** [ModOrganizer2/modorganizer#1411] opened 2021-02-14 00:10 UTC
## The problem:
Recently MO2 notifications have been about issues with many SKSE related mods, like smooth cam, hdt smp, (skse64) havok fix and Racemenu, but with the difference that it specifically says that the skee64.dll is the one causing issues, by the way, i do have the latest versions of both skse64 ans Skyrim SE

This is the warning that MO2 is throwing at me:

Script extender log reports incompatible plugins
The failed plugins are: 

- skee version 1 (skee64.dll, RaceMenu) disabled, fatal error occurred while loading plugin.
- HavokFix version 2 (HavokFix64.dll, (SKSE64) Havok Fix) disabled, fatal error occurred while loading plugin.
- hdtSSEPhysics version 1 (hdtSMP64.dll, HDT-SMP (Skinned Mesh Physics)) disabled, fatal error occurred while loading plugin. 

## To Reproduce:

1. Have either of those mods installed.
2. try to run the game normally

## Environment:

* Mod Organizer Version that exhibits the issue: Mod Organizer 2 Version 2.3.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): Mod Organizer 2 Version 2.3.2
* Desktop OS/version used to run Mod Organizer: Windows 10

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
https://gist.github.com/TheWanderer0794/1aa0b3103bf2467a92eec20b328ed85e

### MO Interface:
https://gist.github.com/TheWanderer0794/df5ceaccdd8728f4b012a21528125599

**Comment by isanae** [comment] 2021-02-14 00:12
Go in the Settings, Diagnostics tab, change the log level to Debug, restart MO, reupload `mo_interface.log`.

**Comment by TheWanderer0794** [comment] 2021-02-14 02:40
Here it is:
https://gist.github.com/TheWanderer0794/b35605250c2529387cbe9f257e25cd58

By the way, are there any similar issues to this one? how were they fixed?

**Comment by AnyOldName3** [comment] 2021-02-14 02:44
I don't see how this is a MO2 issue. MO2's reading your SKSE64 log (which should be in your `Documents\My Games` directory, like the saves folder is) and telling you what it's found in there. The most likely issues are that you've got a too-new or too-old SKSE64 for the plugins you're using, as they tend to only work with one specific version.

**Comment by Qudix** [comment] 2021-02-14 03:33
skee64.dll is RaceMenu. Notice the missing 's' in the name

**Comment by AnyOldName3** [comment] 2021-02-14 15:40
Yes. It's still SKSE64 that's failing to load it and is logging its failure.

**Comment by Holt59** [comment] 2021-02-17 11:17
Closing since the issue is not related to MO2.

**Closed by Holt59** 2021-02-17 11:17 UTC
Labels: issue report
