### ISSUE TITLE
MO 2.2.0 - need to reinstall random mods

### ISSUE THREAD

**Issue by Atlntssplayer** [ModOrganizer2/modorganizer#716] opened 2019-05-17 14:53 UTC
## The problem:
I setup Skyrim Classic using MO 2.2.0 following the STEP Guide v2.10.0, so it's a pretty well known and clean setup of about 250 mods and everything works fine, but sometimes the game starts crashing 100% of the time. I then try to disable some mods, reinstall a few, change load order but after hours and hours of trying there is no real consequent solution.

After doing this for days, this is what I noticed and it seems pretty serious.

Sometimes mods don't work/don't load from my setup and they need to be reinstalled.
This happens out of the blue, without me doing anything.

4 pretty visible cases I managed to notice recently that made me think this might be the source of the problem:

1. I started the game through MO as usual and the main menu emblem wasn't spinning. It should spin because as per the STEP guide I have 'Main Menu Spinning Skyrim Emblem Average Speed' mod installed and it was enabled in the left pane of MO as usual.
So I reinstalled it and started the game, and it was spinning again.

2. Waterfalls disappeared. I reinstalled the waterfall and realistic water two mods and they became visible again.

3. Skyui reported SKSE not being present. I reinstalled it and the Skyui error stopped showing.

4. STEP compilation patch mod: when I disabled it, the game stopped crashing.
After reinstalling the patch, the game was working fine.

I think the reason for my game crashing right after I start a new playthrough is that mods don't load or become invisible to Skyrim randomly and unless it is something visible on the screen (like the spinning emblem or waterfalls missing), there is no indication as to which mod is acting up this way. 

I don't have antivirus, I disabled firewall and uac years ago. I'm admin on my win 7 system.

## To Reproduce:
I can't really reproduce this reliably as it happens randomly to mods in my mod list, at least that is how it seems.
I start the game in Riverwood and after walking out the game crashes. Then I disable and re-enable mods, reinstall a few and it is working again.
There doesn't seem to be any coherence or rule that would seem to cause or solve this other then reinstalling some mods.

## Environment:

* Mod Organizer Version that exhibits the issue: MO 2.2.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer: Windows 7 x64 Ultimate

**Comment by LostDragonist** [comment] 2019-05-17 16:49
This is guessing some but it sounds like you're having issues with the archive invalidation.  I'm thinking your vanilla BSAs, or maybe a mod's BSA, got redated which causes loose files to not override them.  

MO has a "redate BSAs" feature in the workarounds settings menu.  You might give that a shot.

**Comment by Atlntssplayer** [comment] 2019-05-17 20:28
Thank you for your answer!

I clicked Back-Date BSAs and now all the .bsa files in Skyrim directory have a date of 2000.01.01.
After this if I don't reinstall the mods that give me visible errors in-game (like waterfalls missing and Skyui not finding SKSE scripts etc), nothing happens, the same errors show up. Game crashes if all my mods are enabled. If I disable most of them then it runs, I just have the mentioned visible errors.

After reinstalling the water mods and SKSE, these errors go away. I don't know if they will come back now that I've done this re-dating thing. So far, before the re-dating, these errors came back after a day or so and I checked the mods in question against backups I have and they were the same byte-for-byte, even my MO profiles were the same, so it's not file system corruption. The most crazy thing I can't comprehend is that the problems goes away after I reinstall mods in MO, but on the disk everything is the same, every file, every directory, the meta.ini files of MO, everything. Still, the game stops crashing and the visible errors go away. And after a random amount of time it's happening again. At least that is how it was before 'I clicked re-dating BSAs'.

Anyway, can you tell me if in MO2 at the profile settings should 'Automatic Arhive Invalidation' be checked for Skyrim Classic?

If I go back to MO1 and check that option, will that solve this weird issue?

**Comment by LostDragonist** [comment] 2019-05-17 20:33
Another possibility is that the file attributes are affecting the game.  That's much more of a problem with Skyrim SE but I was told similar code does exist in Skyrim LE.  The issue is that the game has a broken check on which files it should load.  If the "archive" flag is missing, they may not be loaded.  The archive flag is used by various backup software (maybe even including Windows?) and is expected to be cleared and set as needed.

MO 2.2.0 adds a file attribute checker to allow for you to check and correct these conditions.  You can enable that in Settings > Plugins > Basic Diagnosis Plugin > check_fileattributes and set it to True.  You can do that by double-clicking False (or something like that).  When you run a tool or the game, it'll check the file attributes and prompt you to fix them if it finds problems.

**Comment by Al12rs** [comment] 2019-09-21 10:19
Closing this for organizational purposes, please reopen if you are still experiencing this problem.

**Closed by Al12rs** 2019-09-21 10:20 UTC
Labels: issue report

**Comment by Pleasantless** [comment] 2023-07-04 13:47
2023, still having this issue every couple of weeks or so on SkyrimSE.
Random files get corrupted (textures, meshes, scripts, animations, etc) I think even update.esm got corrupted once. 
It is simple to fix, but extremely tedious to go through each mod.

**Comment by AnyOldName3** [comment] 2023-07-04 13:54
That shouldn't be possible if your computer's working properly - even if MO2's VFS goes horribly wrong, it just gives handles to the original file to the application, so corrupting files is far from likely. Have you tried general Windows troubleshooting stuff like `chkdsk` and `sfc /scannow`?

**Comment by Pleasantless** [comment] 2023-07-04 13:56
I have tried chkdsk, but will try sfc /scannow
You think it may be a failing SSD?

**Comment by AnyOldName3** [comment] 2023-07-04 14:08
`sfc /scannow` detects operating system files that have been corrupted. Occasionally, something damages one (which could mean a single high-energy particle from space just happening to collide with the right part of your computer at the wrong time, or could be a hardware/software/firmware/BIOS fault), and that can make the OS do the wrong thing. Generally, `sfc` can fix things automatically - you just keep running it until it says there are no problems.

**Comment by Pleasantless** [comment] 2023-07-04 14:31
It seems no space particle targeted my PC, as the scan states "The operation completed successfully"

**Comment by AnyOldName3** [comment] 2023-07-04 15:35
That's not something I'd expect it to print out. If it's fixed things, it should say *Windows Resource Protection found corrupt files and successfully repaired them* and if there was nothing to fix, it should say *Windows Resource Protection did not find any integrity violations.* Both of those count as completing successfully.
