### ISSUE TITLE
Skyrim Special Edition - Zoomed to Top Corner

### ISSUE THREAD

**Issue by soven1988** [ModOrganizer2/modorganizer#755] opened 2019-06-06 18:39 UTC
## The problem:
Since last night when I launch Skyrim SP from the Mod Organiser the screen zooms in on the top left hand corner and I can only see about 1/4 of the screen.

## To Reproduce:
Steps to reproduce the behaviour:

Just launch the game through Mod Organiser.

## Environment:

* Mod Organizer Version that exhibits the issue: 2.2.0
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.3
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:

I installed a new mod, MystiriousDawn's HD Skyrim Overhaul, it installed fine but when I launched the game, I noticed I can only see a fraction of the screen as it zoomed in.  I have tried googling the problem but the 2 or 3 pages that can back with the same issue had suggestions that didn't work (such as launching the game from Steam, changing the resolution in the options or editing the SkyrimPrefs.ini file screen resolutions).  When I launch the game from Steam, it works fine but I can't play my game because of the mods I have installed.  I tried to remove all mods and reinstalling Skyrim but the issue remains.  I have also posted my issue on Everything Bethesda (facebook) and MystiriousDawn's HD Skyrim Overhaul Nexus page for any advice but so far no luck.  My game is completely unplayable and desperate for a solution,

## Link to Mod Organizer logs:
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder". You should close MO2 before sending or examining the logs as they are finished writing only after the program is closed.
[skse64.log](https://github.com/ModOrganizer2/modorganizer/files/3262976/skse64.log)
[skse64_loader.log](https://github.com/ModOrganizer2/modorganizer/files/3262977/skse64_loader.log)
[skse64_steam_loader.log](https://github.com/ModOrganizer2/modorganizer/files/3262978/skse64_steam_loader.log)

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your USVFS logs, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by Al12rs** [comment] 2019-06-06 21:02
To check whether the issue is related to one of the mods installed or your ini settings, see if it keeps happening in a new empty profile:
https://cdn.discordapp.com/attachments/403979692501106688/524939782435110924/unknown.png
https://cdn.discordapp.com/attachments/403979692501106688/524940397643038740/unknown.png

Also make sure you don't have any mods installed in actual game folder.

**Comment by Al12rs** [comment] 2019-09-21 10:22
Closing this for organizational purposes, please reopen if you are still experiencing this problem.

**Closed by Al12rs** 2019-09-21 10:22 UTC
Labels: issue report
