### ISSUE TITLE
Mod Manager 2 not working after updating to Windows 10 developer branche

### ISSUE THREAD

**Issue by mdeberts** [ModOrganizer2/modorganizer#1435] opened 2021-02-23 22:33 UTC
## The problem:
After updating my windows 10 Pro Insider Preview Build 21318 if I run mod manager 2 it starts.
If I start my skyrim sse as usual via SKSE it will popup the skse64_loader cmd window and then wont load anything.

Is this a problem due to my new windows build?
I also uninstalled some stuff and maybe uninstalled something important?

## To Reproduce:

1. get windows 10 pro dev branch
2. run mod manager 2
3. try to start skse64
4. wont load
5. doesnt matter if I use a clean version without any mods loaded or my usual mod list

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.0
* Last Mod Organizer Version that did not exhibit the issue (if applicable): none
* Desktop OS/version used to run Mod Organizer:

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
https://gist.github.com/mdeberts/7b51ce1ac817cf2d54c1d8aa475ab3bb

### MO Interface:
https://gist.github.com/mdeberts/95961b7b1b276a2a52e1f824fcae84b0

**Comment by Al12rs** [comment] 2021-02-23 22:36
Please see #1410

**Comment by Al12rs** [comment] 2021-02-23 22:37
duplicate of #1410

**Closed by Al12rs** 2021-02-23 22:37 UTC
Labels: duplicate, issue report

**Comment by mdeberts** [comment] 2021-02-24 07:23
puh you are saints it worked thx
