### ISSUE TITLE
MO2 Uninstallation Removes Majority Of Files (When Prompted Not To Remove)

### ISSUE THREAD

**Issue by MichaelDevers** [Modorganizer2/modorganizer#175] opened 2017-12-27 19:01 UTC
I'm just after uninstalling MO2 and when I was given the option to either completely remove everything ('Yes') or to keep specific folders, such as the downloads, mods, profiles, stylesheets, etc... I selected 'No' (Assuming it would keep the folders mentioned). However, it has permanently removed some of them folders and can not be restored.

Current MO2 build was the latest: V2.1.1

![capture1](https://user-images.githubusercontent.com/31483329/34390569-849cc412-eb38-11e7-812d-fbcc0551b811.jpg)

![capture2](https://user-images.githubusercontent.com/31483329/34390873-6e60e000-eb3a-11e7-8716-7dc21bb2272a.jpg)

**Comment by Silarn** [comment] 2017-12-29 06:07
This is probably a duplicate of #123

**Comment by LePresidente** [comment] 2018-04-13 15:49
Fixed in 2.1.2

**Closed by LePresidente** 2018-04-13 15:49 UTC
Labels: bug, duplicate, installer, needs investigation, potential fix
