### ISSUE TITLE
MO2 wont start anything

### ISSUE THREAD

**Issue by OnestormGX** [Modorganizer2/modorganizer#310] opened 2018-04-15 00:47 UTC
# The problem

I cant seem able to start any program/tool/.exe in general.
This is what it says when i try to launch anything:
failed to spawn "nvse_loader.exe": failed to start process (wrong parameter [87])
I cant seem able to launch ANYTHING no matter what i do, i tried running as administrator and the vast majority of tips i could find googling and it still says the same. Any tip?

# Environment

I'm using v2.1.2 On Fallout:New Vegas,WIN7

# Details
 Since i'm not very familiar with Mod organizer i cant give more information, if there is a step by step give of how to give more information about the problem i will be glad to follow it to help

**Comment by Al12rs** [comment] 2018-04-15 00:50
Can you give us your mo_interface log and follow these instructions for the usvfs log?
```
When reporting an issue, you should always provide your MO2 version, windows version (run winwer to see build number) and your mo_interface.log  that can be found in: 
\logs inside the ModOrganizer folder if you use a portable Instance, or in:
appdata\local\modorganizer\<InstanceName>\logs if you have a global instance of MO.
From MO2 v2.1.2 you can also open the logs folder from the new "Open folder" menu over the mod-list (Close MO before actually sending the Logs because those are written only after exiting the program).
```

**Comment by OnestormGX** [comment] 2018-05-05 06:36
Mod Organizer 2 (Installer Version)-6194-2-1-2
Microsoft Windows Version 6.1 (7601:Service Pack 1)
[mo_interface.log](https://github.com/Modorganizer2/modorganizer/files/1976393/mo_interface.log)

**Comment by JustGummy** [comment] 2018-05-12 13:01
This is probably a problem with your Anti-Virus.
Check if files like usvfs_x64.dll or usvfs_proxy_x86.exe (etc) are in quarantine and if so, restore those files.
You could also add your MO2 installation path to excluded paths for you antivirus.
This problem happens, because MO2 does not have the permission to access these files after they are added to quarantine (or similar) by an antivirus.

**Comment by Al12rs** [comment] 2018-08-03 10:52
Will close for lack of response and inability to reproduce in a few days.

**Comment by DankRafft** [comment] 2018-08-04 15:49
I still don't know what is causing it. It only happens with LOOT in my case and it happens rarely. Wrye Bash, xEdit and Creation Kit work fine. When it happens I get a blank LOOT window, closing the window leaves one hidden instance of LOOT in Task Manager active. That's also what causes the error message in MO2 when trying to restart LOOT. I have to close MO2, open Task Manager, close the hidden LOOT instance and restart MO2.

**Comment by LostDragonist** [comment] 2018-08-19 05:53
Closing due to lack of response from original reporter.  Anyone else having issues like this should create their own issue or hit up the discord channel for more timely help.

**Closed by LostDragonist** 2018-08-19 05:53 UTC
Labels: awaiting feedback, needinfo
