### ISSUE TITLE
Hiding files on the Conflicts tab causes the same mod to appear in both the "Overwrites" and "Overwritten by" columns

### ISSUE THREAD

**Issue by VariableReferee** [ModOrganizer2/modorganizer#1500] opened 2021-04-28 18:51 UTC
## The problem:
When looking at content on the Conflicts tab, and then using the "hide" and "unhide" feature, it causes the items in the "Overwrites" and "Overwritten by" columns to get messed up in such a way that the same mods will appear in both the "Overwrites" and "Overwritten by" columns. This is very reproducible. I have to close the window and open it back up to correct the display.

## To Reproduce:
1. Find a mod that overwrites lots of files in other mods and which also has file overwritten.
2. Access the conflicts tab.
3. Highlight several conflicting files, right-click them, and choose Hide.
4. The same mod(s) will not appear in both the Overwrite and Overwritten by columns. See pics below.

## Environment:
* Mod Organizer Version that exhibits the issue: 2.4.1
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
Before hiding:
https://cdn.discordapp.com/attachments/403979692501106688/835185841268850688/SPOILER_before.png

After hiding:
https://cdn.discordapp.com/attachments/403979692501106688/835185913851805747/SPOILER_after.png

**Comment by Al12rs** [comment] 2021-04-28 18:55
Duplicate of #1491 
I appreciate the detailed report though.

**Closed by Al12rs** 2021-04-28 18:55 UTC
Labels: issue report
