### ISSUE TITLE
MO2 detection of Skyrim.ini

### ISSUE THREAD

**Issue by MyHouseATL** [ModOrganizer2/modorganizer#477] opened 2018-08-09 11:59 UTC
I recently upgraded to the now MO2 and now MO2 doesn't recognize the -sse argument.  SSEdit, DynDOLOD, Merge Edit are all looking for Oldrim .ini's.  

I am unsure which MO2 I had previously, but it was working before.

I checked my pyCfg.py and it did have:

elif gameName == "skyrimse":
return ["skyrim.ini", "skyrimprefs.ini"]

https://gist.github.com/MyHouseATL/d394423d6c9e14ca38b158652f878a00

**Comment by LostDragonist** [comment] 2018-08-09 12:08
Click [this icon](https://imgur.com/aOsUsPF) and select "Open MO2 Logs folder" to be taken to the relevant logs.  Reproduce the problem, close MO2, and then post the mo_interface.log and latest usvfs_xx.log as a GitHub gist.

**Comment by MyHouseATL** [comment] 2018-08-10 20:12
According to my interface log, MO2 is not detecting SE.

**Comment by LostDragonist** [comment] 2018-08-10 20:18
It looks like you posted the usvfs log twice.  I don't see an interface log there.

MO2 uses a registry key to find the game.  Running the launcher will make sure that's correct.  After that, you'd want to check the game path in the MO2 Paths setting to make sure it's pointing to your game.

**Comment by MyHouseATL** [comment] 2018-08-10 20:43
Hmmm, when I click on that link, both show....
I can play Skyrim, it's just other programs like SSEEdit\DyDOLOD doesn't recognize SkyrimSE.  They all get pointed to Skyrim, which I have uninstalled.

**Comment by LostDragonist** [comment] 2018-08-10 20:48
Your gist has a file called mo_interface.log but the contents of that file are from a usvfs log.  It's really difficult to help you without that.

**Comment by MyHouseATL** [comment] 2018-08-10 21:00
Oh, sorry.  Try this...
https://gist.github.com/MyHouseATL/8f830b39449239fe2404b2390cc07d84

**Comment by MyHouseATL** [comment] 2018-08-10 21:00
Headed to work.  Will have to check comments later.  Thanks for looking LostD...

**Comment by LostDragonist** [comment] 2018-08-10 21:09
Based on that, I'm guessing your problem is due to having MO2 in your game directory.  This is a bad idea.  It's known to cause problems like this.  We're not entirely sure why.  The closest that MO2 should come to your game directory is C:/Games/steamapps/common/Mod Organizer.

Judging by the rest of your settings, you'd probably also want to change your MO2 Paths settings to also move the profiles and mods out of the game directory.

> 01:37:29 [D] looking for plugins in C:\Games\steamapps\common\Skyrim Special Edition\plugins

That line really scares me.  I don't know why MO2 would be starting from the Skyrim SE folder unless you dumped the entire contents of MO2 into the game folder.  That's probably worse than everything else.

I have some other concerns about the way you have it set up but I don't think they'd cause any problems...

**Comment by LostDragonist** [comment] 2018-08-10 21:16
And, just in case, please run the launcher of the game to make sure that registry key is populated correctly.  xEdit and other tools also use this to determine if a game is installed.  If it's not present or is incorrect, they'll throw a fit when trying to select that game.

**Comment by MyHouseATL** [comment] 2018-08-11 09:25
> That line really scares me. I don't know why MO2 would be starting from the Skyrim SE folder unless you dumped the entire contents of MO2 into the game folder. That's probably worse than everything else.

Ummm, yea.  That is how I ran MO for the last 3 years without issue. I figured, MO2 would run that way as well.  (Creature of habit...)  Also, all I have in the Mod Organizer folder is the mods\profiles\webcache and overwrite.  Probably shouldn't do that?
Should I also move the other tools outside with MO2?

**Comment by Zarggg** [comment] 2018-08-11 13:38
The virtual file system that MO2 uses is quite different from the file-linking method the original MO used.

To be safe, it's best to install any tools that you would run from within MO2 outside the game directory, unless its function requires it to be installed alongside game files (e.g., Wrye Flash, script extenders, etc)

**Comment by MyHouseATL** [comment] 2018-08-12 07:24
Last question, should all of MO2 be installed in Mod Organizer folder?  My set up: Mods\Profiles\Web cache\overwrite was the only thing installed in the Mod Organizer folder.

**Comment by MyHouseATL** [comment] 2018-08-12 07:51
Ok, not last question.  I'm am still getting an error message with Merge Plugins that the master plugin is in a lower load order than it is supposed to be.  Even though in the plugin of MO2, it is in the order it should be.  
And DynDOLOD is still having the same issue of being pointed to Oldrim.

**Comment by Al12rs** [comment] 2018-09-08 13:33
SSE and oldrim both use Skyrim.ini and Skyrimprefs.ini, they are just in different folders. What makes you think that DynDOLOD is looking at the oldrim INIs?

**Comment by Al12rs** [comment] 2019-01-19 23:21
Closing for organization, please reopen if there is still an issue.

**Closed by Al12rs** 2019-01-19 23:21 UTC
Labels: waiting on user
