### ISSUE TITLE
Not checking for esp masters after switching profiles

### ISSUE THREAD

**Issue by dunc001** [Modorganizer2/modorganizer#108] opened 2017-10-26 08:49 UTC
Plugin masters do not appear to be being rechecked on profile switch so profile specific plugins with common names (DynDOLOD.esp, etc) are showing as having missing masters after switching profiles, requiring to exit and relaunch MO2.

**Comment by Silarn** [comment] 2017-11-03 00:14
It looks like @LePresidente pushed a fix for this issue, so I'm adding it to the 2.1 milestone. If you can verify the fix with a recent build, I'll close this

**Comment by Silarn** [comment] 2017-12-12 20:12
On a related issue, we should also rescan plugin masters when exiting a running application. If I rebuild a bashed patch, I more or less have to restart MO (or remove and readd the plugin) to reload the masters.

**Comment by Al12rs** [comment] 2018-04-09 18:48
duplicate of #194

**Comment by Al12rs** [comment] 2018-04-09 19:01
closing this, will use the other one if needed

**Closed by Al12rs** 2018-04-09 19:01 UTC
Labels: bug, duplicate, potential fix
