### ISSUE TITLE
Importing/exporting Racemenu presets will not load/save CBBE morph slider values or XPMSE Slider Values

### ISSUE THREAD

**Issue by Rathalos300** [ModOrganizer2/modorganizer#377] opened 2018-05-24 11:48 UTC
# The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Mod Organizer). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to our discord channel

# Environment

* Mod Organizer Version that exhibits the issue:
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Mod Organizer:

# Details

If necessary, describe the problem you have been experiencing in more detail.

# Link to Mod Organizer logs
https://drive.google.com/drive/folders/1-LiTLaFpwT8N141mOSnoPw1bFi73hzq2
## USVFS
https://gist.github.com/Rathalos300/58c6a2d7f669cea5af3506baa643a82b

## MO Interface
https://gist.github.com/Rathalos300/16c49435cbbff8edbcf7154b695f6bbd

**Comment by Al12rs** [comment] 2018-12-11 11:08
@Rathalos300 We released a Dev build with a usvfs fix on Discord that hopefully fixes this issue as well, Could you try it out and confirm that it works now?
https://discord.gg/MB3CyMH

**Comment by Al12rs** [comment] 2018-12-28 13:09
Can anyone reproduce this issue on MO2.1.6 ?

**Comment by Al12rs** [comment] 2019-01-19 23:16
Closing for organization, reopen if you can reproduce still.

**Comment by LordOfLA** [comment] 2019-01-22 17:01
The following pertains to Skyrim Legendary Edition, _not_ Special Edition.

Here are some debug logs and racemenu jslot files from two runs of MO2 2.1.7 Alpha 6 and MO1 1.3.11 showing the differences in how jslot files are saved between MO1 and MO2.

Essentially MO2 seems to be preventing RaceMenu from saving complete presets. While Using MO2 All I can save is head data, race and gender. Details such as body/hand/foot paint, body scales, weapon placement/style, etc are not saved. Attempt the same preset changes on MO1 and complete data is saved.

Attached are the first and second debug runs in MO2, and two runs in MO1. Additionally, I will link to Imgur galleries showing screenshots of what I'm trying to save, and the results.

The differences between the first and second run of MO2 are as follows:

* Private Profile Redirector plugin disabled in the second run
* Racemenu presets have been moved from the MO2 overwrites folder to a profile overrides mod.

No changes occurred in MO1 runs.

Jslot files and MO profile files have been included as well as log files.

[MO2 VFS Debug Log for Github report - LordOfLA - MO2.1.7alpha6.zip](https://github.com/ModOrganizer2/modorganizer/files/2783774/MO2.VFS.Debug.Log.for.Github.report.-.LordOfLA.-.MO2.1.7alpha6.zip)

[MO2 Debug First Run Gallery](https://imgur.com/a/Ttgfl9w)

[MO2 VFS Debug Log for Github report - LordOfLA - MO2.1.7alpha6 - SecondRun.zip](https://github.com/ModOrganizer2/modorganizer/files/2783775/MO2.VFS.Debug.Log.for.Github.report.-.LordOfLA.-.MO2.1.7alpha6.-.SecondRun.zip)

[MO2 Debug Second Run Gallery](https://imgur.com/a/pksZsYH)

[MO2 VFS Debug Log for Github report - LordOfLA - MO1.3.11.zip](https://github.com/ModOrganizer2/modorganizer/files/2783777/MO2.VFS.Debug.Log.for.Github.report.-.LordOfLA.-.MO1.3.11.zip)

[MO1 Debug First Run Gallery](https://imgur.com/a/eYlFtFP) - Note the difference in filesizes between the MO2 and MO1 debug presets.

[MO2 VFS Debug Log for Github report - LordOfLA - MO1.3.11 - Second Run.zip](https://github.com/ModOrganizer2/modorganizer/files/2783778/MO2.VFS.Debug.Log.for.Github.report.-.LordOfLA.-.MO1.3.11.-.Second.Run.zip)

[MO1 Second Run Debug Gallery](https://imgur.com/a/c5eBphQ)

**Comment by LostDragonist** [comment] 2019-01-25 23:37
So far I've been unable to reproduce this issue with the following mod list on v2.2.0alpha9: 
![image](https://user-images.githubusercontent.com/7862539/51778408-1f773e80-20c7-11e9-8fa6-0251c81a4483.png)

Body morphs are saved and restored.  Body paints are saved and restored.  Weapons styles are saved and restored.

**Comment by LordOfLA** [comment] 2019-01-26 05:58
Just tested with alpha9 on my full load order and the issue still exists. Will Try a minimal load order of just aslal, skyui, racemenu, xpmse, fnis, body paint mod later today or tomorrow.

Debug log and JSlot file of this test run attached.

[MO2 VFS Debug Log - Alpha 9 Full Load Order - LordOfLA.zip](https://github.com/ModOrganizer2/modorganizer/files/2798665/MO2.VFS.Debug.Log.-.Alpha.9.Full.Load.Order.-.LordOfLA.zip)

**Comment by LordOfLA** [comment] 2019-01-26 16:37
Okay, fresh install of alpha 9 to new location. Copied minimal mods over to test my desired preset changes. Still not saving full data.

[Minimal setup at modwat.ch](https://modwat.ch/u/CrystallineRaindropsDebug/modlist)

[MO 2VFS Debug Log - Alpha 9 Minimal Test Order Fresh Install - LordOfLA.zip](https://github.com/ModOrganizer2/modorganizer/files/2799219/MO.2VFS.Debug.Log.-.Alpha.9.Minimal.Test.Order.Fresh.Install.-.LordOfLA.zip)

I can test on a smaller still setup if you want.

**Comment by LostDragonist** [comment] 2019-01-26 19:33
I wasn't able to find all of the mods present in the list above but I was able to find enough to reproduce the issue.  I was also able to make the problem go away again by disabling all of the mods not directly related to Race Menu.  Progress!  Will report back when I find the smoking gun.

**Comment by LordOfLA** [comment] 2019-01-26 20:01
Awesome! Was beginning to think it was unique to my PC. Already clean installed windows incase it was something wonky there.

If you need me to package up and provide the mods you couldn't find I can send them over but since you were able to reproduce the issue I'm guessing you won't need anything.

**Comment by LordOfLA** [comment] 2019-01-26 20:46
I'll try this out myself once I get my windows setup back to where it was before I reinstalled.

By manually installing mods do you mean manually unpack them with 7zip into a mod in the mods folder or drop them in skyrim\data?

**Comment by LostDragonist** [comment] 2019-01-26 21:01
Manually installing means installing in the Skyrim\data folder with no MO2 involvement.  

To be clear, I'm not asking you to do anything with that right now.  It's just a nice way to confirm that the issue is actually an MO2 issue and not a weird mod issue.  I know you kind of already confirmed that by using MO1 but that's the proper test to perform.  I guess in case MO1 was the reason it was working for some reason...?

**Comment by LordOfLA** [comment] 2019-01-26 21:15
I used MO1 as that was faster (Copy profile from mo2 to mo1, move mods folder over, carry on).

The problem also doesn't exist if I use Wrye Bash as mod manager which installs mods directly to the skyrim\data folder.

**Comment by LostDragonist** [comment] 2019-03-10 17:55
Fixed in https://github.com/ModOrganizer2/usvfs/commit/5f2493ab3c8526bcd32333537bf48aa079e6eaf1

**Closed by LostDragonist** 2019-03-10 17:55 UTC
Labels: fixed in next release, usvfs
