### ISSUE TITLE
Savegames are displayed with wrong timestamp

### ISSUE THREAD

**Issue by Horf** [ModOrganizer2/modorganizer#1268] opened 2020-10-25 11:43 UTC
## The problem:
Inside if MO2 the savegames are differring 7 hours from my local time (I think from GER to US ?) - If I made a save at 2:30 PM it will be 7:30 AM in MO2. It's not 'gamebreaking' but still confusing and I can't find any option to set the time.
The savegame itself still has the correct time (in this example 2:30 PM).

## Environment:

* Mod Organizer Version that exhibits the issue: 2.4.0alpha2
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): I can't say, I think it has always been so
* Desktop OS/version used to run Mod Organizer: Win10 Home 2004

##Screenshots:
![Inside MO2](https://user-images.githubusercontent.com/46202211/97106319-19115e80-16c1-11eb-9bf0-d47df1f3af1a.png)
![Savegame Properties Window](https://user-images.githubusercontent.com/46202211/97106322-1b73b880-16c1-11eb-837a-019196c6a793.png)

## USVFS:
https://pastebin.com/aAKZ6TF1

## MO Interface:
https://pastebin.com/jsxgpHs3

**Comment by Holt59** [comment] 2020-10-25 11:48
Duplicate of #1142 I think.

**Comment by Horf** [comment] 2020-10-25 11:55
Oops, sorry, haven't seen it. Yet I posted two screenshots.

**Comment by Holt59** [comment] 2020-10-25 11:55
@Horf The issue will be referenced in the duplicate. You can add additional information there if you want.

**Closed by Holt59** 2020-10-25 11:55 UTC
Labels: issue report
