### ISSUE TITLE
2.2.1 update changed some tool settings?

### ISSUE THREAD

**Issue by Zaflis** [ModOrganizer2/modorganizer#948] opened 2019-12-25 22:28 UTC
## The problem:
I updated MO to 2.2.1 from previous major version and i use it for Skyrim LE and its CK etc. It has all been working fine for years but now i was getting some error number when starting CK and it just went back to MO. Then i went to check CK start settings, and the overwrite Steam AppID wasn't there. I set it to 202480 it was supposed to be and then everything worked again.

## To Reproduce:
- Install old version.
- Set launch properties for Creation Kit and make sure it works. Set its Steam override ID.
- Install patch from MO2, will the ID be gone?

## Environment:
* Mod Organizer Version that exhibits the issue: 2.2.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.1.6 propably.
* Desktop OS/version used to run Mod Organizer: Win10-Home-64bit.

## Details:
This is a _really_ low priority issue that i don't care about because it was so easy to workaround for. If you cannot quickly find a mistake in update process that would change the tools that way then feel free to close. I used Creation Kit many times before updating even very recently and there is no way i would have removed the ID myself. Unless it worked without the ID in earlier version but that is very unlikely, i always knew about it as fix to CK issues and i used it.

**Comment by LostDragonist** [comment] 2019-12-26 02:01
I can confirm that is an issue when upgrading from 2.2.0 to 2.2.1.  MO doesn't correct upgrade executables that were previously defaulted (custom=false).

There should be a check added to `ExecutablesList::load` or `ExecutablesList::upgradeFromCustom` that looks for `custom == false` and use the default settings for the executable if the condition is met.  Currently, it takes the stored Steam App ID (which is blank) and applies it going forward.

**Comment by isanae** [comment] 2019-12-29 20:48
This is unfortunate and it's a bug in my migration code. Since 2.2.1 has already been out for months and 2.2.2 is coming out soon without a fix, this is pretty low priority, but I'll fix it eventually.

**Comment by isanae** [comment] 2020-12-28 09:41
Closing because the affected version is really old and I never got around to fixing this.

**Closed by isanae** 2020-12-28 09:41 UTC
Labels: area: executables, bug, issue report
