### ISSUE TITLE
2.x: NXM Handler Initialization can set up a fallback to an existing nxmhandler causing loops

### ISSUE THREAD

**Issue by gerbilOFdoom** [Modorganizer2/modorganizer#62] opened 2017-02-26 03:55 UTC
Attempting to download a mod via Download with Manager spawns unlimited copies of nxmhandler.exe when nxmhandler.ini contains

`1\games=skryim`

when it should contain

`1\games=skyrimse`

**Comment by Tkdmaster** [comment] 2017-02-28 09:01
I can confirm this problem, though it is sporadic at best... I have found it shows up, for me, mostly when downloading large mods.

**Comment by azraal** [comment] 2017-04-15 13:10
I don't know if that helps but I have the issue with any profiles that are not set as portable installations:
I have:
fo4 (portable mode) no issue
new vegas issues
skyrim (the old one) issues

**Comment by Leosky** [comment] 2017-05-22 16:06
removing execution permission from nxmhandler fix endless process creation. It's a shitty workaround but it work, just remove exec rights and reset them.

**Comment by NoICE** [comment] 2017-05-23 16:27
I did run into this too. I noticed then when I run nxmhandler.exe that it tries to run nxmhandler.exe for each game and that is what does the loop. It was configured like that right after fresh install.

When I tried to correct it, it always returned to default, because the nxmhandler updates it's config when it exits and because it was running in the background, it was constantly overwriting my config. It  was very frustrating. I didn't know that its config is in nxmhandler.ini, good to know.

**Comment by Silarn** [comment] 2017-11-28 00:17
I've not seen this issue since I started working on MO2. Is anyone from this thread around that can test this on the latest builds?

**Comment by gerbilOFdoom** [comment] 2017-11-30 15:13
I've noticed this happens when I have multiple installs of MO2 and try to use an NXM link for a game when the nxm handler for another game's MO2 install is set as the primary handler.

**Comment by erasmux** [comment] 2017-12-04 08:02
I had a similar problem, and noticed it was caused by the following lines in the nxmhandler.ini:
2\games="oblivion,fallout3,fallout4,falloutnv,skyrim,skyrimse,other"
2\executable=c:\Games\Skyrim_SE_mods\ModOrganizer\nxmhandler.exe
This means that if I click on a mod for a game not covered before these lines then nxmhandler will spawn itself which will against spawn itself and so on.

Removing the above lines fixed the problem for me.

**Comment by Silarn** [comment] 2017-12-07 21:07
I think the problem is figuring out why this particular entry gets created.

**Comment by Silarn** [comment] 2017-12-11 16:46
I guess ultimately we need to improve the automatic nxmhandler management. I believe this stems from the fact that nxmhandler tries to create an entry for existing NXM link handlers as a fallback. But if that happens to be a second nxmhandler executable, we're going to run into these problems.

At the very least, we should ignore any other registered nxmhandler.exe entry when the current nxmhandler is initializing.

Additionally, I've found associating a game in the settings often overwrites an existing entry instead of appending to it - which disassociates the previous game(s).

**Comment by Silarn** [comment] 2017-12-13 19:15
I've added some code to check for this possibility. It wont fix existing broken installs - you will have to launch nxmhandler and remove the problem entry - but it should prevent it from happening.

I also modified nxmhandler to merge games being added with an existing entry rather than replacing them unless it's being forcibly re-added.

**Comment by Evolution0** [comment] 2017-12-15 15:08
Even on a clean install if you do not first go into MO2 and associate nexus links from the settings (even if you get a dialog asking you if you want to) it will cause this endless loop. I had to resort to `taskkill /F /IM nxmproxy.exe` (You sometimes have to do this multiple times so they stop spawning)

**Comment by Project579** [comment] 2017-12-27 10:32
The proxy on the latest version 2.1.0.1 does not cause Infinite loops but it does not seem to create the nxmhandler.ini file automatically causing it to never register the games. Manually creating the file solves the problem as expected.

**Comment by Silarn** [comment] 2017-12-29 06:19
MO generally attempts to add any new game instance created to the active nxmhandler - and the 'associate' button within the MO settings should now add the current game to an existing entry instead of overwriting it.

You shouldn't have to create the file manually if you perform one of those actions.

**Comment by Silarn** [comment] 2017-12-29 06:22
FYI a clean install requires you to remove any files within AppData as well as the MO install directory. As I said, this doesn't fix an existing broken setup but should prevent MO from creating a broken setup automatically.

**Comment by gerbilOFdoom** [comment] 2017-12-29 06:49
Might be a good idea for the temporary workarounds to be added to an FAQ accessible from the readme, especially the relevant taskkill command.

**Comment by Silarn** [comment] 2017-12-29 09:28
Well, fixing a broken setup should be as simple as running nxmhandler and clearing out any bad (recursive) entries for the same (or another) nxmhandler process. Typically only NMM or MO exes should be in the handler list. If nxmhandler is instantiated while NMM is the current handler it should add an NMM handler as a 'fallback' to the handler list. Following that, any new MO.exe entries will be added to the top of the handler list (located either in the AppData directory of the same MO directory as the 'active' nxmhandler).

Previously, the nxmhandler code _might_ add an existing (but different) nxmhandler (set as the active NXM handler in Windows) the same way as NMM - creating a recursive nxmhandler process for any games not currently claimed by an NMM or MO exe. The new code should exclude adding another nxmhandler.exe this way.

**Closed** 2018-05-16 14:38 UTC
Labels: bug, potential fix
