### ISSUE TITLE
Mods not loading (for certain applications) when Mod Organizer is placed within the game directory

### ISSUE THREAD

**Issue by JadeRoyale** [ModOrganizer2/modorganizer#169] opened 2017-12-27 03:41 UTC
# The problem
MO2 not loading mods when using skse64 to launch game. It will just load the vanilla game.

# Environment

* Mod Organizer Version that exhibits the issue: 2.1.0.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable): 2.0.8.3b
* Desktop OS/version used to run Mod Organizer: Windows 10 (I'm sorry, I'm so ashamed.)

# Details

When I launch skse64 (build 2.0.6) from MO2 it will not load any mods. I just get a vanilla game.
Next... I launched using just the SE launcher from MO2 and all the mods loaded up with errors saying that skse64 is not present some mods won't work... yadda yadda. Expected that! Still they all loaded.
Lastly, I dropped some skse64 dependent mods in the vanilla data folder outside of MO2 and launched skse64 directly from the Skyrim SE folder.  (Just to make sure the skse64 file wasn't corrupted.)  It launched and loaded the mods with no issues. 

## USVFS  
(These probably won't be helpful. My game is not crashing because of this issue. The mods just aren't loading.  The only time and reason my game is crashing right now is because I am an idiot and I forget to use a clean save when testing.)
https://gist.github.com/JadeRoyale/875d2c30afccde17f581c4faefb6966a

## MO Interface

https://gist.github.com/JadeRoyale/85e1b9b93aa2aec595e6a1bf4d708785

**Comment by Silarn** [comment] 2017-12-27 08:29
Please use winver to identify your specific Windows build number.

**Comment by Kharos** [comment] 2017-12-27 11:45
I have the same problem with Fallout 4 on Windows 7 (build 7601, SP1).
- starting FO4Edit: Mods load (the built-in .esm's are disabled initially and I need to enable them, but after that everything works).
- starting Fallout4.exe: Mods load (but of course some mods complain that F4SE is not loaded)
- starting f4se_loader.exe: No mods loaded, looks like the virtual file system does not work at all. Maybe the loader creates a child process and that child process can somehow not see the virtual file system?

**Comment by JadeRoyale** [comment] 2017-12-27 13:26
Version 1709 (OS Build 16299.125)

**Comment by Zarggg** [comment] 2017-12-27 16:04
I was going to post about this as well, but @Kharos basically listed everything I was going to say.

**Comment by JadeRoyale** [comment] 2017-12-27 17:27
Didn't think to check before but there are no problems with SSEEdit. It is loading all the mods without issue.

**Comment by LastReaction** [comment] 2017-12-28 17:32
I've found the issue in the logs, the link below points to the line in question. The USVFS log states that it seems to be failing to inject into SkyrimSE.exe due to an unknown exception. One thing I notice is that there are two slashes before SkyrimSE.exe in the file path, when it looks like there should only be one slash. That's just a guess though.

[usvfs-2017-12-28_17-20-29.log](https://gist.github.com/LastReaction/3da6a4cd499463720e6b8315ced342e5#file-usvfs-2017-12-28_17-20-29-log-L175)

**Comment by Kharos** [comment] 2017-12-28 19:33
Retested with 2.1.1.0 and same behavior. Yep, the log says:
`20:17:53.413 <6312:4520> [E] failed to inject into C:\Games\SteamLibrary\SteamApps\common\Fallout 4\\Fallout4.exe: Unknown exception`
Full file is attached below.

I had trouble finding the logs. The settings page of Mod Organizer 2 says that 'logs and crash dumps are stored under your current instance in the logs and crashDumps folders`. I (manually) installed MO2 into a subfolder of Fallout 4 (so for example the mods are at `C:\Games\SteamLibrary\SteamApps\common\Fallout 4\ModOrganizer2\mods`); but the log files were in `%LOCALAPPDATA%\ModOrganizer\Fallout 4\logs`. Is that expected behavior?


[usvfs-2017-12-28_19-16-22.log](https://github.com/LePresidente/modorganizer/files/1591948/usvfs-2017-12-28_19-16-22.log)

**Comment by JadeRoyale** [comment] 2017-12-28 21:32
MO2 2.1.1  No change. Mods not loading with skse64.
[usvfs-2017-12-28_21-02-05.log](https://github.com/LePresidente/modorganizer/files/1592162/usvfs-2017-12-28_21-02-05.log)

**Comment by Silarn** [comment] 2017-12-29 06:14
Erasmux has been investigating similar issues. If you can hop on the Discord channel (see the repository description) we can use any info to help trace down this problem. It seems extremely intermittent and specific to the systems experiencing the problem, and we'll need as much info as possible to track down the cause.

That being said, there are a couple known causes:

* Your MO should not be installed within your game directory as this is known to cause intermittent problems. Try moving it to the root of your drive or somewhere similar.
* If, for some reason, you are using symlinks or junctions to install your games to a different location than the expected path, MO currently is unable to deal with this. Updating the settings in your ModOrganizer.ini to point to the true location of the game directory will generally fix the problem.

**Comment by Kharos** [comment] 2017-12-29 08:31
- Not using any symlinks or something like that for game installation path.
- The issue is not intermittent for me, it is 100% reproducible.
- I also want to point out again that MO2 works correctly for me with both FO4Edit and Fallout4.exe; it only fails with f4se_loader.exe. So it is not a general failure of MO2 on my system.
- 2.0.7 works correctly

If I understand this thread correctly, JadeRoyale has the same problem with Skyrim SE: MO2 works with base game, but not with skse64, 2.0.8.3b worked correctly.

My instincts tell me that we hit an edge when running the script extender on our systems, as it obviously works for most users. As a developer with knowledge of the code base (which I lack) I would probably try to find the root cause of the `Unknown exception` that is present in all three log files. Maybe create a  special build that logs more details about this exception and send it to us for testing?

I can try to catch one of you on Discord, but all developers were yellow when I tried. At what time (including timezone) should I try?

**Comment by Silarn** [comment] 2017-12-29 09:20
Well, the root game directory isn't (or shouldn't be) mapped in the VFS - just the Data directory. So the VFS file mappings are unlikely to be at fault. I do wonder about the usvfs dll, though. That's interesting. There was one change we made that I might attempt to revert to see how it affects things. There may not be a reason to even use that code with the way USVFS works. It was an attempt to fix issues with SKSE plugin DLLs failing to load - but that could have also been due to the handle leaks we've fixed.

**Comment by JadeRoyale** [comment] 2017-12-29 18:09
The only thing I can ascertain from Discord is that I need to add a friend.... :-(  Which is why I dumped it way back when. Do you possibly have a link?

**Comment by GrantSP** [comment] 2018-01-01 22:46
Just now installed a portable version of MO2 2.1.1 into my FO4 game folder and it is reading everything just fine.
Will grab a f4se mod and install that and see what happens.

**Comment by erasmux** [comment] 2018-01-01 23:06
Rereading the remarks here, and taking into account the reports of many users not having any problems running similar setups. I agree with Kharos that this is an edge case that causes the usvfs injection to fail.

In theory yes we could investigate the current usvfs implementation but with my current plans for usvfs I don't see that as a good use of the limited time devs (and mainly me) have for usvfs support.

Do note that I will most likely be working on a usvfs rewrite that will solve this and other usvfs core problems. This will eventually either come to pass or fall through. at which point if this issue still persists I will investigate and fix it.

**Comment by GrantSP** [comment] 2018-01-01 23:10
f4se mods are being called correctly for me so I'm not sure what is the edge case for the others.

**Comment by JadeRoyale** [comment] 2018-01-03 00:16
f4 is ctd on load screen. Don't know if it is MO2 related or not haven't looked into closely. @erasmux Sounds good to me. I can wait awhile longer.  I appreciate your efforts! Thanks!

**Comment by erasmux** [comment] 2018-01-03 08:06
@JadeRoyale I am not sure what issues you have now but they seem to be unrelated to this one:

Your original usvfs-2017-12-28_21-02-05.log indeed shows the "failed to inject into..." which is exactly the "Mods not loading" issue.

But your more recent usvfs-2017-12-29_20-11-14.log does not show this (in fact the only real info there is that usvfs was injected successfully to the game process but doesn't show SKSE at all which causes me to suspect MO/SKSE are not properly configured). And finally your last message states a CTD which again is a different issue.

Please try to keep on topic as this is a bug tracking system. For general support please join the discord channel linked on the main github page. If joining the discord channel is out of the question for you, open a new unrelated issue and supply info. For a CTD try to collect a dump file (not always possible) and if not supply interface and usvfs log files (set log level to debug).

**Comment by JadeRoyale** [comment] 2018-01-03 15:01
@erasmux  The primary issue is SkyrimSE (F4 is unrelated in my case). The difference in the logs is launching with and without SKSE64.  If I launch "with" skse64 nothing but a vanilla game loads, it won't load ANY mods at all. If I launch with SE launcher, "no" skse64.... MO2 loads up all the mods beautifully as it should. Then I get the error SKSE64 is not present and some mods may not function, of course we knew that. That is the only issue I am concerned with at this time. Again... I can wait for your next usvfs roll out.  As I said before, I really do appreciate your help!

**Comment by TechAngel85** [comment] 2018-01-21 03:37
@JadeRoyale 
I'm curious if this is still an issue for you with the latest beta of USVFS available on the Discord. I mention it because Dirty Weasel mentioned this issue in his recent video, which led me to search it out, and I've seen no mention of the betas being tested.

**Comment by JadeRoyale** [comment] 2018-02-08 04:35
@TechAngel85 
"Yes! I am using usvfs 0.3.1-beta4 and it is working as it should.  I did have to move MO2's default "mods" folder to a separate location but I can live with that... cause... it is working! Yeah! Thanks millions!"  (Sorry, I did not respond sooner. My husband had a heart attack and I haven't been playing but he is doing better now..... and MO2 IS WORKING!)

**Comment by Al12rs** [comment] 2018-02-27 22:41
Is anyone here that can reproduce the issue willing to help a Dev investigate the issue? None of the devs has this problem so it is very hard to pin down, if you can reproduce and are willing to test and report ping me on the discord server.

**Comment by isanae** [comment] 2020-12-28 12:19
Reopen if the problem still occurs.

**Closed by isanae** 2020-12-28 12:19 UTC
Labels: bug, needs investigation, usvfs
