### ISSUE TITLE
So many issues in Oblivion.

### ISSUE THREAD

**Issue by tommyonsn** [ModOrganizer2/modorganizer#1536] opened 2021-06-10 13:50 UTC
## The problem:
for example:
1. DarNified UI(omod)
   can not be installed.
2. Elven Map Redux, Dynamic Map...
  installed. but no work.
## Environment:
mo2.4.2

**Comment by Holt59** [comment] 2021-06-10 14:01
You need to be more precise regarding the problem you're facing.

DarNified UI can be installed with the OMOD installer since MO2 2.4 using the OMOD installer, and many people have done so without any issues, so you need to tell us what the problem actually is.

Same for the other mods, many of them I've been installed and used without any issues by MO2 users, so you need to be more precise on "but no work".

If you have issue installing those mods through MO2, come by the Discord so someone can help you install them properly.

**Comment by isanae** [comment] 2021-06-10 14:01
I'm closing this because it's just a rant. If you have a specific problem, open a new issue with a descriptive title and steps to reproduce.

**Closed by isanae** 2021-06-10 14:01 UTC
Labels: issue report
