### ISSUE TITLE
Problems with usvfs on Windows 10 build 21313

### ISSUE THREAD

**Issue by isanae** [ModOrganizer2/modorganizer#1410] opened 2021-02-13 21:54 UTC
We're not sure what's going on yet, but usvfs fails for some programs on the most recent Insider Build, 21313. The only solution for now is to rollback. We'll update this when we get more information.

**Comment by isanae** [comment] 2021-02-21 22:58
We have a tentative fix for the problem. Download [usvfs-insider.zip](https://github.com/ModOrganizer2/modorganizer/files/6018792/usvfs-insider.zip) and extract in MO's installation folder. Backup the existing files just in case. Report here if it fixes the problem or causes more.

**Comment by whraven** [comment] 2021-02-22 05:38
Work perfectly on 21318 pre-release (210216). Saved me a LOT of trouble! Thanks.

**Comment by clausagerskov** [comment] 2021-02-22 20:02
+1 works perfectly on 21318 Pro

**Comment by WYVERN2742** [comment] 2021-02-24 00:32
Fix confirmed working on 10.0.21318 Build 21318 👍

**Comment by n8ohu** [comment] 2021-02-24 05:00
I can confirm the fix works for me as well.

**Comment by mdeberts** [comment] 2021-02-24 07:24
worked thank you very much

**Comment by IridiumH** [comment] 2021-02-26 20:13
not working on 21322.1000
[usvfs-2021-02-26_20-06-18.log](https://github.com/ModOrganizer2/modorganizer/files/6052227/usvfs-2021-02-26_20-06-18.log)
[mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/6052236/mo_interface.log)

**Comment by Holt59** [comment] 2021-02-26 21:05
> 
> 
> not working on 21322.1000
> [usvfs-2021-02-26_20-06-18.log](https://github.com/ModOrganizer2/modorganizer/files/6052227/usvfs-2021-02-26_20-06-18.log)
> [mo_interface.log](https://github.com/ModOrganizer2/modorganizer/files/6052236/mo_interface.log)

You should have a crash dumps associated, could you upload it?

**Comment by JimBeamBeagle** [comment] 2021-02-26 23:29
tested and working on 21322

**Comment by IridiumH** [comment] 2021-02-27 05:02
@Holt59 
[crashDumps.zip](https://github.com/ModOrganizer2/modorganizer/files/6053759/crashDumps.zip)

**Comment by IridiumH** [comment] 2021-02-27 05:15
@Holt59 
I update to 2.4.0 and overwrite with files from here again. now it works fine. sorry for bothering you..

**Comment by duachuot** [comment] 2021-02-28 05:10
I also use Windows 10 build 21322, upgraded to MO2 2.4.0 and overwrite 4 files patch for usvfs-insider.zip. Finally, SKSE cannot run, but other run normally (FNIS, Skyrim se launcher, Virtual Folder..)
Pls help me. Tks so much.

**Comment by Al12rs** [comment] 2021-02-28 11:00
@duachuot it is likely that your skse/game is crashing due to one of your mods or in files. Create a new empty profile with default INI settings and try starting it there.

**Comment by duachuot** [comment] 2021-02-28 11:37
No, it is not. I just restored previous build 21301 and it run normally. So, I choose to stop update windows for a week in order to play MO2 - Skyrim SE.

**Comment by Holt59** [comment] 2021-02-28 11:44
> No, it is not. I just restored previous build 21301 and it run normally. So, I choose to stop update windows for a week in order to play MO2 - Skyrim SE.
> 
> 
> 
> 

It might also be an SKSE issue with latest build, did you try running SKSE outside of MO2 before rolling back to 21301?

**Comment by duachuot** [comment] 2021-02-28 12:32
I'm using SKSE 2.0.19 for Skyrim SE 1.5.97. And now, I am playing Skyrim SE with window 10 build 21301.

**Comment by DracoWhitefire** [comment] 2021-03-05 06:17
I can confirm that Insider build 21322.1000 has the same issue, and that the above replacement files do indeed work on that build as well. Thanks!

**Comment by isanae** [comment] 2021-03-14 20:30
We released these DLLs with 2.4.1 RC1 but found that they broke at least FNIS, so we reverted the changes for RC2. We were a bit surprised because nobody reported problems in this thread. We'll keep working to find a solution.

**Comment by isanae** [comment] 2021-03-18 02:51
Here's another set of DLLs that seem to work better. Thanks to Qudix for building them. [usvfs-insider-v2.zip](https://github.com/ModOrganizer2/modorganizer/files/6160977/usvfs-insider-v2.zip)

**Comment by JimBeamBeagle** [comment] 2021-03-18 14:06
WinBuild 21337, MO 2.4.1.rc2 with v2 of usvfs.
Wyre Bash is now saving the bashed patch back up into the mod directory. (v1 left it in the data directory of the game folder)
Save games are save back to to the profile correctly. (v1 the ess files were staying in the _MOSaves directory)

**Comment by arosalind** [comment] 2021-04-17 02:48
> 
> 
> Here's another set of DLLs that seem to work better. Thanks to Qudix for building them. [usvfs-insider-v2.zip](https://github.com/ModOrganizer2/modorganizer/files/6160977/usvfs-insider-v2.zip)

After 3 days of head scratchin' (on 21359), this fixed the problem for me as well. Thanks. Is there a reason why these modified DLLs haven't been integrated into the v2.4.1 release?

**Comment by LostDragonist** [comment] 2021-11-23 00:04
This should be fixed as of the 2.4.2 release. Closing.

**Closed by LostDragonist** 2021-11-23 00:04 UTC
Labels: usvfs
