### ISSUE TITLE
MO2 causes crash on load when using 3 specific F4SE dll mods together

### ISSUE THREAD

**Issue by passerby5** [ModOrganizer2/modorganizer#170] opened 2017-12-27 05:54 UTC
# The problem

There is a strange MO2 issue that causes the game to crash on load when using all three of the following mods together:
- Extended Dialogue Interface (XDI): https://www.nexusmods.com/fallout4/mods/27216
- Better Console - F4SE: https://www.nexusmods.com/fallout4/mods/26582
- Crafting Highlight Fix: https://www.nexusmods.com/fallout4/mods/27479

If using any combination of 2 of the 3 mods above, there are no issues. But once all 3 are on at once, the game will crash on load (either fairly immediately or while it's trying to load into the Main Menu).

This is an MO2 issue as when the third mod's DLL is moved to the FO4 data folder, it will not crash.

Others have been discussing this on the "Better Console - F4SE" post page about specifically this issue and I was able to reproduce.

https://www.nexusmods.com/fallout4/mods/26582/?tab=posts&navtag=https%3A%2F%2Fwww.nexusmods.com%2Ffallout4%2Fajax%2Fcomments%2F%3Fmod_id%3D26582%26page%3D1%26sort%3DDESC%26pid%3D0%26thread_id%3D5966088&pUp=1

jachichorro says:

> Tested on an fresh Mod Organizer profile with the only mods being Better Console, Crafting Highlight Fix, and XDI. Using any combination of only 2 out of the 3 works fine, but using all 3 together results in CTD at startup.

MrTroubleMaker says:

>@ jachichorro I use mod organizer as well. I think it has an issue. If you move the dll's from the mod organizer folders and place them in the games data f4se plugin folder the ctd issue stops (at least for me).

# Environment

Tested this with MO2 v2.1.0.1. However, the comments quoted above pre-date v2.1's release.

**Comment by EsOmEs** [comment] 2017-12-27 08:56
I have the issue too but if I disable just better consoles all other F4SE mods I have (9) work fine together. I think this is due to the fact that even though the authors claim that the mods are F4SE version independent, they are NOT. The same happened after the update to game version x.x.40. after all of them rebuilt the plugins they ALL worked together like a charm (until the next game version came out).
I think this has nothing to do with ModOrganizer.

**Comment by juliocoliveira** [comment] 2017-12-27 14:50
I'm with this issue too. I cannot launch F4SE any more.
I have this error when trying to launch F4SE from MO.
```
SHGetFolderPath 00000005 failed (result = 80004005 lasterr = 00000000)
Assertion failed in IDebugLog.cpp (64): SUCCEEDED(err) (code = FFFFFFFF80004005 (-2147467259))
```

And a crash window from F4SE A component of Fallout 4 Script Extender has stopped working.
And was working fine before the 2.1 update.

**Comment by CptMcSplody** [comment] 2017-12-27 20:06
Can this issue be replicated outside MO?

**Comment by passerby5** [comment] 2017-12-28 06:33
@juliocoliveira 
Is what you're experiencing something different? According to the people I quoted, they were experiencing this issue before the release of v2.1. Does the problem go away if you move the dlls to the FO4 data folder?

@CptMcSplody 
If your question was directed at me, the reason why this is brought up as an MO2 issue is that when the F4SE Plugin DLLs are placed outside of MO (and in the FO4 data folder), the issue goes away.

**Comment by passerby5** [comment] 2017-12-28 06:46
Disregard the open/close issue above. Accidentally hit the wrong button while commenting.

**Comment by hugalafutro** [comment] 2018-01-05 21:23
I had this issue too, I'm using many F4SE addons, and now suddenly after Floating Damage mod was updated, I can load all of them including Better Console. Previously I would get crash just before menu if I enabled Better Console in MO.

**Comment by Al12rs** [comment] 2018-12-28 13:10
Can anyone reproduce this on 2.1.6 ?

**Comment by hugalafutro** [comment] 2018-12-28 22:37
On 2.1.6 I use following F4SE plugins together without any issue:

Achievements
Better Console
Clock Widget
Crafting Highlight Fix
DEF_UI translations
DEF_ESH Explosives Swap Hotkey
Faster Workshop
HUD Plus Plus
MCM
Place Anywhere
Rename Anything
Extended Dialogue Interface

so that would be a no.

Totally unrelated:
What still happens though is, everytime F4SE updates, loading game claims XDI.esm is missing, to fix you have to move the esm into overwrite, load, save, move it back to mod folder and it will work until next time F4SE updates.

**Comment by Qudix** [comment] 2018-12-28 22:38
That shouldn't happen on 2.1.6 anymore. Did you reinstall XDI first?

**Comment by Al12rs** [comment] 2018-12-28 23:12
Closing this then, @hugalafutro thanks for confirming

**Closed by Al12rs** 2018-12-28 23:12 UTC
Labels: bug, needs investigation, usvfs, waiting on user
