### ISSUE TITLE
Tutorial Bug

### ISSUE THREAD

**Issue by Khitt92** [ModOrganizer2/modorganizer#1458] opened 2021-03-11 00:23 UTC
## The problem:
I am new to Mod Organizer 2 and was trying to learn how to mod using the tutorial, but every time I got to the segment that talked about right clicking on a mod and going into the Information tab, the tutorial bugs out and refuses to continue to the next task.

## To Reproduce:

1. Go to 'Help'
2. Click on 'Tutorial'
3. Click on any of the Tutorials.
4. Follow the instructions as normal.

## Environment:

* Mod Organizer Version that exhibits the issue: v2.4.0
* Last Mod Organizer Version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 10

## Details:
If necessary, describe the problem you have been experiencing with more details and pictures.

## Link to Mod Organizer logs:
Right click on the log window at the bottom of MO2, set log level to debug, restart Mo2 and reproduce the problem.
To access the log files you can press the Open folder icon over the modlist and select "Open MO2 Logs folder".

### USVFS:
Create a [GIST](https://gist.github.com) which is a paste of your latest USVFS log, and link them here.
Do _NOT_ paste your full USVFS logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the USVFS logs!

### MO Interface:
Create a [GIST](https://gist.github.com) which is a paste of your mo_interface logs, and link them here.
Do _NOT_ paste your full mo_interface logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include the mo_interface logs!

**Comment by isanae** [comment] 2021-03-11 00:48
Duplicate of #1419, fixed in 2.4.1.

**Closed by isanae** 2021-03-11 00:48 UTC
Labels: issue report
